### ISSUE TITLE
Port the latest k-graph

### ISSUE THREAD

**Issue by searchivarius** [nmslib/nmslib#100]

**Comment by davidanastasiu** [comment]
If this is for http://www.kgraph.org/, you should know v.1.4 does not change the internals one little bit. The author just added a small API for returning the similarities in addition to the neighbors. Other than that, it's the same exact library is v.1.2.

**Comment by searchivarius** [comment]
@davidanastasiu the title is a bit misleading, we don't even have a proper k-graph version yet, because it wasn't open-sourced until recently. What I ported was the old implementation of NN-descent, which ships with the search function.

Regarding the diffs in versions: one big difference was that the latest k-graph has symmetric neighboring links. SW-graph used symmetric links from the get-go, but not k-graph. Eventually it was noticed that symmetric links can improve performance quite a bit.

However, I am not sure if this feature was in 1.2. When was 1.2 released? Symmetric links were added around May 2016.

**Comment by davidanastasiu** [comment]
I'm not sure when v.1.2 was released. His web page does not record the date, and the repo does not have releases. I just remember going through the trouble of updating some of my code that used the library for 1.4 and running experiments, only to basically get identical results as previous experiments I had run on 1.2. I then looked at the code diff and found the minimal changes... If your code was on 1.2, I just wanted to save you the trouble,

It does seem that the repo (https://github.com/aaalgo/kgraph) has had some more recent updates, but I have not delved into it at all, so I am not sure if they're any updates to the method.

**Comment by searchivarius** [comment]
Good to know, thank you! The updates that I describe are dated by May-June 2016. Did you check the code before?

**Comment by gokceneraslan** [comment]
> Actually, I am not sure exactly the date... It was sometime last summer, while I was working on this paper [http://davidanastasiu.net/pdf/papers/2016-AnastasiuK-IA3-pl2knn.pdf] for a workshop in SC 16. I used v.1.4 of KGraph for that paper, but v 1.2 for this paper [http://davidanastasiu.net/pdf/papers/2015-AnastasiuK-CIKM-l2knng.pdf], in which I compared against K-Graph v.1.2 (NN-Descent in the paper). Sorry for the confusion...

@davidanastasiu are you planning to put the code for L2Knng* and pL2Knng on Github? It'd be great to write Python wrappers for them as well.

**Comment by davidanastasiu** [comment]
That's the plan, when I get a chance... Been busy with some other projects,
but I'd like to create a sparse NN library with pL2Knn, pL2AP, and Python
wrappers. In the meantime, L2Knng and L2AP (serial codes) are on my
website: http://davidanastasiu.net/software/l2knng/,
http://davidanastasiu.net/software/l2ap/.
