### ISSUE TITLE
Additional measures of intrinsic dimensionality

### ISSUE THREAD

**Issue by searchivarius** [nmslib/nmslib#103]
port/implement the following metrics:

1) Local Intrinsic Dimensionality: L. Amsaleg, O. Chelly, T. Furon, S. Girard, M. E. Houle,
K. Kawarabayashi, and M. Nett. Estimating local intrinsic
dimensionality

2) Relative Contrast: J. He, S. Kumar, and S. Chang. On the difficulty of nearest
neighbor search. In ICML, 2012.

**Comment by chasingegg** [comment]
Where do we have these metrics?

**Comment by searchivarius** [comment]
Hi @chasingegg frankly speaking I have implemented only one metric so far. However, I don't even include it into the new version of the library. In the previous versions I have only this:
```
similarity_search/apps/report_intr_dim.cc
```

**Comment by searchivarius** [comment]
PS: @chasingegg these metrics turned out to be less useful than we expected.
