### ISSUE TITLE
Error in make on Linux

### ISSUE THREAD

**Issue by johanneshk** [nmslib/nmslib#114]
Hi,

I'm trying to build this project, but I have some issues:
https://gist.github.com/johanneshk/dfb170acc469047b6aac108ed3d3f4a4

Any ideas? Thanks!
 Johannes

**Comment by searchivarius** [comment]
Hi, thank you for reporting this.
Please, tell me more about:

CPU
Linux Version
GCC version 
many thanks!

**Comment by johanneshk** [comment]
CPU: Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz
Linux: 4.4.13-1-MANJARO #1 SMP PREEMPT Wed Jun 8 09:21:59 UTC 2016 x86_64 GNU/Linux
GCC: gcc (GCC) 6.1.1 20160602

**Comment by searchivarius** [comment]
Thanks, I will have a look. We didn't test such new GCC yet.

**Comment by johanneshk** [comment]
It's not to pressing for me at the moment, since I have to complete some other stuff before I look into this again. Plus, I can try an older version of GCC, which would be a good workaround: So from my side, as I said, it's not that important!
