### ISSUE TITLE
Range queries for SW-graph & HNSW

### ISSUE THREAD

**Issue by searchivarius** [nmslib/nmslib#130]
implement

**Comment by disa-mhembere** [comment]
Hello @searchivarius so was it your determination that rangequery for hnsw is abandoned at this point then?

**Comment by searchivarius** [comment]
@disa-mhembere could you answer my e-mail? It's not impossible, but I'd like to know a bit more.

**Comment by ProtossSine** [comment]
hi, @searchivarius, Is hnsw suitable for range search? Is there any possible performance gap between range search and KNN search for hnsw algorithm?

Looking forward your reply.

Thanks ^_^

**Comment by searchivarius** [comment]
We haven't implemented it, sorry.

**Comment by jtibshirani** [comment]
@searchivarius thanks for the great library and set of algorithms. I am investigating whether we could add range queries as part of our ongoing work in Lucene around HNSW (https://issues.apache.org/jira/browse/LUCENE-9004). Do you have any ideas/ suggestions (even very rough) on how range queries might be implemented?

**Comment by searchivarius** [comment]
Hi could you send me an email?

***@***.***

Thank you!

**Comment by searchivarius** [comment]
Uuups @jtibshirani the e-mail is leo at boytsov.info . Sometimes security features go way to far.
