### ISSUE TITLE
Separate indexing and searching parameters

### ISSUE THREAD

**Issue by searchivarius** [nmslib/nmslib#15]
We need to be able to specify search parameters that can be changed during the search phase. In this way, we can modify them and re-run queries without rebuilding the index.

**Comment by JWalker1995** [comment]
Was there any progress on this? I'm interested in using a mahalanobis metric that I can specify at query time.

**Comment by searchivarius** [comment]
@JWalker1995 it's a really old closed issue: We have had separate query-time parameters for a long-time now. This original design flaw has been long fixed.

**Comment by JWalker1995** [comment]
Thank you!
