### ISSUE TITLE
minor fix (getting rid of labels alltogether)

### ISSUE THREAD

**Issue by shubaoliu** [nmslib/nmslib#174]
In similarity_search/include/object.h, line 93:
```
92  inline IdType    id()         const { return *(reinterpret_cast<IdType*>(buffer_)); }
93  inline LabelType label()      const { return *(reinterpret_cast<LabelType*>(buffer_ + LABEL_SIZE)); }
94  inline size_t datalength()    const { return *(reinterpret_cast<size_t*>(buffer_ + LABEL_SIZE + ID_SIZE));}
```

I guess it line 93 should be
```
93  inline LabelType label()      const { return *(reinterpret_cast<LabelType*>(buffer_ + ID_SIZE)); }
```
, since we need to add the offset of "id" (instead of the offset of "label") to get the address of label.
This should have no effect on the result, since in the implementation, ID_SIZE == LABEL_SIZE.

**Comment by searchivarius** [comment]
Yes, good point. But I am going to get rid of it anyways. Didn't prove to be useful. In the unlikely case, anybody wants to test classification accuracy, this can be done by the code that calls our API. That is, the mapping from IDs to labels can be kept by an external application.

**Comment by searchivarius** [comment]
I am going to reclassify it a bit so that this objective (remove labels) isn't forgotten.

**Comment by shubaoliu** [comment]
I agree. Label information is better kept outside, and focus this library on data indexing.

**Comment by TieSKey** [comment]
Are u still planning to remove the label? I find it useful for my usecase but if removing it increases search speed then plz go for it :P

**Comment by searchivarius** [comment]
@TieSKey not in this version of nmslib, I don't think speed will be affected. However, could tell me more about the use case? It may be in general terms: leo@boytsov.info. Knowing why it's useful may help me with future versions.

**Comment by TieSKey** [comment]
Oh it is quite simple. I have several vectors that belong/describe the same document. 
For each vector I set the owner document id as the label and the vector id (relative to each document) as the object id.
Ofc this can be done outside of the index but using the label it is quite convenient.
