### ISSUE TITLE
Switching to use #pragma once

### ISSUE THREAD

**Issue by searchivarius** [nmslib/nmslib#175]
Let's use #pragma once, b/c it's supported by all major compilers.

**Comment by elfring** [comment]
This construct does not belong to [the programming language standard](https://stackoverflow.com/questions/1695807/why-isnt-c-cs-pragma-once-an-iso-standard "Why isn't C/C++'s “#pragma once” an ISO standard?").

**Comment by searchivarius** [comment]
Hi @elfring great point and I am aware of this. This is why I haven't switched yet. However, the current C-way of simulating #pragama once is ugly and error prone. For example, copy-pasting a template space or method and forgetting to update these define names creates subtle problems. Besides, do you known any major compiler that doesn't support #pragma once? Clang, gcc, intel, and Visual Studio all do.
