### ISSUE TITLE
Documentation updates for 2.0

### ISSUE THREAD

**Issue by searchivarius** [nmslib/nmslib#190]
1. Check if SW-graph still has init*Attempts parameters.
2. Update manual readme to highlight examples of using library as explained in e.g., https://gitter.im/nmslib/Lobby?at=591a5f8c8a05641b11876827

Thanks!

**Comment by JulianKingman** [comment]
@searchivarius is there documentation written for MACOS, or does that come in version 2?

**Comment by searchivarius** [comment]
Hi @JulianKingman there's not special documentation for MACOS, but things are similar to Linux.
