### ISSUE TITLE
Support for ids as a string

### ISSUE THREAD

**Issue by DavidGOrtega** [nmslib/nmslib#214]
Hi, great work!

Supporting ids as a string would be extremely useful. For some cases ids are not just a number, so another structure is needed to be maintained.

**Comment by searchivarius** [comment]
Hi, @DavidGOrtega thank you for the kind words. There is some support for strings, but this 
1) requires a custom space
2) can be used from the query server only.
I am thinking about adding this to 2.0, but this is not going to be soon.

**Comment by thess24** [comment]
@searchivarius How do you format your data to include ids in the query server? I haven't been able to figure it out by looking through the examples/documentation. Right now, each row of my data that is being loaded into the query server is in the form:

.021 .045 .501 .099 .245

How do I go about adding numerical/string ids for each row?

**Comment by searchivarius** [comment]
@thess24 this is currently supported only for custom spaces, which space do you need it for?

**Comment by rbrthogan** [comment]
Just gonna add my +1 to this issue. Would be create to not need to maintain separate structure to interpret your ids

**Comment by searchivarius** [comment]
@rbrthogan but that is just a couple of lines in Python. And what about people who want integer IDs?

**Comment by rbrthogan** [comment]
@searchivarius sure, not at all suggesting that integer ids be replace, only to extend to allow strings. I know it is easy to work around, but adding this flexibility would make the index API much nice in some situations. 

Not urgent. 

Thanks for the work on a great library :)
