### ISSUE TITLE
Suggestion: simplify Windows build instructions

### ISSUE THREAD

**Issue by lsorber** [nmslib/nmslib#245]
The "Quick Start on Windows" part of the README says you need Visual Studio 2015 Express and CMake for Windows. A more lightweight solution is to ask users to install [Microsoft Visual C++ 2015 Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) (and make sure they keep the included Windows 8 SDK selected, which is the default), that's all they really need together with `pybind11` (which they can `conda install`).

**Comment by searchivarius** [comment]
@lsorber I should really try this, besides there seems to be various issues with Windows builds.

**Comment by lsorber** [comment]
Of course. Steps I took to reproduce on a fresh Windows environment:
1. Install Microsoft Visual C++ 2015 Build Tools with the Windows 8 SDK. The 2017 version doesn't work. The 2015 Build Tools with the Windows 10 SDK may work, haven't tested.
2. `conda install pybind11`
3. `pip install nmslib`

**Comment by scottgigante** [comment]
Just a note that building `bdist_egg` on a machine with Visual Studio installed and then installing it on a machine without seemed to work - at the very least the install was successful and `python_bindings/tests/bindings_test.py` passed.

**Comment by scottgigante** [comment]
Windows binaries are up! Looks like installation instructions have been simplified too.

**Comment by searchivarius** [comment]
@scottgigante actually, I will need to try re-compile with the latest Visual Studio. But, binaries are easy to install now.
