### ISSUE TITLE
Unknown MS compiler version 1900

### ISSUE THREAD

**Issue by munitech4u** [nmslib/nmslib#247]
I am trying to pip install the package and it is throwing me error:

ValueError: Unknown MS compiler version 1900.

Is it a problem with my MS build compiler version?

I have MS build 15.0 installed on windows 7

**Comment by searchivarius** [comment]
Which version of the Python?

**Comment by munitech4u** [comment]
3.5

**Comment by searchivarius** [comment]
@munitech4u thank you, I will try to reproduce this week.

**Comment by munitech4u** [comment]
I found a workaround to let the windows compile it, by adding environment variable: VS90COMNTOOLS - value >>%VS140COMNTOOLS%. But it's unable to build wheel with error: 

ws Kits\10\include\10.0.15063.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10
\include\10.0.15063.0\ucrt" /EHsc /Tpnmslib\similarity_search\src\method\proj_vp
tree.cc /Fobuild\temp.win-amd64-3.5\Release\nmslib\similarity_search\src\method\
proj_vptree.obj /EHsc /openmp /O2 /DVERSION_INFO=\"1.6.3\"
  proj_vptree.cc
  c:\users\mbansa001c\appdata\local\temp\pip-build-ob7jfqrp\nmslib\nmslib\simila
rity_search\include\object.h(123): warning C4267: '=': conversion from 'size_t'
to 'int', possible loss of data
  .\nmslib\similarity_search\include\distcomp.h(244): warning C4244: 'initializi
ng': conversion from '::size_t' to 'float', possible loss of data
  nmslib\similarity_search\src\method\proj_vptree.cc(133): warning C4267: 'argum
ent': conversion from 'size_t' to 'unsigned int', possible loss of data
  nmslib\similarity_search\src\method\proj_vptree.cc(84): note: while compiling
class template member function 'void similarity::ProjectionVPTree<float>::Create
Index(const similarity::AnyParams &)'
  nmslib\similarity_search\src\method\proj_vptree.cc(248): note: see reference t
o class template instantiation 'similarity::ProjectionVPTree<float>' being compi
led
  nmslib\similarity_search\src\method\proj_vptree.cc(235): warning C4267: 'argum
ent': conversion from 'size_t' to 'const unsigned int', possible loss of data
  nmslib\similarity_search\src\method\proj_vptree.cc(226): note: while compiling
 class template member function 'void similarity::ProjectionVPTree<float>::Searc
h(similarity::KNNQuery<dist_t> *,similarity::IdType) const'
          with
          [
              dist_t=float
          ]
  nmslib\similarity_search\src\method\proj_vptree.cc(212): warning C4267: 'argum
ent': conversion from 'size_t' to 'const unsigned int', possible loss of data
  nmslib\similarity_search\src\method\proj_vptree.cc(199): note: while compiling
 class template member function 'void similarity::ProjectionVPTree<float>::Searc
h(similarity::RangeQuery<dist_t> *,similarity::IdType) const'
          with
          [
              dist_t=float
          ]
  nmslib\similarity_search\src\method\proj_vptree.cc(45): warning C4267: 'argume
nt': conversion from 'size_t' to 'similarity::IdType', possible loss of data
  nmslib\similarity_search\src\method\proj_vptree.cc(40): note: while compiling
class template member function 'similarity::Object *similarity::ProjectionVPTree
<float>::ProjectOneVect(::size_t,const similarity::Query<dist_t> *,const similar
ity::Object *) const'
          with
          [
              dist_t=float
          ]
  nmslib\similarity_search\src\method\proj_vptree.cc(169): note: see reference t
o function template instantiation 'similarity::Object *similarity::ProjectionVPT
ree<float>::ProjectOneVect(::size_t,const similarity::Query<dist_t> *,const simi
larity::Object *) const' being compiled
          with
          [
              dist_t=float
          ]
  c:\users\mbansa001c\appdata\local\temp\pip-build-ob7jfqrp\nmslib\nmslib\simila
rity_search\include\params.h(189): warning C4244: '=': conversion from 'const in
t' to 'float', possible loss of data
  nmslib\similarity_search\src\method\proj_vptree.cc(60): note: see reference to
 function template instantiation 'void similarity::AnyParamManager::GetParamOpti
onal<float,int>(const std::string &,ParamType &,const DefaultType &)' being comp
iled
          with
          [
              ParamType=float,
              DefaultType=int
          ]
  nmslib\similarity_search\src\method\proj_vptree.cc(49): note: while compiling
class template member function 'void similarity::ProjectionVPTree<float>::SetQue
ryTimeParams(const similarity::AnyParams &)'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\1
4.10.25017\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I.\nmslib
\similarity_search\include -Ic:\anaconda3\Include -IC:\Users\mbansa001c\AppData\
Roaming\Python\Python35\Include -Ic:\anaconda3\lib\site-packages\numpy\core\incl
ude -Ic:\anaconda3\include -Ic:\anaconda3\include "-IC:\Program Files (x86)\Micr
osoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\Include" "-IC:\Pro
gram Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "-IC:\Program File
s (x86)\Windows Kits\10\include\10.0.15063.0\um" "-IC:\Program Files (x86)\Windo
ws Kits\10\include\10.0.15063.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10
\include\10.0.15063.0\ucrt" /EHsc /Tpnmslib\similarity_search\src\method\seqsear
ch.cc /Fobuild\temp.win-amd64-3.5\Release\nmslib\similarity_search\src\method\se
qsearch.obj /EHsc /openmp /O2 /DVERSION_INFO=\"1.6.3\"
  seqsearch.cc
  c:\users\mbansa001c\appdata\local\temp\pip-build-ob7jfqrp\nmslib\nmslib\simila
rity_search\include\object.h(123): warning C4267: '=': conversion from 'size_t'
to 'int', possible loss of data
  nmslib\similarity_search\src\method\seqsearch.cc(160): warning C4267: 'argumen
t': conversion from 'size_t' to 'similarity::IdTypeUnsign', possible loss of dat
a
  nmslib\similarity_search\src\method\seqsearch.cc(146): note: while compiling c
lass template member function 'void similarity::SeqSearch<float>::Search(similar
ity::KNNQuery<dist_t> *,similarity::IdType) const'
          with
          [
              dist_t=float
          ]
  nmslib\similarity_search\src\method\seqsearch.cc(181): note: see reference to
class template instantiation 'similarity::SeqSearch<float>' being compiled
  nmslib\similarity_search\src\method\seqsearch.cc(125): warning C4267: 'argumen
t': conversion from 'size_t' to 'similarity::IdTypeUnsign', possible loss of dat
a
  nmslib\similarity_search\src\method\seqsearch.cc(111): note: while compiling c
lass template member function 'void similarity::SeqSearch<float>::Search(similar
ity::RangeQuery<dist_t> *,similarity::IdType) const'
          with
          [
              dist_t=float
          ]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\1
4.10.25017\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I.\nmslib
\similarity_search\include -Ic:\anaconda3\Include -IC:\Users\mbansa001c\AppData\
Roaming\Python\Python35\Include -Ic:\anaconda3\lib\site-packages\numpy\core\incl
ude -Ic:\anaconda3\include -Ic:\anaconda3\include "-IC:\Program Files (x86)\Micr
osoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\Include" "-IC:\Pro
gram Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "-IC:\Program File
s (x86)\Windows Kits\10\include\10.0.15063.0\um" "-IC:\Program Files (x86)\Windo
ws Kits\10\include\10.0.15063.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10
\include\10.0.15063.0\ucrt" /EHsc /Tpnmslib\similarity_search\src\method\simple_
inverted_index.cc /Fobuild\temp.win-amd64-3.5\Release\nmslib\similarity_search\s
rc\method\simple_inverted_index.obj /EHsc /openmp /O2 /DVERSION_INFO=\"1.6.3\"
  simple_inverted_index.cc
  c:\users\mbansa001c\appdata\local\temp\pip-build-ob7jfqrp\nmslib\nmslib\simila
rity_search\include\object.h(123): warning C4267: '=': conversion from 'size_t'
to 'int', possible loss of data
  .\nmslib\similarity_search\include\distcomp.h(244): warning C4244: 'initializi
ng': conversion from '::size_t' to 'float', possible loss of data
  nmslib\similarity_search\src\method\simple_inverted_index.cc(162): warning C42
67: 'argument': conversion from 'size_t' to 'unsigned long', possible loss of da
ta
  nmslib\similarity_search\src\method\simple_inverted_index.cc(151): note: while
 compiling class template member function 'void similarity::SimplInvIndex<float>
::CreateIndex(similarity::AnyParamManager &)'
  nmslib\similarity_search\src\method\simple_inverted_index.cc(242): note: see r
eference to class template instantiation 'similarity::SimplInvIndex<float>' bein
g compiled
  nmslib\similarity_search\src\method\simple_inverted_index.cc(185): warning C42
67: 'argument': conversion from 'size_t' to 'unsigned long', possible loss of da
ta
  nmslib\similarity_search\src\method\simple_inverted_index.cc(208): warning C42
67: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data
  c:\users\mbansa001c\appdata\local\temp\pip-build-ob7jfqrp\nmslib\nmslib\simila
rity_search\include\space\space_sparse_vector_inter.h(204): warning C4267: 'argu
ment': conversion from 'size_t' to 'uint32_t', possible loss of data
  nmslib\similarity_search\src\method\simple_inverted_index.cc(166): note: see r
eference to function template instantiation 'void similarity::UnpackSparseElemen
ts<float>(const char *,::size_t,std::vector<similarity::SparseVectElem<float>,st
d::allocator<_Ty>> &)' being compiled
          with
          [
              _Ty=similarity::SparseVectElem<float>
          ]
  nmslib\similarity_search\src\method\simple_inverted_index.cc(151): note: while
 compiling class template member function 'void similarity::SimplInvIndex<float>
::CreateIndex(similarity::AnyParamManager &)'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\1
4.10.25017\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I.\nmslib
\similarity_search\include -Ic:\anaconda3\Include -IC:\Users\mbansa001c\AppData\
Roaming\Python\Python35\Include -Ic:\anaconda3\lib\site-packages\numpy\core\incl
ude -Ic:\anaconda3\include -Ic:\anaconda3\include "-IC:\Program Files (x86)\Micr
osoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\Include" "-IC:\Pro
gram Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "-IC:\Program File
s (x86)\Windows Kits\10\include\10.0.15063.0\um" "-IC:\Program Files (x86)\Windo
ws Kits\10\include\10.0.15063.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10
\include\10.0.15063.0\ucrt" /EHsc /Tpnmslib\similarity_search\src\method\small_w
orld_rand.cc /Fobuild\temp.win-amd64-3.5\Release\nmslib\similarity_search\src\me
thod\small_world_rand.obj /EHsc /openmp /O2 /DVERSION_INFO=\"1.6.3\"
  small_world_rand.cc
  c:\users\mbansa001c\appdata\local\temp\pip-build-ob7jfqrp\nmslib\nmslib\simila
rity_search\include\object.h(123): warning C4267: '=': conversion from 'size_t'
to 'int', possible loss of data
  .\nmslib\similarity_search\include\method/small_world_rand.h(92): warning C426
7: 'initializing': conversion from 'size_t' to 'similarity::IdType', possible lo
ss of data
  nmslib\similarity_search\src\method\small_world_rand.cc(764): warning C4267: '
initializing': conversion from 'size_t' to 'similarity::IdType', possible loss o
f data
  nmslib\similarity_search\src\method\small_world_rand.cc(750): note: while comp
iling class template member function 'void similarity::SmallWorldRand<float>::Sa
veIndex(const std::string &)'
  nmslib\similarity_search\src\method\small_world_rand.cc(862): note: see refere
nce to class template instantiation 'similarity::SmallWorldRand<float>' being co
mpiled
  nmslib\similarity_search\src\method\small_world_rand.cc(771): warning C4267: '
initializing': conversion from 'size_t' to 'similarity::IdType', possible loss o
f data
  nmslib\similarity_search\src\method\small_world_rand.cc(155): warning C4267: '
argument': conversion from 'size_t' to 'unsigned long', possible loss of data
  nmslib\similarity_search\src\method\small_world_rand.cc(141): note: while comp
iling class template member function 'void similarity::SmallWorldRand<float>::Ad
dBatch(const similarity::ObjectVector &,bool,bool)'
  nmslib\similarity_search\src\method\small_world_rand.cc(357): note: see refere
nce to function template instantiation 'void similarity::SmallWorldRand<float>::
AddBatch(const similarity::ObjectVector &,bool,bool)' being compiled
  nmslib\similarity_search\src\method\small_world_rand.cc(162): warning C4267: '
argument': conversion from 'size_t' to 'similarity::IdType', possible loss of da
ta
  nmslib\similarity_search\src\method\small_world_rand.cc(175): warning C4267: '
argument': conversion from 'size_t' to 'similarity::IdType', possible loss of da
ta
  nmslib\similarity_search\src\method\small_world_rand.cc(219): warning C4267: '
initializing': conversion from 'size_t' to 'similarity::IdType', possible loss o
f data
  nmslib\similarity_search\src\method\small_world_rand.cc(199): note: while comp
iling class template member function 'void similarity::SmallWorldRand<float>::De
leteBatch(const std::vector<similarity::IdType,std::allocator<_Ty>> &,int,bool)'

          with
          [
              _Ty=similarity::IdType
          ]
  nmslib\similarity_search\src\method\small_world_rand.cc(227): warning C4267: '
initializing': conversion from 'size_t' to 'similarity::IdType', possible loss o
f data
  nmslib\similarity_search\src\method\small_world_rand.cc(269): warning C4267: '
initializing': conversion from 'size_t' to 'similarity::IdType', possible loss o
f data
  nmslib\similarity_search\src\method\small_world_rand.cc(273): warning C4267: '
initializing': conversion from 'size_t' to 'similarity::IdType', possible loss o
f data
  nmslib\similarity_search\src\method\small_world_rand.cc(714): error C2065: '_M
M_HINT_T0': undeclared identifier
  nmslib\similarity_search\src\method\small_world_rand.cc(670): note: while comp
iling class template member function 'void similarity::SmallWorldRand<float>::Se
archOld(similarity::KNNQuery<dist_t> *) const'
          with
          [
              dist_t=float
          ]
  nmslib\similarity_search\src\method\small_world_rand.cc(557): note: see refere
nce to function template instantiation 'void similarity::SmallWorldRand<float>::
SearchOld(similarity::KNNQuery<dist_t> *) const' being compiled
          with
          [
              dist_t=float
          ]
  nmslib\similarity_search\src\method\small_world_rand.cc(714): error C3861: '_m
m_prefetch': identifier not found
  nmslib\similarity_search\src\method\small_world_rand.cc(717): error C2065: '_M
M_HINT_T0': undeclared identifier
  nmslib\similarity_search\src\method\small_world_rand.cc(717): error C3861: '_m
m_prefetch': identifier not found
  nmslib\similarity_search\src\method\small_world_rand.cc(609): error C2065: '_M
M_HINT_T0': undeclared identifier
  nmslib\similarity_search\src\method\small_world_rand.cc(561): note: while comp
iling class template member function 'void similarity::SmallWorldRand<float>::Se
archV1Merge(similarity::KNNQuery<dist_t> *) const'
          with
          [
              dist_t=float
          ]
  nmslib\similarity_search\src\method\small_world_rand.cc(556): note: see refere
nce to function template instantiation 'void similarity::SmallWorldRand<float>::
SearchV1Merge(similarity::KNNQuery<dist_t> *) const' being compiled
          with
          [
              dist_t=float
          ]
  nmslib\similarity_search\src\method\small_world_rand.cc(609): error C3861: '_m
m_prefetch': identifier not found
  nmslib\similarity_search\src\method\small_world_rand.cc(612): error C2065: '_M
M_HINT_T0': undeclared identifier
  nmslib\similarity_search\src\method\small_world_rand.cc(612): error C3861: '_m
m_prefetch': identifier not found
  nmslib\similarity_search\src\method\small_world_rand.cc(637): error C2065: '_M
M_HINT_T0': undeclared identifier
  nmslib\similarity_search\src\method\small_world_rand.cc(637): error C3861: '_m
m_prefetch': identifier not found
  nmslib\similarity_search\src\method\small_world_rand.cc(645): warning C4267: '
=': conversion from 'size_t' to 'int_fast32_t', possible loss of data
  nmslib\similarity_search\src\method\small_world_rand.cc(652): warning C4267: '
=': conversion from 'size_t' to 'int_fast32_t', possible loss of data
  nmslib\similarity_search\src\method\small_world_rand.cc(663): warning C4018: '
<': signed/unsigned mismatch
  nmslib\similarity_search\src\method\small_world_rand.cc(130): warning C4267: '
argument': conversion from 'size_t' to 'similarity::IdType', possible loss of da
ta
  nmslib\similarity_search\src\method\small_world_rand.cc(124): note: while comp
iling class template member function 'void similarity::SmallWorldRand<float>::Co
mpactIdsIfNeeded(void)'
  nmslib\similarity_search\src\method\small_world_rand.cc(186): note: see refere
nce to function template instantiation 'void similarity::SmallWorldRand<float>::
CompactIdsIfNeeded(void)' being compiled
  nmslib\similarity_search\src\method\small_world_rand.cc(325): warning C4267: '
initializing': conversion from 'size_t' to 'similarity::IdType', possible loss o
f data
  nmslib\similarity_search\src\method\small_world_rand.cc(313): note: while comp
iling class template member function 'void similarity::SmallWorldRand<float>::Ch
eckIDs(void) const'
  nmslib\similarity_search\src\method\small_world_rand.cc(187): note: see refere
nce to function template instantiation 'void similarity::SmallWorldRand<float>::
CheckIDs(void) const' being compiled
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildT
ools\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\cl.exe' failed with exit
status 2

  ----------------------------------------
  Failed building wheel for nmslib
  Running setup.py clean for nmslib
Failed to build nmslib

**Comment by searchivarius** [comment]
Hi @munitech4u this would be very helpful, I am still looking into this.
