### ISSUE TITLE
[Python API] Opening a saved index doesn't behave correctly

### ISSUE THREAD

**Issue by yonromai** [nmslib/nmslib#255]
The behavior of a loaded index is different from a created one. `knnQuery` seems to work fine, but `len`, `[]` and `getDistance` are misbehaving:
```python
import nmslib
import numpy

data = numpy.random.randn(1000, 10).astype(numpy.float32)
indexA = nmslib.init(method='hnsw', space='cosinesimil')
indexA.addDataPointBatch(data)
indexA.createIndex({'post': 2}, print_progress=True)

print "Original index:"
print indexA.knnQuery(data[42], k=3)
print len(indexA)
print indexA[42]
print indexA.getDistance(0, 42)

indexA.saveIndex("foo.hnsw")

indexB = nmslib.init(method='hnsw', space='cosinesimil')
indexB.loadIndex("foo.hnsw")

print "\n\nDeserialized index:"
print indexB.knnQuery(data[42], k=3)
print len(indexB)
print indexB[42]
print indexB.getDistance(0, 42)
```
Outputs:
```
Original index:
(array([ 42, 802, 564], dtype=int32), array([ 0.        ,  0.09754962,  0.25818336], dtype=float32))
1000
[1.4986600875854492, 2.611328601837158, -1.1076785326004028, -0.6702077984809875, 0.035500362515449524, -0.20164893567562103, 0.09561093151569366, 0.802577555179596, 0.37556448578834534, 0.02108302153646946]
1.04743230343

Deserialized index:
(array([ 42, 802, 564], dtype=int32), array([ 0.        ,  0.09754962,  0.25818336], dtype=float32))
0
RuntimeError: Caught an unknown exception!
RuntimeError: Caught an unknown exception!
```

**Comment by searchivarius** [comment]
Hi @yonromai thank you for reporting this: this isn't really a bug, but rather a feature. Currently, our indices aren't real indices (except in one case), b/c they don't store data. Data needs to be reloaded. However, HNSW has an exception in that regard. It can save data as well. It would be sufficient to search, but this data isn't visible to the generic function getDistance. A good question is to how make this working in the best possible way. 

Regarding, the function len(): there is no reason why this function should work at all.

**Comment by yonromai** [comment]
Thanks for your answer @searchivarius!
Good to know - then I'm wondering if these methods should part of the visible Python API if they are not completely supported. 
> Currently, our indices aren't real indices (except in one case), b/c they don't store data. Data needs to be reloaded. However, HNSW has an exception in that regard. It can save data as well.

Would you mind developing a little bit more on that point?

**Comment by searchivarius** [comment]
@yonromai fair comment. Not sure about len: I need to doublecheck, but the distance can still be computed if the data is **reloaded**. Well, it's a current deficiency, but we will try to fix this in the future. When this all started, it wasn't completely clear how indices will be saved, so adding indices involved some ad hoc implementations. I will need to do a unification in the next version: I will simply make all good methods save the meta-index **and** data. So, we won't have situations like this.
