### ISSUE TITLE
loadIndex does not work for sparse vectors

### ISSUE THREAD

**Issue by icarocd** [nmslib/nmslib#300]
After a HNSW index for sparse vectors is saved, it can not be loaded. Function loadIndex always produces segmentation fault.
Below I provide an example.
I am using Ubuntu 16 LTS, python 3.5 and nmslib 1.7.2.

import numpy
import scipy.sparse as sparse
import nmslib

def init_index():
    return nmslib.init(method='hnsw', space='cosinesimil_sparse', data_type=nmslib.DataType.SPARSE_VECTOR)
    #return nmslib.init(method='hnsw', space='cosinesimil')

data = numpy.random.randn(100, 10).astype(numpy.float32)
data = sparse.csr_matrix(data)

indexA = init_index()
indexA.addDataPointBatch(data)
indexA.createIndex()
print("Original index")

indexA.saveIndex("foo.hnsw")

indexB = init_index()
indexB.loadIndex("foo.hnsw")
print("Deserialized index")

**Comment by searchivarius** [comment]
Hi @icarocd sorry this is a feature in a sense. Non-optimized indices are only meta-indices you have to recreate data points
```
indexB = init_index()
**indexB.addDataPointBatch(data)**
indexB.loadIndex("foo.hnsw")
print("Deserialized index")
```
I checked it works this way for me, but crashes with your script.
Please, refer to this notebook for further details: https://github.com/searchivarius/nmslib/blob/master/python_bindings/notebooks/search_sparse.ipynb

**Comment by icarocd** [comment]
I did not understand why it was closed. Don't you see it as a bug? loadIndex does not work. Recreating the index is not the intent. Is there any workaround for now? I have tried to use the pickle module to dump and load serialized index but it does not work either.

**Comment by searchivarius** [comment]
Hi @icarocd please add ``indexB.addDataPointBatch(data)`` before loading the index. It is not the full index, it's the meta-index that comes without data. You need to **re-load** the data before initialization. See, the attached script. It works without crashing.
[test.py.zip](https://github.com/searchivarius/nmslib/files/1844874/test.py.zip)

**Comment by icarocd** [comment]
It works this way, thanks. The current problem I see is that the index, to be fully reused from the file, needs to be created with the exact same configs and also the train data must be available.
Ideally, a unique call, such as nmslib.load('path'), would be preferable, but this requires the file to also store all metadata.

**Comment by searchivarius** [comment]
@icarocd I can agree more. Poor design choices made for the sake of expediency.

**Comment by searchivarius** [comment]
I believe this is now fixed with the flag `save_data=True` in `saveIndex` and `load_data=True` in `loadIndex`
