### ISSUE TITLE
Jaccard to method HSNW for sparse features

### ISSUE THREAD

**Issue by icarocd** [nmslib/nmslib#302]
Hi,

I want to know if HSNW provides Jaccard (similarity or distance, does not matter), besides cosine, for sparse features.
There are scenarios in which Jaccard outperforms.

Python notebooks provided show the following metrices: l2, l2sqr_sift, cosinesimil_sparse.

According to space_sparse_scalar.h, the following metrices seem to be implemented, or in preparation, to sparse features:
#define SPACE_SPARSE_COSINE_SIMILARITY          "cosinesimil_sparse"
#define SPACE_SPARSE_ANGULAR_DISTANCE           "angulardist_sparse"
#define SPACE_SPARSE_NEGATIVE_SCALAR            "negdotprod_sparse"
#define SPACE_SPARSE_QUERY_NORM_NEGATIVE_SCALAR "querynorm_negdotprod_sparse"

What does each of these metrices mean?
I also saw cosinesimil_sparse_fast in a few files. What is it, and how is it compared to cosinesimil_sparse? Is it ready for use?

I can provide a Jaccard implementation for sparse vectors, given 2 vectors implemented as hash tables, but I haven't found out how to integrate it to the code.
It would also be preferable to check which metrices are already available.
The closest clue I got was to expand the following files: distcomp_scalar.cc, hnsw.cc and hnsw_distfunc_opt.cc, but I am not sure which steps to make.
I saw some mentions to Jaccard in space_sparse_jaccard.cc and distcomp.h. But no examples are given.

Thanks in advance.

**Comment by searchivarius** [comment]
A more detailed description of spaces is in the manual (starting from p. 29) https://github.com/nmslib/nmslib/blob/master/manual/manual.pdf:

However, Jaccard isn't covered there. But it is supported: https://github.com/nmslib/nmslib/blob/master/similarity_search/include/space/space_sparse_jaccard.h

The difference between sparse fast and slow versions is that the fast version uses a very efficient (3x faster) SIMD-implementation. Hash tables is another thing to try to make things fast. 

PS: for such generic questions, please, use Gitter https://gitter.im/nmslib/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by icarocd** [comment]
jaccard_sparse did not work to me, v1.7.2. Segmentation fault between prints 1 and 2 in code below:

import numpy
import scipy.sparse as sparse
import nmslib

data = numpy.random.randn(100, 10).astype(numpy.float32)
data = sparse.csr_matrix(data)

indexA = nmslib.init(method='hnsw', space='jaccard_sparse', data_type=nmslib.DataType.SPARSE_VECTOR)
print(1)
indexA.addDataPointBatch(data)
print(2)
indexA.createIndex()
print(3)

**Comment by searchivarius** [comment]
aaargh, it won't work this way, sorry. It is a generic space where you can pass data points only in the string format. I will create a Python notebook. We have an example for string-based data representatoins buried in the python_bindings directory, but it's clearly quite difficult to find.

**Comment by searchivarius** [comment]
Hi, @icarocd sorry for the delay. It was a bit tricky to create a notebook for this case. But there we go:
https://github.com/nmslib/nmslib/blob/develop/python_bindings/notebooks/search_generic_sparse_jaccard.ipynb

**Comment by searchivarius** [comment]
@icarocd : please, note that this the so-called generic case, when we pass data points in the string format.

**Comment by icarocd** [comment]
Thanks for the notebook! I ran it but it is lauching segmentation fault in the call to index.knnQueryBatch(...), in section "Querying"

**Comment by searchivarius** [comment]
@icarocd thank you for testing! What is the directory where you run it?

**Comment by icarocd** [comment]
I run it in my 'home': /home/icaro
I am attaching my test code here.

2018-04-09 12:12 GMT-03:00 Leonid Boytsov <notifications@github.com>:

**Comment by searchivarius** [comment]
Attachment doesn't seem to work. Please, make sure that the data files: https://github.com/nmslib/nmslib/blob/master/sample_data/sparse_wiki_5K.txt are referenced properly in the notebook. I cannot check this now, but I suspect that if the notebook can't load the data, it just ignores it. Then, there is also a bug in some of the versions where querying an empty data set causes a segfautl.

**Comment by icarocd** [comment]
I am attaching here the code, which is the same from codebook, but launches segmentation fault.
[nmslib_jaccard_sparse.zip](https://github.com/nmslib/nmslib/files/1890555/nmslib_jaccard_sparse.zip)

**Comment by searchivarius** [comment]
Thanks! I will try to run. I also suspect we have a bug when the data set is too small :-)
Please, don't use max_qty when you read data and see what you get. It takes only a few seconds to create an index (and a few seconds to create gold standard) for this small data set.

**Comment by icarocd** [comment]
It also failures without max_qty

**Comment by searchivarius** [comment]
Ok, I will certainly have a look. Could you also provide more details:
OS?
Python version?
NMSLIB version?
How was NMSLIB installed?

**Comment by icarocd** [comment]
Ubuntu 16 LTS
Python 3.5.2
nmslib 1.7.2, installed through pip3

**Comment by icarocd** [comment]
Same problem occurs in:
Ubuntu 17.10, Python 3.6.3, nmslib 1.7.2 installed through pip3

**Comment by searchivarius** [comment]
Great to hear it worked. Regarding the matrices the classic Jaccard
operates only on IDs.

**Comment by icarocd** [comment]
Jaccard is defined for vectors also.
Please see here:
-> https://en.wikipedia.org/wiki/Jaccard_index, section "Generalized Jaccard similarity and distance"
-> https://mathoverflow.net/questions/123339/weighted-jaccard-similarity
-> https://datascience.stackexchange.com/questions/15862/how-to-compute-the-jaccard-similarity-in-this-example-jaccard-vs-cosine

**Comment by icarocd** [comment]
How it can be done? Could you provide the steps?

**Comment by searchivarius** [comment]
There is a bit low-level work to be done, because you need to create a space that has the function createObjFromVector:
https://github.com/nmslib/nmslib/blob/master/python_bindings/nmslib.cc#L205
Because you probably don't want to implement a SIMD-based version the Jaccard, you can probably just inherit from SpaceSparseVectorSimpleStorage. An example of doing so is SpaceSparseCosineSimilarity.

Also, one needs to update the space initialization code. A brief (possibly not totally up-to-date) description is given in the manual starting on p 65 (section 7.2): https://github.com/nmslib/nmslib/blob/master/manual/manual.pdf
