### ISSUE TITLE
how to integrate into search engine,  such as Elasticsearch?

### ISSUE THREAD

**Issue by shuitai** [nmslib/nmslib#304]
Hi~

I have a question, could you tell how to integrate into search engine,  such as Elasticsearch?
Expect your feedback!

**Comment by searchivarius** [comment]
I am sorry, I do not understand the question. Also, please, use Gitter: https://gitter.im/nmslib/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge  for general questions. Thank you !

**Comment by shuitai** [comment]
If we has a lot of vectors, about 100 millions，nsmlib seems to put all the index in memory. It should cost a lot of memory. So we want to put the index in search engine, such as solr or elasticsearch. Currently, we use PQ method to generate the code of vector, and put the code as index in search engine. So If using nsmlib, I do not know to do it. Expect your feedback!

**Comment by shuitai** [comment]
Ok, thank you for your feedback.
