### ISSUE TITLE
bit_hamming does not work

### ISSUE THREAD

**Issue by underfitting** [nmslib/nmslib#306]
I ran this code, 
`index = nmslib.init(method='hnsw', space='bit_hamming', dtype=nmslib.DistType.INT)`

but this yields error message:

`ValueError: The space type bit_hamming is not compatible with the type DENSE_VECTOR, only dense vector spaces are allowed!`

Is this bug or Is my code wrong?

**Comment by searchivarius** [comment]
bit_hamming data needs to be passed as a string, here is an example for Jaccard: you can use a similar one, but you need to update the data loading function and the function to compute the gold standard:

https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_generic_sparse_jaccard.ipynb

**Comment by underfitting** [comment]
It works. thank you!
