### ISSUE TITLE
Indexing takes too long for 1M 128D float32 arrays

### ISSUE THREAD

**Issue by Neltherion** [nmslib/nmslib#309]
First of all thanks for this awesome effort.

I'm trying to test NMSLib with large 128 dimensional numpy arrays but my code seems to take a long time to index (More than 50 seconds).

Are my parameters unoptimized? I want to aim for more than 10M datapoints but I fear the indexing time grows exponentially.

```
import time

import nmslib
import numpy as np

NUMBER_OF_SAMPLES = 1000000
NUMBER_OF_DIMENSIONS = 128

start_time = time.time()
array = np.random.random_sample((NUMBER_OF_SAMPLES, NUMBER_OF_DIMENSIONS)).astype(np.float32)
print("Finished generating the data => %s seconds" % np.mean(time.time() - start_time))

M = 10
efC = 20
efS = 10
num_nbrs = 5
num_threads = 4
post = 0  # Build the Tree twice but gain accuracy
index_time_params = {'M': M, 'indexThreadQty': num_threads, 'efConstruction': efC, 'post': post}
print('Index-time parameters', index_time_params)

start_time = time.time()
nmslib_index = nmslib.init(method='hnsw', space='cosinesimil')
nmslib_index.addDataPointBatch(array)
nmslib_index.createIndex(index_time_params, print_progress=True)
nmslib_index.setQueryTimeParams({'efSearch': efS})
print("\nTree Initialization Time => %s" % np.mean(time.time() - start_time))
array = None

times = []
for i in range(0, 100):
    start_time = time.time()
    ids, distances = nmslib_index.knnQuery(np.random.rand(1, NUMBER_OF_DIMENSIONS), k=num_nbrs)
    times.append(time.time() - start_time)
print("Average Search Time => %s" % np.mean(times))
```

**Comment by searchivarius** [comment]
All your parameter values are actually quite low. When you run indexing what's the CPU usage, do we use  four cores?

**Comment by Neltherion** [comment]
@searchivarius Yes, all of the CPUs (4 Cores, 8 Threads) are used during indexing...

I took a look at the manual but since it was a long read, I tried to use some of the parameters in example codes and they didn't work (Indexing took more than 50 seconds).

Is 50 seconds indexing time not normal for 1M 128D datapoints and the code/parameters are wrong? or NMSLib is optimized for datasize less than this amount?

The code is easily reproducible (Copy/Paste and Run!) and I'd be really grateful if someone could test it and help me on this issue.

Thanks again for this awesome gem!

**Comment by searchivarius** [comment]
@Neltherion actually if it's just 50 seconds, it's fine. However, if it's much longer than 50 seconds, it's a a concern.

**Comment by searchivarius** [comment]
@Neltherion I would actually advise increasing efConstruction to 50 or 100. It should still be about the same time, but the quality will be noticeably better.

**Comment by Neltherion** [comment]
@searchivarius Thanks so much...

By the way ,I'm going to test the library for 10M 512K datapoints, Do you think that the build time would grow linearly or exponentially to the point that using NMSLib for these kind of data would be infeasible?

I remember FLANN kd-tree indexing time to grow so much exponentially that I couldn't use it for more than 5M 128D data (Otherwise it would take forever to build the index).

**Comment by searchivarius** [comment]
@Neltherion we used it for 30M, @yurymalkov used a somewhat optimized version of NMSLIB to index 200M https://github.com/nmslib/hnsw
Indexing time grows a bit superlinearly, but with say 36 cores, it is possible I think to index 1B in a reasonable time. It would be more of an issue to fit everything into RAM.

**Comment by searchivarius** [comment]
PS: is 512K the number of dimensions? Is 50 seconds for 512K-dimensional vectors?

**Comment by Neltherion** [comment]
@searchivarius Thanks again for the help. I really hope the build time would stay near-linear so that our time/speed assumptions would work for larger scale data.

I will let you know of the build times at a later date (as soon as I have the resources to test the library for large scale datasets).

Thanks again!

**Comment by xuxiaohui4** [comment]
what about the build time you get last?
