### ISSUE TITLE
How to add one data point into index after createIndex?

### ISSUE THREAD

**Issue by universewill** [nmslib/nmslib#311]
i am using nmslib for vector searching. I find that the addDataPoint function will not working if the index is already created. I have to add a createIndex function after addDataPoint to enable the single data point, which will be time consuming because my data points number is large.
How to solve this problem?

My code is something like this:

```
import nmslib
import numpy as np

a = np.array([[1.0,0,0], [0,1.0,0], [0.1, 0, 1.0]])
b = np.array([0,0, 1.0])
c = np.array([0,0, 0.9])

nmsl = nmslib.init(method='hnsw', space='l2')
nmsl.addDataPointBatch(a)
nmsl.createIndex({'post': 2}, print_progress=True)
nmsl.addDataPoint(3, b)
id, dist = nmsl.knnQuery(c, 2)
print id, dist

```

**Comment by searchivarius** [comment]
Hi @universewill this is not supported yet.

**Comment by universewill** [comment]
Is it very difficult to support this feature with nmslib? Cause I think it is a really good feature if nmslib is used in product scene. @searchivarius

**Comment by yurymalkov** [comment]
@universewill Probably hnswlib (https://github.com/nmslib/hnsw/) is a good match for your tasks. It supports incremental indexing.

**Comment by universewill** [comment]
@yurymalkov Yeah! that's cool. Thanks.
