### ISSUE TITLE
Documentation for parameters

### ISSUE THREAD

**Issue by lesterlitch** [nmslib/nmslib#313]
Correct me if I'm wrong, but there appears to be no real documentation for the parameters:

- efConstruction
- M
- efSearch
- post

For example, what they do, sensible default ranges, considerations for scaling with the size of the samples or features to be indexed etc.

Should this be included in the docs somewhere?

**Comment by lesterlitch** [comment]
Ok apologies I found the manual - is it possible to include a link to this on the landing page of the python bindings?

**Comment by searchivarius** [comment]
@lesterlitch no worries, I really need to create a wiki page for the most important parameters.

**Comment by searchivarius** [comment]
Hi @lesterlitch I have added more detailed guidelines (manual is actually quite outdated) here: https://github.com/nmslib/nmslib/blob/master/python_bindings/parameters.md

@yurymalkov please, double check. comments are welcome.

**Comment by lesterlitch** [comment]
Thank you - that was unreasonably fast of you.
