### ISSUE TITLE
Error on example from manual

### ISSUE THREAD

**Issue by bkj** [nmslib/nmslib#315]
In the manual, it suggests running:
```
release/experiment \
  --distType float --spaceType l2 --testSetQty 5 --maxNumQuery 100 \
  --knn 1  \
  --dataFile ../sample_data/final8_10K.txt --outFilePrefix result \
  --cachePrefixGS sw-graph \
  --method sw-graph \
    --createIndex NN=3,initIndexAttempts=5,indexThreadQty=4 \
    --queryTimeParams initSearchAttempts=1,efSearch=10 \
    --saveIndex sw-graph_index
```
but this throws the error
```
...
2018-05-09 18:01:25 params.h:247 (CheckUnused) [ERROR] Unknown parameter: 'initIndexAttempts'
...
```
If I remove that argument, it complains about `initSearchAttempts`.  If I remove both, then it runs -- but is it safe to do so?

Thanks

**Comment by searchivarius** [comment]
Hi @bkj sorry these parameter were sunset (``initSearchAttempts`` and ``initIndexAttempts``), but the manual wasn't updated yet. I am moving some descriptions online, in particular here:
https://github.com/nmslib/nmslib/blob/master/python_bindings/parameters.md

**Comment by bkj** [comment]
fantastic -- thanks!
