### ISSUE TITLE
example of using Hnsw in C++

### ISSUE THREAD

**Issue by Damcy** [nmslib/nmslib#316]
Could you give some examples for using Hnsw in C++, I couldn't find the example in this project.

**Comment by searchivarius** [comment]
Hi @Damcy I will add HNSW to this example: https://github.com/nmslib/nmslib/blob/master/sample_standalone_app/sample_standalone_app1.cc
However, you can just substitute, e.g., small_world_rand with hnsw as well as to **modify some query-time and index-time parameters".

**Comment by Damcy** [comment]
@searchivarius Thank you very much! I will try it in these two days.
