### ISSUE TITLE
switch from nmslib to hnswlib api

### ISSUE THREAD

**Issue by universewill** [nmslib/nmslib#320]
Accoording to #311 , i want to switch nmslib api to hnswlib api.
My nmslib api code is as below:
```
        nmsl = nmslib.init(method='hnsw', space='l2')
        nmsl.addDataPointBatch(points)
        nmsl.createIndex({'post': 2}, print_progress=True)
```

Now i want to use hnswlib api. But i don't know how to set the parameters to achieve the same result as the nmslib.
I find the parameters of hnswlib are complated for me to understand, such as M, or ef_construction.
I only want to get the same result as the code above.

How should i set the hnswlib paras?

**Comment by universewill** [comment]
@yurymalkov @searchivarius 
Could you guys give any help here? Thanks a lot!

**Comment by yurymalkov** [comment]
Hi @universewill ,
The default parameters in nmslib are ef_construction=200 and M=16. You can use them in hnswlib, the results will be pretty close.
The description of the HNSW parameters can be found here https://github.com/nmslib/nmslib/blob/master/python_bindings/parameters.md , although hnswlib does not have a 'post' parameter.

**Comment by universewill** [comment]
OK , thanks for your info. @yurymalkov
Besides, what does the post parameter mean?

**Comment by yurymalkov** [comment]
'post' parameter is used for an additional data pass through the index after it is constructed. 
It leads to better search speed/accuracy, but at expense of construction time, construction memory; it also does not play well with incremental construction.

**Comment by yurymalkov** [comment]
'post' parameter is not a part of the original paper on hnsw. It is an nmslib-only feature.
Yes, having no post parameter decreases the accuracy a bit at high recalls (up to 10-15% speed), but it allows index updates, much less build memory and much faster indexing time. Because of the latter two reasons it is off by default in nmslib.

hnswlib is likely to have an updates friendly substitute for post parameter in the future.

By default ef is 20 in nmslib. I would recommend always tuning ef for an accuracy/speed tradeoff that is optimal for your application.

**Comment by universewill** [comment]
ok, i understand. Looking forward for your feature updates.
Thanks again!
@yurymalkov

**Comment by universewill** [comment]
I set ef =20, M=16, ef_construction=200 with hnsw api. However, the retrieval  is about 10~20 times slower than nmslib with post parameter setting to 2 .
Could you give any help here? @yurymalkov

**Comment by yurymalkov** [comment]
@universewill Thanks! I'll check it soon.

**Comment by yurymalkov** [comment]
@universewill I think I know what is the reason.
Nmslib and hnswlib behave a bit differently when k is very large. 
When ef<k, hnswlib overrides the main search paramter ef to k, leading to (almost) guaranteed return of total k closest neighbors and more accurate but slower search. 
Nmslib uses a different approach - it returns only the neighbors that the algorithm could find for the supplied ef value (the number of returned neighbors potentially may be much lower than k).

This seems to be your situation, look at the modified demo code:
```
from __future__ import print_function
import numpy as np
import hnswlib
import nmslib
import time


data = np.random.randn(100000, 2048).astype(np.float32)

#
print('hnswlib')
p = hnswlib.Index(space = 'l2', dim = data.shape[1])
p.init_index(max_elements=data.shape[0], ef_construction=200, M=16)
p.set_ef(20)
p.add_items(data)

tic = time.time()
labels, dists = p.knn_query(data[1, :], k=1500)
toc = time.time()
print ('h search top 1500 time used:', toc -tic)
print('total neighbors found:',len(labels[0]))

tic = time.time()
labels, dists = p.knn_query(data[10, :], k=2000)
toc = time.time()
print ('h search top 2000 time used:', toc -tic)
print('total neighbors found:',len(labels[0]))

tic = time.time()
labels, dists = p.knn_query(data[100, :], k=6000)
toc = time.time()
print ('h search top 6000 time used:', toc -tic)
print('total neighbors found:',len(labels[0]))

labels, dists = p.knn_query(data[1000, :], k=8000)
toc = time.time()
print ('h search top 8000 time used:', toc -tic)
print('total neighbors found:',len(labels[0]))

print('nmslib')
n = nmslib.init(method='hnsw', space='l2')
n.addDataPointBatch(data)
n.createIndex({'post': 0}, print_progress=True)

tic = time.time()
labels, dists = n.knnQuery(data[1, :], k=1500)
toc = time.time()
print ('n search top 1500 time used:', toc -tic)
print('total neighbors found:',len(labels))

tic = time.time()
labels, dists = n.knnQuery(data[10, :], k=2000)
toc = time.time()
print ('n search top 2000 time used:', toc -tic)
print('total neighbors found:',len(labels))

tic = time.time()
labels, dists = n.knnQuery(data[100, :], k=6000)
toc = time.time()
print ('n search top 6000 time used:', toc -tic)
print('total neighbors found:',len(labels))

labels, dists = n.knnQuery(data[1000, :], k=8000)
toc = time.time()
print ('n search top 8000 time used:', toc -tic)
print('total neighbors found:',len(labels))
```
output:
```
hnswlib
h search top 1500 time used: 0.016036272048950195
total neighbors found: 1500
h search top 2000 time used: 0.01944136619567871
total neighbors found: 2000
h search top 6000 time used: 0.04127645492553711
total neighbors found: 6000
h search top 8000 time used: 0.09058547019958496
total neighbors found: 8000
nmslib
n search top 1500 time used: 0.0008158683776855469
total neighbors found: 601
n search top 2000 time used: 0.0006973743438720703
total neighbors found: 552
n search top 6000 time used: 0.0007381439208984375
total neighbors found: 593
n search top 8000 time used: 0.001882791519165039
total neighbors found: 686
```
I think that hnswlib is a bit more user friendly in this regard, as it does not allow to set "strange" combinations of parameters.

**Comment by universewill** [comment]
yeah, that's cool! Thanks for your reply! @yurymalkov
