### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by universewill** [nmslib/nmslib#323]
I user hwns api to create index and retievel, but encountered 'core dumped' error when building index.
My computer memory is 300G, so i don't think it is caused by memory limit.

My code (notice the point dimension is 2048, and i have 100000 number of points):
```
        nmsl = hnswlib.Index(space='l2', dim=2048)
        nmsl.init_index(max_elements=650000, ef_construction=200)

        nmsl.set_ef(20)
        nmsl.add_items(points)
```

**Comment by searchivarius** [comment]
wrong repository

**Comment by universewill** [comment]
yeah, the error occurs when running the example code of hnswlib. It seems it is correlated with the system eviroment, but i can not figure it out. Same code can runs well on another machine.
The error occurs when running this code line:
```
...
p.init_index(max_elements = num_elements, ef_construction = 200, M = 16)
```

Any hint or suggestions here?

@yurymalkov

**Comment by universewill** [comment]
I reinstall an ubuntu system and hnswlib, and when import hnswlib, it runs into core dump ...
