### ISSUE TITLE
LoadIndex

### ISSUE THREAD

**Issue by blackberrybhtg** [nmslib/nmslib#324]
The indexed loaded with LoadIndex doesn't function as expected.

The example below is based on commit 829e830c33d1b40f6e59e0ad0e2f5e80bb62483e.

int main(void) {

    initLibrary();

    Space<float> *space = SpaceFactoryRegistry<float>::Instance().CreateSpace("l2", AnyParams());

    ObjectVector dataset;
    float base[2][2] = {
        {1.0f, 1.0f},
        {2.0f, 2.0f}
    };
    for (int i = 0; i < 2; ++i) {
      dataset.push_back(new Object(i, -1, sizeof(base[0]), base[i]));
    }

    Index<float>* index = MethodFactoryRegistry<float>::Instance().CreateMethod(false, "hnsw", "l2", *space, dataset);

    index->CreateIndex(AnyParams());
    cout << "Indexed dataset size: " << index->GetSize() << endl;;

    // Test Case 1. Query against new index.
    int k = 2;
    float queryVector[2] = {4.0f, 2.0f};
    KNNQuery<float> query (*space, new Object(-1, -1, sizeof(queryVector), queryVector), k);
    index->Search(&query);
    const KNNQueue<float> *result = query.Result();
    query.Print();

    // Test Case 2. Save index and query.
    string indexPath = "hnsw.index";
    index->SaveIndex(indexPath);
    KNNQuery<float> query2 (*space, new Object(-1, -1, sizeof(queryVector), queryVector), k);
    index->Search(&query2);
    query2.Print();

    // Test Case 3. Load index and query.
    ObjectVector ds;
    KNNQuery<float> query3 (*space, new Object(-1, -1, sizeof(queryVector), queryVector), k);
    Index<float>* index2 = MethodFactoryRegistry<float>::Instance().CreateMethod(false, "hnsw", "l2", *space, ds);
    index2->LoadIndex(indexPath);
    cout << "Reloaded dataset size: " << index2->GetSize() << endl;;
    index2->Search(&query3);
    query3.Print();
}

Results:
Indexed dataset size: 2
queryID = -1 size = 2 (k=2 dc=0) 0(3.16228 3.16228) 1(2 2) 
queryID = -1 size = 2 (k=2 dc=0) 0(3.16228 3.16228) 1(2 2) 
Reloaded dataset size: 0
queryID = -1 size = 0 (k=2 dc=0)

Expected results for the last two lines:
Reloaded dataset size: 2
queryID = -1 size = 2 (k=2 dc=0) 0(3.16228 3.16228) 1(2 2) 

I notice that when I use the original ObjectVector (dataset instead of empty ds), the index works as expected. But as per https://github.com/nmslib/nmslib/issues/301 , it appears the original dataset isn't necessary for reloading index. So I am not clear if the original dataset is needed or not.

**Comment by searchivarius** [comment]
ps: Ohh, sorry you do re-create the index. So, here is a potential issue. Most indexes in NMSLIB are just metaindexes. You do need to reload the same data set as well as the index. However, this is not the case for L2/cosine and HNSW.

**Comment by blackberrybhtg** [comment]
Thank you very much for the quick replies!

**Comment by rshest** [comment]
@searchivarius It appears that this behaviour changed in `1.7.3.1` for an optimized L2/HNSW indexes as well (i.e. one does need to explicitly add the data for them as well now).

The [corresponding notebook](https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_optim.ipynb) prints `kNN recall 0.000000` in the very end if running with `nmslib==1.7.3.1` (as a result of `knnQueryBatch` basically returning empty results), whereas with `nmslib==1.7.2` it prints `kNN recall 0.992860`, as expected.

**Comment by searchivarius** [comment]
@rshest thanks a lot for noticing this. Indeed, this bug was introduced while fixing another issue (and there is no test for this). In the future, actually, we will have only "optimized" indices that will always save the data. The current setup is an unfortunate artifact as to how the library has been evolving. It's time to re-write most of it :-)

**Comment by searchivarius** [comment]
@rshest please try 1.7.3.2

**Comment by rshest** [comment]
@searchivarius Thank you! :)

**Comment by searchivarius** [comment]
I hope this would be partially solved now with the introduction of `save_data` in `saveIndex` and `load_data` in `loadIndex`
