### ISSUE TITLE
default -march=native build cannot be overridden by flags

### ISSUE THREAD

**Issue by zseder** [nmslib/nmslib#325]
I would like to use nmslib in python and when installing nmslib by `pip install nmslib`, `-march=native` is passed to gcc https://github.com/nmslib/nmslib/blob/829e830c33d1b40f6e59e0ad0e2f5e80bb62483e/python_bindings/setup.py#L82 and so binaries are created that work only on the same architecture. I would like to use nmslib inside docker and these docker containers would run on different types of machines (different generations of aws ec2 instances), but this building setting will cause `Illegal instruction` in some cases.

It would be great if C++ build flags could be overridden somehow. I tried with `CFLAGS="-march=sse4.2"`, but these options get _before_ `-march=native"`, so the latter overrides the former.

I created my own fork of nmslib, modified `setup.py` and this solved the problem, but this clearly isn't the best solution, and maybe others have the same problem when using nmslib with docker and ec2, so I hoped someone here can suggest a better solution.

Thanks

**Comment by zseder** [comment]
I can open a PR for this, but I can't really design a general solution, i would just append an extra option to the `extra_compile_args` list between these two lines:
https://github.com/nmslib/nmslib/blob/829e830c33d1b40f6e59e0ad0e2f5e80bb62483e/python_bindings/setup.py#L112-L113
If you don't mind this being too specific, I'll create the PR.

**Comment by searchivarius** [comment]
@zseder what do you mean by a general solution?

**Comment by zseder** [comment]
I really don't know :)
I just feel like this solution, a gcc call wil look like this:
`gcc ... -march=native ... -march={user_defined}`
and this looks very confusing because one has to know that the latter always overrides the former

**Comment by searchivarius** [comment]
@zseder I think this makes a lot of sense if you can just specify a "downgraded" version for CXX flags. This is also a good reminder to still support older architectures: although I am a bit surprised, we don't have AVX on most AWS instances yet.

**Comment by searchivarius** [comment]
PS: I can't think of a more general solution and your approach sounds just fine.

**Comment by zseder** [comment]
I tried to make this work, but this setuptools is way too complicated.
The solution you suggested adds a new argument to install but `setup.py` is implementing `build_ext`, not `install`, so I couldn't make it work, arguments passed to install (`pip install ... --extra-arg`) could not be obtained in `build_ext`.
After this, I tried https://stackoverflow.com/questions/15725869/pass-build-ext-options-to-pip-install
But with this solution, build_ext arguments got overridden, and all the other dependencies got the argument (like numpy), and they complained they don't understand this extra arg for build_ext.

I'm afraid I'll have to give up here, i have no idea about the whole setuptools and I just don't know what I am doing...

**Comment by searchivarius** [comment]
@zseder aaargh, ok. In fact, there seems to be a bug in setuptools.py that we don't have a workaround for yet. setuptools is difficult.

**Comment by searchivarius** [comment]
@DemonTPx no, it's not too risky. It's just some work needs to be done by processing extra flags.

For a quick fix: what prevents you from manually changing -march=native in the setup.py script? It's only an issue if you install it through pypi. Will it be too much additional work while creating a docker container?

**Comment by searchivarius** [comment]
Another option would be to try this approach: https://stackoverflow.com/questions/677577/distutils-how-to-pass-a-user-defined-parameter-to-setup-py
Yet, I didn't try it yet.

**Comment by searchivarius** [comment]
@zseder This is definitely fixed now. If you export CFLAGS for the Linux build and set e.g., -march=<something> or -msse.... it will go with a specified option. For a Windows build you need to specify the ARCH variable. Please, see the code here for a reference: https://github.com/nmslib/nmslib/blob/master/python_bindings/setup.py#L116
