### ISSUE TITLE
Results returned are different even if I only use one thread

### ISSUE THREAD

**Issue by bli25broad** [nmslib/nmslib#326]
Hi,

I found that if I use the hnsw method in nmslib, I'll get slightly different results each run, even if I only use one single thread. But this behavior is not appeared if I use hnswlib. 

Any comments?

Thanks,
Bo

**Comment by searchivarius** [comment]
What is eactly a run?

**Comment by bli25broad** [comment]
@searchivarius , thanks for your quick reply. Please see the codes below.

knn_index = nmslib.init(method = 'hnsw', space = 'l2', data_type = nmslib.DataType.DENSE_VECTOR)
knn_index.addDataPointBatch(adata.obsm['X_pca'])
knn_index.createIndex({'M': 15, 'indexThreadQty': 1, 'efConstruction': 100}) 
knn_index.setQueryTimeParams({'efSearch': 100})
results = knn_index.knnQueryBatch(adata.obsm['X_pca'], k = 100, num_threads = 1)

I have run the same codes twice and get different results.

**Comment by searchivarius** [comment]
@bli25broad possibly, this is some older version which didn't consistently initialized the random number generator.

**Comment by bli25broad** [comment]
@searchivarius , NMSLIB version is 1.7.2 . Isn't it up-to-date?

**Comment by searchivarius** [comment]
@bli25broad could you 
1) double-check that it's 1.7.2, print nmslib.__version__
2) what happens when you run knnQueryBatch several times? (but indexing once) do you get different results?
thanks!

**Comment by bli25broad** [comment]
@searchivarius 

re:1. I think it is 1.7.2. See below.

>>> print(nmslib.__version__)
1.7.2

re:2. If I index once, I will not get different results.

Thanks,
Bo

**Comment by searchivarius** [comment]
@bli25broad thanks, so it's indexing being non-deterministic. Ok, the next question: is there a chance that you call init() twice in the same Python script?

**Comment by bli25broad** [comment]
@searchivarius , I guess not?  

What I did is paste the codes twice in iPython. This should create two different index objects, won't it?

Best,
Bo

**Comment by searchivarius** [comment]
@bli25broad the library initializes the random number generator only once. It is currently not being re-initialized by the initIndex function.
