### ISSUE TITLE
Duplicate points

### ISSUE THREAD

**Issue by hjain689** [nmslib/nmslib#328]
My data has some duplicate points(which I don't want to remove as it would mess up my further processing). However, the code runs forever while creating the index with such a dataset. If I remove the duplicates is runs fine. Any suggestions as to how I can solve this without removing duplicates?

**Comment by searchivarius** [comment]
@hjain689 which method (parameters also) do you use and how approximately does your data look like?

**Comment by hjain689** [comment]
I am using hnsw with cosine similarity, M=100, efC=300, efS=300. Dataset in 300 dimensional having 501,070 points out of which around 20,000 are duplicates

**Comment by searchivarius** [comment]
@hjain689 any chance you have all-zero vectors?

**Comment by hjain689** [comment]
@searchivarius I checked there are no all-zero vectors

**Comment by hjain689** [comment]
@searchivarius I'm sorry, I just realized that the data has some NaN values which were getting removed when I filtered out unique vectors. 
Sorry for bothering you.
