### ISSUE TITLE
Questions for efsearch param, Thrift server

### ISSUE THREAD

**Issue by blackberrybhtg** [nmslib/nmslib#329]
Hi,

I have a question about how/if a client of a Thrift query server using HNSW can set the efsearch query parameter per KNN query. Are clients expected to set it at index using [SetQueryTimeParams](https://github.com/nmslib/nmslib/blob/d3cc0899604698f1e78867cf5396031268db55f1/similarity_search/include/method/multi_index.h#L58) before sending each query? I am worried that will cause various concurrency issues, from read/write error to race condition.

Thank you!

**Comment by searchivarius** [comment]
Hi @blackberrybhtg you need to call SetQueryTimeParams every time you change parameters. Ideally, you do it only once. Please, note that this call isn't thread safe.

**Comment by blackberrybhtg** [comment]
I see. Thanks for the heads-up!

**Comment by searchivarius** [comment]
@blackberrybhtg no problem, glad, this was helpful.
