### ISSUE TITLE
Is the index thread safe?

### ISSUE THREAD

**Issue by Dr-Champ** [nmslib/nmslib#330]
Hi,

First of all, thanks for the nice work you guys've put into making this NMS lib. It's really useful and saves a lot of time implementing a custom ANN search index of my own. 

However, I haven't seen this mentioned explicitly anywhere in the documentation. So, could anyone confirm if the index object, once created (from nmslib.init(...)), is safe to be shared and queried across multiple threads? 

Thanks !

**Comment by searchivarius** [comment]
@Dr-Champ yes, but note that in some cases it's a *META* index, i..e., you have to re-load data. It's a deficiency that I am gonna fix someday, but not very soon. When you are not sure whether data needs to be reloaded, please, consult the following examples:
https://github.com/nmslib/nmslib/tree/master/python_bindings/notebooks

**Comment by Dr-Champ** [comment]
Thanks !
