### ISSUE TITLE
query vector from hnsw index not found in top K 

### ISSUE THREAD

**Issue by chapleau** [nmslib/nmslib#331]
This is more a question than a bug report.

Building a rather large index with hnsw method, > 1M unit vectors (100d) with l2 space, M=40, efConstruction=1000, efSearch in 100-1000 range, default params otherwise (using v1.7.2)
For every vector in index, querying for top 1000 nearest neighbors. This works like a charm and the results are very accurate (and fast!) and because the vectors being queried are also used to create the index, the closest vector is always itself. However, there are very few cases ( < 100 ) where this isn't the case, i.e. the query vector is not in the top 1000 and the results are more or less relevant. 

My question would be, is this simply a consequence of the approximate nature of the method ? Something that has to do with how the heuristics work when building the index and all ?

Thanks in advance !

**Comment by searchivarius** [comment]
@chapleau I think it is a consequence of the approximate nature of the method, but it is hard to know for sure. I am a bit surprised that people are searching for vectors already indexed: is it a common use scenario?

**Comment by chapleau** [comment]
thanks for the prompt reply ! 
Re your question, in the case of pairwise distances among the input vectors themselves (finding similar items) it's much more efficient than a brute force approach.

**Comment by chapleau** [comment]
I create an index with my data, and then I find the K nearest neighbors for all my data points. So I query for all x already in the index. It think that's a pretty common scenario, unless I'm missing something here.

**Comment by searchivarius** [comment]
@chapleau if every query is indexed in the data, isn't it trivial to add to the result set? :-)

**Comment by chapleau** [comment]
oh, absolutely ! I was just being curious :) 
I think I finally understand what you were saying, you're right that if I already have x indexed and query kNN with it, I don't need it in the result set since I know by definition that it should be there (with a valid dst metric). 
Thanks for the conversation and the prompt replies. 
I'll close this since this isn't a bug.

**Comment by searchivarius** [comment]
no worries, thanks!
