### ISSUE TITLE
Intolerance to empty vectors in l1/l2 sparse and cosine similarity spaces

### ISSUE THREAD

**Issue by lsorber** [nmslib/nmslib#333]
`index.createIndex()` fails with the following message for `l1_sparse` and other `l[x]_sparse` spaces:
```
RuntimeError: Check failed: it's either a bug or inconsistent data!
```

Minimal example:
```python
import nmslib
import numpy as np
import scipy


def test_l1_sparse():
    index = nmslib.init(
        method='hnsw',
        space='l1_sparse',  # Also fails for e.g., l2_sparse
        space_params=None,
        data_type=nmslib.DataType.SPARSE_VECTOR,
        dtype=nmslib.DistType.FLOAT)
    X = scipy.sparse.random(
        10_000,
        100,
        density=0.1,
        format='csr',
        dtype=np.float32,
        random_state=42)
    index.addDataPointBatch(X)
    index.createIndex()
```

**Comment by searchivarius** [comment]
@lsorber How the heck this even works in Python? 10_000 is not a proper number. You probably want something like:
```
scipy.sparse.random(
        100,
        10000,
```

**Comment by lsorber** [comment]
`10_000` and `10000` are equivalent since Python 3.6, it's a language feature [1].

[1] https://www.python.org/dev/peps/pep-0515/

**Comment by searchivarius** [comment]
@lsorber o dear, anyways, the reason why this error happens, because NMSLIB l2_sparse and l1_sparse space doesn't like empty vectors, but it, unfortunately, fails to produce a cohere error. Try this script to see:
```
import numpy as np
import scipy, scipy.sparse


def test_l1_sparse():
    index = nmslib.init(
        method='hnsw',
        space='l1_sparse',  # Also fails for e.g., l2_sparse
        space_params=None,
        data_type=nmslib.DataType.SPARSE_VECTOR,
        dtype=nmslib.DistType.FLOAT)
    X = scipy.sparse.random(
        10_000,
        100,
        density=0.1,
        format='csr',
        dtype=np.float32,
        random_state=42)
    minQty = 1e10
    for x in X:
      minQty = min(minQty, x.count_nonzero())
    print('minQty: %d' % minQty)
    index.addDataPointBatch(X)
    index.createIndex()

test_l1_sparse()

```

**Comment by lsorber** [comment]
I see, that does explain what's causing the error. However, the `l1_sparse` space should still work for all-zero rows in `X`, right?

**Comment by searchivarius** [comment]
@lsorber fair comment, this should be fixed someday. Do you actually have a usecase of the all-zero vector or is more of a hypothetical thing for now?

**Comment by lsorber** [comment]
In this case it's more of a hypothetical use case. We found this bug by fuzzing the input parameters. Still, seems like something that should be fixed.

The related issue #321 is an actual problem for our use case: if the training set contains all zero vectors then NMSLib does not complain with the cosine similarity space, but it returns incorrect results! There is no workaround for that issue beyond not allowing all zero query or training vectors at the user level (which is not a solution in our case).

**Comment by searchivarius** [comment]
This bug should be fixed by now (and there's a test to prevent a future regression). Feel free to bug me if it's still a problem.
