### ISSUE TITLE
HNSW Parameter Ranges

### ISSUE THREAD

**Issue by lkoll** [nmslib/nmslib#334]
Question on parameter ranges that I know you have hinted at in other issues, but as far as I can tell haven't directly addressed. I am also referencing the following link: 

https://github.com/nmslib/nmslib/blob/master/python_bindings/parameters.md

Elsewhere you mentioned it is possible to go above the values listed at the link for m,efc,efs. Is there a limit to how far above these values you can go? Is this dictated by your data set size? I am working on a 500k x 20k sparse matrix and would like to improve my results in terms of getting closer to the true nearest neighbors. I had previously run the query with the following parameters:
m=100
efc=2000
efs=2000

I also recently read in the documentation about the post=2 parameter, which I will add on my next run. I'm just trying to make sure I understand all my options for improvement.

**Comment by searchivarius** [comment]
@lkoll yes, it is possible to go about this values, but the search will be kinda slow. I would also recommend trying increase the value M first, what's the largest M that you tried? Setting M to 50-70 isn't unreasonable.

BTW, for sparse matrices, we have an alternative that can be roughly as efficient as HNSW, while taking much shorter time to index.

**Comment by searchivarius** [comment]
@lkoll I cannot exactly recommend, you can try higher M certainly. The question is whether indexing time would be acceptable. Do your vectors have a lot of non-zeros?

**Comment by lkoll** [comment]
Well, I may be misunderstanding something but the way I think about sparse matrices is if it's 95% sparse, then doesn't that mean 5% of them are non zero? Please forgive me if I'm mis stating something, I am fairly new to this area.

**Comment by searchivarius** [comment]
@lkoll actually this 5% density is a relevant number too, but what is the total dimensionality? Also, if you could provide a small sample (say 1M entries) I can very quickly tell you if NAPP works or not.

**Comment by lkoll** [comment]
So by total dimensionality do you mean the dimensions of my matrix? There are approximately 100 million values distributed across a 480k by 18k matrix. I can try to provide a sample of data later. Are you wanting just a .txt file? If it is sufficient the data I'm working with is described here:
https://en.wikipedia.org/wiki/Netflix_Prize#Problem_and_data_sets

**Comment by searchivarius** [comment]
@lkoll so it's about 900 non-zeros per row. txt will be fine.

**Comment by lkoll** [comment]
So I've attached 1000 samples from the dataset... I kept getting errors that the file was too big. The data is not in matrix format yet. UserId would be my Y axis and Movie ID would be my x axis of my matrix, with the rating being the value. Let me know if this will work for you. Thank you.
[random_1000.txt](https://github.com/nmslib/nmslib/files/2207425/random_1000.txt)

**Comment by searchivarius** [comment]
@lkoll could you upload somewhere (say dropbox or google docs) the actual matrix file in the format that NMSLIB understands. If you zip/gzip/bzip2 it will be quite small. You can share the link privately with leo at boytsov.info
