### ISSUE TITLE
"Check failed" in `createIndex` for sparse data containing zero rows

### ISSUE THREAD

**Issue by rshest** [nmslib/nmslib#336]
When creating an index for sparse data from the Python wrapper (calling `createIndex` with `scipy.sparse.csr_matrix`), it fails if there are zero vectors (i.e. all-zero rows) in the input data.

Here's a minimal repro-case:
```python
import numpy as np
from scipy.sparse import csr_matrix 
import nmslib 

data = csr_matrix((3, 3), dtype=np.float64)
data[0, 0] = 1
data[1, 0] = 2

# uncomment the following line to get rid of an empty row (and a crash)
#data[2, 0] = 3 

index = nmslib.init(method='hnsw', space='cosinesimil_sparse', data_type=nmslib.DataType.SPARSE_VECTOR) 
index.addDataPointBatch(data)

index.createIndex({'M': 30, 'indexThreadQty': 4, 'efConstruction': 100, 'post' : 0}) 
```

This results in:
```
Check failed: obj1->datalength() > 0
...
RuntimeError: Check failed: it's either a bug or inconsistent data!
```

Uncommenting the line `data[2, 0] = 3` in the above snippet makes it work.

Possibly some internal data structures do not get initialized when loading the data from Python (in case there are empty rows in `csr_matrix`)?

**Comment by searchivarius** [comment]
Sorry, it's an "intolerance" to empty vectors. This duplicates the issue #333

**Comment by rshest** [comment]
Sorry, I did not realize it's the same as #333.

Just a note, a "workaround" for this would be just to initialize a single element of all the empty rows with an explicit zero.

E.g., if in the snippet above we instead do:
```python
data[2, 0] = 0 # note the zero here
```

and then run a query:
```python
index.knnQueryBatch(data[1, :], k=3)
```

the result is
```
[(array([1, 0, 2], dtype=int32), array([0., 0., 1.], dtype=float32))]
```
with zero vector returned as the furthest, which kind of makes sense.

**Comment by searchivarius** [comment]
@rshest thank you, yes, this will work, but I want to eventually fix this, in particular, b/c there's a need to fix the distance between all-zero vectors.
