### ISSUE TITLE
Same Result

### ISSUE THREAD

**Issue by pawmis** [nmslib/nmslib#338]
Getting the same result for all the queries. 

query_qty = 1
start = time.time()
labels = newIndex.knnQueryBatch([query_index], k = K, num_threads = num_threads)
end = time.time()
print('kNN time total=%f (sec), per query=%f (sec), per query adjusted for thread number=%f (sec)' %
      (end-start, float(end-start)/query_qty, num_threads*float(end-start)/query_qty))

labels remain same for different query_index

**Comment by searchivarius** [comment]
Hi @pawmis could you create a minimally reproducible example?

**Comment by pawmis** [comment]
Hello @searchivarius sorry to bother you. But this error was due to some other problem on google cloud. It is not related to nmslib. It is because I was searching with the same query stored in cache again and again.
