### ISSUE TITLE
How do you use leven?

### ISSUE THREAD

**Issue by lesshaste** [nmslib/nmslib#339]
I am trying to use the space 'leven'. Here is a toy example of a failed attempt.

```
import nmslib
import numpy as np
import random

f = 4 # length of vectors
seqs = []
for i in xrange(400):
    v = [random.randint(0, 2) for z in xrange(f)]
    seqs.append(''.join(map(str,v)))

seqs = np.array(seqs)
index = nmslib.init(method='hnsw', space='leven')
index.addDataPointBatch(seqs)
index.createIndex()
ids, distances = index.knnQuery(seqs[0], k=2)
```

This gives:

> RuntimeError: 2018-07-28 08:58:41 spacefactory.h:50 (CreateSpace) It looks like the space leven is not defined for the distance type : FLOAT

I also tried:

`seqs.append(v)`

with the same failure.

What is the right way to do this?

**Comment by searchivarius** [comment]
Hi @lesshaste it requires an integer data (or you can use normalized Levenshtein ``normleven'' instead). Anyways, you need to init the library with additional argumens:
```
nmslib.init(method='hnsw', space='leven', data_type=nmslib.DataType.OBJECT_AS_STRING, dtype=nmslib.DistType.INT)
```

**Comment by lesshaste** [comment]
Thanks. In the end this worked.

```
import nmslib
import numpy as np
import random

f = 4 # length of vectors
seqs = []
for i in xrange(400):
    v = [random.randint(0, 2) for z in xrange(f)]
    seqs.append(''.join(map(str, v)))

print("Made data. Now time to build index.")
index = nmslib.init(method='hnsw', space='leven', data_type=nmslib.DataType.OBJECT_AS_STRING, dtype=nmslib.DistType.INT)
index.addDataPointBatch(seqs)
index.createIndex(print_progress=True)
ids, distances = index.knnQuery(seqs[0], k=10, print_progress=True)
```

In short, I needed to make a list of strings. 

I am not sure I understand what you meant by "it requires an integer data " as an array of ints doesn't work.   Do you mean it has to be a string of ints?

**Comment by searchivarius** [comment]
@lesshaste print_progress isn't a valid argument for the query function.

Regarding the type int: we have types of the distance: int, float, double and type of the object. It can be dense vector, sparse vector and anything that is a string. 

Well, it looks like the distance type other than float isn't useful, but this wasn't clear when the library was created.

**Comment by lesshaste** [comment]
Sorry I still don't understand fully. Would you mind showing me the full version of my code below that uses dense vectors please. This doesn't work, for example,

```
f = 10
# length of vectors
seqs = []
for i in xrange(400):
    v = [float(random.randint(0, 2)) for z in xrange(f)]
    seqs.append(np.array(v))

print("Made data. Now time to build index.")
index = nmslib.init(method='hnsw', space='leven', data_type=nmslib.DataType.OBJECT_AS_STRING, dtype=nmslib.DistType.INT)
```

The only version I have managed to get to work is when v is converted to a string.

**Comment by searchivarius** [comment]
Sure, but v **must** be converted to string. Levenstein distance is defined on strings, but the distance type is integer:
```
#!/usr/bin/env python3
import nmslib
import numpy as np
import random

f = 4 # length of vectors
seqs = []
for i in range(400):
    v = [random.randint(0, 2) for z in range(f)]
    seqs.append(''.join(map(str, v)))

print("Made data. Now time to build index.")
index = nmslib.init(method='hnsw', space='leven', data_type=nmslib.DataType.OBJECT_AS_STRING, dtype=nmslib.DistType.INT)
index.addDataPointBatch(seqs)
index.createIndex(print_progress=True)
ids, distances = index.knnQuery(seqs[0], k=10)
print(ids, distances)
```

**Comment by lesshaste** [comment]
Thanks so much!  I have other questions but I will ask them in a different issue :)

**Comment by searchivarius** [comment]
@lesshaste you are most welcome!

**Comment by VasantVK** [comment]
Does using the leven space return the queried string as the nearest neighbor with a distance of 0? I am getting some queries that are returning itself and some that aren't.

**Comment by searchivarius** [comment]
@VasantVK no problem. Indeed, the search doesn't guarantee 100% accuracy.
