### ISSUE TITLE
Squared Euclidean for normed vectors

### ISSUE THREAD

**Issue by jodevak** [nmslib/nmslib#343]
Is it possible to perform search on l2 normed vectors using squared-euclidean distance ?

**Comment by jodevak** [comment]
@searchivarius Im asking because this because i dont know the details of the approximate l2 calculation, however if the results are actually given using the original l2 forumla i will square the results ,  thanks alot.

**Comment by searchivarius** [comment]
@jodevak ok, no problem, thanks! I was just trying to make sure we were on the same page (i.e., I understand your need).
