### ISSUE TITLE
Sparse cosine slower than brute force

### ISSUE THREAD

**Issue by bkj** [nmslib/nmslib#347]
I'm looking at the [sparse cosine notebook](https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_sparse_cosine.ipynb).  It looks like NMSLIB is actually slower than the brute force baseline:

```
kNN time total=0.895622 (sec), per query=0.001791 (sec), per query adjusted for thread number=0.007165 (sec)
...
Brute-force preparation time 0.018111
brute-force kNN time total=0.655375 (sec), per query=0.001311 (sec)
```

NMSLIB takes `0.895622` vs brute KNN taking `0.655375` -- is that right, or am I misunderstanding?

**Comment by searchivarius** [comment]
Hi @bkj : this is not impossible, b/c the data set is very small. If this is true for say 100K data points then I would have been worried.

**Comment by bkj** [comment]
Any pointers to a larger sparse dataset I could test with?

**Comment by searchivarius** [comment]
@bkj https://github.com/nmslib/nmslib/blob/master/data/download_wikipedia_sparse.sh
Please, post the results. I am pretty sure, it's fine at the C++ level, but I wonder this might not translate into Python bindings for sparse spaces. Thanks!

**Comment by bkj** [comment]
OK cool -- running the same code w/ a query/index split of 27K/3K records from the wikipedia dataset:
```
kNN time total=5.335008 (sec), per query=0.001778 (sec), per query adjusted for thread number=0.007113 (sec)
brute-force kNN time total=19.549971 (sec), per query=0.006517 (sec)
kNN recall 0.932533
```
so that looks much better.  Might be good to add a disclaimer to the example notebook.

**Comment by searchivarius** [comment]
@bkj thanks a lot for testing! this makes sense. the gap increases with the data size. I have added a couple of words to one of the readme pages.
