### ISSUE TITLE
Installation issues on a Windows machine

### ISSUE THREAD

**Issue by ivan-marroquin** [nmslib/nmslib#348]
Hi,

I have Python 3.6.5 on a windows 10 machine. I already have pybind11 (2.2.4) with  visual studio 2015 (see screen shot)
![visual_studio](https://user-images.githubusercontent.com/28459534/46291875-2cd74e80-c555-11e8-81b3-272a4522097f.PNG)

Then, when I ran the command "pip install nmslib" from a DOS terminal, I noticed two error messages:
A)   This one occurs almost at the beginning of the compilation
  nmslib.cc
  nmslib.cc(16): fatal error C1083: Cannot open include file: 'pybind11/pybind11.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for nmslib

B) This one occurs at the end of the compilation

    ----------------------------------------
Command "c:\temp\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\IMARRO~1\\AppData\\Local\\Temp\\pip-build-aj_e7x2e\\nmslib\\setup.py';f=getattr(tokenize, 'open', op
en)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\IMARRO~1\AppData\Local\Temp\pip-0tm7cks5-record\install-record.txt --single
-version-externally-managed --compile" failed with error code 1 in C:\Users\IMARRO~1\AppData\Local\Temp\pip-build-aj_e7x2e\nmslib\

A copy of the entire messages produced during the compilation can be found in the attached zip file.

Any suggestions?

Many thanks,

Ivan
[Error_Log.zip](https://github.com/nmslib/nmslib/files/2434149/Error_Log.zip)

**Comment by searchivarius** [comment]
I personally never built this new version on Windows yet :-( Are you sure you executed all the steps from this page: https://github.com/pybind/python_example#installation ??

**Comment by ivan-marroquin** [comment]
Thanks for the suggestion. I downloaded the zip file, and then I looked for "python_example" file. No luck. The instructions seems to follow a linux command rather than a call in windows.

But I noticed there is folder named "python_bindings" that contains a setup.py file 

![directory_structure](https://user-images.githubusercontent.com/28459534/46318824-60d66200-c59d-11e8-8a14-5d2b95060406.PNG)

So, I run "python setup.py install". There is a missing .h file

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I.\nmslib\similarity_search\include -IC:\Temp\Python\Python36\Include -IC:\Users\IMarro
quin\AppData\Roaming\Python\Python36\Include -IC:\Temp\Python\Python36\lib\site-packages\numpy\core\include -IC:\Temp\Python\Python36\include -IC:\Temp\Python\Python36\include "-IC:\Program Files (x86
)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Win
dows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpnmslib.cc /Fobuild\temp.win-amd64-3.6\Release\nmslib.obj /EHsc /openmp /O2 /DVERSION_INFO=\"1.7.3.4\"
nmslib.cc
nmslib.cc(27): fatal error C1083: Cannot open include file: 'init.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

The entire error log can be found in the attached file.

Many thanks for your help,

Ivan

[Error_Log_2.zip](https://github.com/nmslib/nmslib/files/2435879/Error_Log_2.zip)

**Comment by benfred** [comment]
@ivan-marroquin you hit two different issues there =(

The first issue was introduced in this commit: https://github.com/nmslib/nmslib/commit/75926713c4c4e4ef12ac007e8e43cb70032098dc and shows up in your error log as 
```
    nmslib\similarity_search\src\method\hnsw.cc(687): error C2065: 'and': undeclared identifier
```
(the rest of it was just noise unfortunately - fixing that would make the build work)

The second issue is that we have a symlink in python_bindings/nmslib that wasn't set up correctly on your system, and that was causing the 'init.h' header to not be found in your second error log.  Unless you enable git symlinks on your system, building from source wouldn't work previously =(.

I've fixed both of those issues PR #349.

**Comment by ivan-marroquin** [comment]
Thanks so much benfred for a such quick fix!

Could you let me know when I can download a new version of this library? Also, for the installation of this library in Windows, the procedure is to run "python setup.py install" (from the python_bindings folder)? Am I correct?

Ivan

**Comment by searchivarius** [comment]
Hi @ivan-marroquin I have uploaded code to pipy, could you try it? Thank you!

**Comment by ivan-marroquin** [comment]
Hi @searchivarius , I just downloaded from the pipy website. The compilation almost finished without error. At the very end, I got these messages:

.\nmslib\similarity_search\include\method/hnsw.h(292): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
.\nmslib\similarity_search\include\method/hnsw.h(294): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

I attached the error log for your reference.

Many thanks,
Ivan

[Error_log_3.zip](https://github.com/nmslib/nmslib/files/2438733/Error_log_3.zip)

**Comment by benfred** [comment]
I don't think the fix made it into the 1.7.3.5 release? It looks like the same error message as first seen, and when I downloaded the release from pypi - I don't see the fix in hnsw.cc

grepping for the fix in the tarball on pypi:
```bash
nmslib-1.7.3.5 ben$ grep 'empty.. and ' nmslib/similarity_search/src/method/hnsw.cc 
```
shows:
```c++
        if (this->data_.empty() and this->data_rearranged_.empty()) {
```

**Comment by searchivarius** [comment]
@benfred thank you, I will double check. something has possibly gone wrong.

**Comment by searchivarius** [comment]
@benfred and @ivan-marroquin ok, now I think I picked up the latest changes.

**Comment by benfred** [comment]
@searchivarius the newest release (1.7.3.6) looks good to me! thanks!

**Comment by ivan-marroquin** [comment]
Hi @searchivarius and @benfred 

I was able to compile the latest version. There were some warning messages (I attached the log) but the compilation was successful

If this OK with you, I would like to suggest the following changes to your instructions on a windows machine ( https://github.com/pybind/python_example#installation ):
- download visual studio 14 for windows from this link http://landinghub.visualstudio.com/visual-cpp-build-tools
- install pybind11 using the command "pip install pybind11"
- download nmslib compressed file from https://pypi.org/project/nmslib/
- uncompress file and cd onto the nmslib folde, and run the command "python setup.py install"


Can I ask an additional question? I have data matrix of 133000000 x 4 and I would like to use the HNSW. What could be optimal values for M, efConstruction, efSearch to run a relative fast search and indexing? Do I need to set dealunay-type to zero?

Many thanks for everything,

Ivan

**Comment by benfred** [comment]
awesome! glad that you got it working. 

The warnings are annoying - but can be safely ignored. The step to install pybind11 first is also not strictly necessary (the nmslib install displays an error message if pybind11 isn't installed, but then will fallback and install it and finish successfully - at least when I tried it).

Adding some more install instructions are probably a good idea. I've also been thinking about distributing binary wheels for this package (will follow up separately with @searchivarius about this), which would make the process virtually painless (no need to install a c++ compiler etc).

**Comment by searchivarius** [comment]
Hi @ivan-marroquin regarding the recommendations for parameters. 
If you have only a **four**-dimensional matrix, 
1. I would use rather small values of M <= 20 and efConstruction <=100. I would have also played with a parameter 
2. Likewise I would try use **larger** values of the paramter mult and see if this helps.
3. delanau_type equals two usually works much better
When you experiment, choose a smaller subset to play. It should take only a minute or so to index say 10M 4-d vectors.

**Comment by searchivarius** [comment]
@ivan-marroquin using post=2 or post=1 is usually a good idea, unless indexing becomes too long.

**Comment by ivan-marroquin** [comment]
Hi @searchivarius  and @benfred 

Thanks for everything!
