### ISSUE TITLE
TypeError: loadIndex(): incompatible function arguments

### ISSUE THREAD

**Issue by tgsmith61591** [nmslib/nmslib#350]
I might be misunderstanding how this function is used, but per the [documentation](https://benfred.github.io/nmslib/api.html#nmslib-floatindex), I expect to be able to persist and load an index from disk.

Using the `saveIndex` method, I've saved an index:

```python
location = "abc.pkl"
index.saveIndex(location)
```

But trying to load the index yields the `TypeError`:

```python
>>> from nmslib.dist import FloatIndex
>>> FloatIndex.loadIndex(filename=location, print_progress=True)

# Which yields:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: loadIndex(): incompatible function arguments. The following argument types are supported:
    1. (self: nmslib.dist.FloatIndex, filename: str, print_progress: bool=False) -> None

Invoked with: kwargs: filename='abc.pkl', print_progress=True
```

Additional info/thoughts:

* In the actual call, I am using an absolute path. For the example, I just replaced it with "abc.pkl"
* I was wondering whether the `loadIndex` call actually was an instance method rather than a static method, but I can't find where in the source code it's even defined, so I suspect it's just a binding to a C++ method somewhere
* The "`-> None`" is causing some concern for me, since it makes me think this is an in-place operation on an existing index. I'm hoping I'm wrong on that front and that there's a way to load an index statically from disk.

**Comment by searchivarius** [comment]
Hi @tgsmith61591 : load index is not static: https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_optim.ipynb

**Comment by tgsmith61591** [comment]
Thanks for the clarification, @searchivarius. That was my fear 😄 Knowing that it's not static, the way I got around this was re-initializing the index:

```python
import nmslib

# ... contained in a wrapper class, hence the "self"
index = nmslib.init(method=self.method, space='cosinesimil')
index.load("abc.pkl")
```

And this appears to work. Whether there are any side-effects to re-initializing and loading, I'm not sure.

**Comment by searchivarius** [comment]
@tgsmith61591 there's currently a bit of a mess due to somewhat adhoc development path, but if you
1. Use a non-optimized index you have to reload data.
2. For the optimized index this is not necessary.
I will fix this in the future, but, currently, please, follow one of the notebook recipes.

**Comment by Berlyli866** [comment]
i try to read the file from the google cloud bucket, but I also got the same error. what is the right way to load the index file directly from bucket without downloading to local ?
my code : 

from tensorflow.python.lib.io import file_io
with file_io.FileIO('gs://ds_haozheng/data_shared/Merch_Clip_Index/NMS_IDX_img_embd_2022_0210.idx', 'r') as f:
    img_index = nmslib.init(method='hnsw', space='cosinesimil', data_type=nmslib.DataType.DENSE_VECTOR) 
    img_index.loadIndex(f)

**Comment by searchivarius** [comment]
We don't support loading through Python file descriptors, sorry, it would be too complicated.
