### ISSUE TITLE
File format incompatibility between 1.6.3 and 1.7

### ISSUE THREAD

**Issue by goldan** [nmslib/nmslib#352]
After upgrading to 1.7 I can no longer open files created with 1.6.3. The error is in `loadIndex`: `RuntimeError: Check failed: it's either a bug or inconsistent data!` Loading the same file works fine in 1.6.3.

**Comment by searchivarius** [comment]
Hi @gold I apologize for this lack of compatibility. I do not have capacity to support index compatibility yet, but as a workaround please consider redirecting the logging output to a file. This requires only a minor change in the binding's code. Here, you need to specify the file name in the function initLibrary:
https://github.com/nmslib/nmslib/blob/v1.6/python_bindings/nmslib.cc#L151
Clearly, you would need to recompile/reinstall bindings.
