### ISSUE TITLE
Can't load python NMSLIB index?

### ISSUE THREAD

**Issue by Ceceu** [nmslib/nmslib#353]
Hello,

I am trying to load the index using the code provided in [notebook 5](https://github.com/hamelsmu/code_search/blob/master/notebooks/5%20-%20Build%20Search%20Index.ipynb):

```
search_index = nmslib.init(method='hnsw', space='cosinesimil')
search_index.loadIndex('./data/search/search_index.nmslib')
```
But, the following error happens:
```
Check failed: data_level0_memory_
Traceback (most recent call last):
search_index.loadIndex("./data/search/search_index.nmslib")
RuntimeError: Check failed: it's either a bug or inconsistent data!
```

My computer has only 8GB as primary memory. So, did this happen because the index is over 8GB and could not be loaded into memory?

Thank you for any help.

**Comment by searchivarius** [comment]
Hi @Ceceu could you please check the following:
1. That notebook you reference is consistent with our notebook: https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_optim.ipynb
2. You use the latest version of NMSLIB.

**Comment by Ceceu** [comment]
Thanks for the quick response,

The notebook I referenced is consistent with yours and uses version 1.7.2.
However, I really do want to understand the reason for the error. Has it occurred because my computer does not have enough memory to load the index (which has more than 8.6GB)? What does "Check failed: data_level0_memory_" mean?

Thank you very much.

**Comment by Ceceu** [comment]
That's the reason then. The data has 8.6GB and I only have 8GB RAM.

**Comment by searchivarius** [comment]
@Ceceu thanks for checking. Yep, it is not enough.
