### ISSUE TITLE
Does HNSW support Jaccard distance on binary vector inputs?

### ISSUE THREAD

**Issue by chunjiangzhu** [nmslib/nmslib#354]
Hi, We searched previous posts #306 and found that HNSW supports "bit_hamming". We suppose the input can be binary vectors because the distance name has a "bit" there. 

Then, does HNSW also supports Jaccard distance on binary vectors? We have a concern that the algorithm itself (not the implementation) does not work for Jaccard distance on binary vectors. If it works, the code in the notebook (https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_generic_sparse_jaccard.ipynb) can also be adapted (or directed used) for binary inputs, right? Thanks!

**Comment by searchivarius** [comment]
@chunjiangzhu to see if the algorithm works for bit vectors, you can use the sparse Jaccard space. You just need to convert binary vectors to a set of IDs. But we do not support computation of the Jaccard over binary vectors directly, sorry.

It's surprising to hear that HNSW doesn't work for Jaccard, which is a nice metric. Could you provide a sample?

**Comment by chunjiangzhu** [comment]
Thank you, for your prompt reply. Yes, we have applied your code on binary vectors with the sparse Jaccard space. The results look nice. But we were not 100% sure theoretically whether the algorithm works for Jaccard  on **binary inputs**, so we posted the question to get a quick answer.

BTW, a naive question: the name "non-metric space library" does not mean that the algorithms there are designed for non-metric space only?

**Comment by searchivarius** [comment]
Hi @chunjiangzhu no problem. Just to make sure, there are two sides of the problem:
1. Whether an algorithm works with Jaccard in principle
2. Whether we have an implementation that computes the Jaccard-based distance given two binary dense vectors.
I would emphasize that in both cases, we have the same distance function. However, the difference will be in the **encoding** only. For example, if you have no more than 32 IDs, a sparse representation of
the set {0, 5, 13, 31} will be just a set of space-separated integers: 0 5 13 31. Internally, it will be stored as a sparse vector with 4-byte vector-element IDs.

A binary representation would be a 32-bit integer with the binary representation:
00001000000001......1

There is **no theoretical difference** between these two cases, only the difference in representation. Also, there is no implementation that would take binary vectors and correctly compute the Jaccard between them. I hope this is clear.

Regarding the name question: it merely means we are more general than most other libraries. In fact, most algorithms for non-metric spaces are also applicable to metric spaces.
