### ISSUE TITLE
Question for retrieving all data points (not feature request)

### ISSUE THREAD

**Issue by blackberrybhtg** [nmslib/nmslib#355]
My question is does hnsw index support retrieving all data points indexed? From the current API, it doesn't seem likely. I am just double confirming that and wondering how much work it might take to add that.

**Comment by searchivarius** [comment]
@blackberrybhtg not much, but I'd rather not do this. I have plans to address this issue in a more systematic fashion in a newer version.

**Comment by blackberrybhtg** [comment]
Great to heart about a newer version! When roughly can we see the new version? Like 2018, early/mid 2019?

**Comment by searchivarius** [comment]
Not very soon, but I will be working on it next year.
