### ISSUE TITLE
Optimized index raises RuntimeError on load when saved with `negdotprod` space

### ISSUE THREAD

**Issue by chomechome** [nmslib/nmslib#356]
Basically, this is what I am trying to do
```python
import nmslib

space = 'negdotprod'

vectors = [[1, 2], [3, 4], [5, 6]]

index = nmslib.init(space=space, method='hnsw')
index.addDataPointBatch(vectors)
index.createIndex(
    {'M': 15, 'efConstruction': 200, 'skip_optimized_index': 0, 'post': 0}
)
index.saveIndex('test.index')

new_index = nmslib.init(space=space, method='hnsw')
new_index.loadIndex('test.index')
```
and it raises
```
Check failed: totalElementsStored_ == this->data_.size() The number of stored elements 3 doesn't match the number of data points ! Did you forget to re-load data?
Traceback (most recent call last):
  File "8.py", line 15, in <module>
    new_index.loadIndex('test.index')
RuntimeError: Check failed: The number of stored elements 3 doesn't match the number of data points ! Did you forget to re-load data?
```

If I change `space` variable to `cosinesimil`, it works just fine. It seems that data points are not stored, even though `hnsw` method with `skip_optimized_index=0` is used.

**Comment by searchivarius** [comment]
Optimized index doesn't work with anything except l2 and cosine sorry.

**Comment by earboxer** [comment]
Is there another way to save and load indexes in other spaces? Or do you have any pointers where the development would need to happen for this to work?

**Comment by searchivarius** [comment]
@earboxer we will have to change a lot of stuff under the hood. Like restructuring all the library to fix a bunch of issues. If anybody is really serious about helping with this, this can be sped up. But, again, it is going to be a lot of changes.

**Comment by searchivarius** [comment]
@earboxer on a second thought, we can a quick fix for data loading too. I think it is actually worth doing. Will you be able to help?

**Comment by earboxer** [comment]
Depends on what needs to be done, I should be able to help! (though I haven't gotten myself too familiar with the code base).

**Comment by searchivarius** [comment]
@earboxer we need some generic code to save/load data, which can be invoked when the method doesn't save data on its own. Plus, helping me to ship this (including testing, etc.).

**Comment by ibeltagy** [comment]
How easy is it to support this for the `cosinesimil_sparse` space ?

**Comment by searchivarius** [comment]
@ibeltagy it's not difficult, this must be done ASAP, but I have a pile of deadlines till the beginning of May.

**Comment by ibeltagy** [comment]
@searchivarius, I am not familiar with the code, but I can give it a shot if it is easy enough and you provide more details on what needs to be done.

**Comment by searchivarius** [comment]
@ibeltagy if you are willing to help, please, drop me a line in a couple of weeks (leo at boytsov dot info). For now, I won't be able to do anything (even giving instructions). Thank you!

**Comment by earboxer** [comment]
Looking at the code, my first guess is we need to modify [index.h](https://github.com/nmslib/nmslib/blob/314f48e0f86efafe9f6ad853236603400030a0ac/similarity_search/include/index.h#L57) to define SaveIndex and LoadIndex to be good, then allow the specific index types to call the function from their parent...

Possible references:

* [pivot_neighb_invindx.cc](https://github.com/nmslib/nmslib/blob/314f48e0f86efafe9f6ad853236603400030a0ac/similarity_search/src/method/pivot_neighb_invindx.cc#L373)
* [hnsw.cc](https://github.com/nmslib/nmslib/blob/599eeafe2a6a3c7164e7eff12f01f639c68c2ae2/similarity_search/src/method/hnsw.cc#L727) --  this is the one that doesn't work, as OP noted.

Is there any recommended way to understand the class inheritance structure (Doxygen or similar tools). It's quite intimidating as a developer.

**Comment by searchivarius** [comment]
@earboxer let's maybe take it offline. leo@boytsov.info.

But basically, we need some generic saveData function that is being called every time there's need to save the index. Then, we can call loadData each time there's need to load the index.

**Comment by searchivarius** [comment]
Hi @earboxer @ibeltagy @chomechome I am going to address this issue ASAP. I would have done this over this weekend, but I have some doubts about what's the best way to fix this. Historically, these indices  were meta-indices **except for L2 and cosine**.

So, I have two options
1. Embed a data loading/saving call into Load/SaveIndex and **always* load store data.
2. Somehow make loading data optional, because for L2 and HNSW there's mostly no need to load this data (except if you want to recompute distances between arbitrary points). This entails two possibilities:
2.2 Having a separate couple of calls LoadData and SaveData.
2.3 Have a flag loadData, saveData in the loadIndex call, which might be True or False by default.

I understand that this is less than ideal, but until the major big-time refactoring it's not possible to fix.

**Comment by chomechome** [comment]
Hello! If it's not decided yet, I suggest using a flag (option 2.3) since it's backwards compatible and is easier to use than separate save/load calls.

**Comment by searchivarius** [comment]
@chomechome this makes sense: so the default False (not loading the data) is probably Ok? The reason I want to keep by default is that many people are using HNSW and just query data, i.e., they don't compute distances between arbitrary points. HNSW, for these common cases, does save the data on its own. So, for these people, saving/loading an additional copy of the data doesn't make sense.

**Comment by ibeltagy** [comment]
I would also go with option 2.3 with False being the default. As you mentioned, I don't need to compute the distance and don't want to save the data, especially that reducing the index/data size is important for my application.

**Comment by searchivarius** [comment]
This issue should be tested in 1.8. I appreciate if you could test. I have also reorganized the docs. I believe they should be more accessible now:
https://github.com/nmslib/nmslib/tree/master/manual

**Comment by chenqi0805** [comment]
@searchivarius Has this issue been resolved? I tried the python snippet in the description with v2.0.6 but the error persists.

**Comment by searchivarius** [comment]
@chenqi0805 it was resolved with a crutch :-) one needs to specify save_data=True and load_data=True:
```
index.saveIndex('test.index', save_data=True)
```
then you can load it:
```
new_index = nmslib.init(space=space, method='hnsw')
new_index.loadIndex('test.index')
```

**Comment by chenqi0805** [comment]
@searchivarius Thank you!

**Comment by chenqi0805** [comment]
@searchivarius I am tackling a similar issue in Java native interface c++ code of a related project depends on nmslib as we also need to support spaces other than l2 and cosine. Do you know how much impact saving and loading data for ObjectVector has on the performance of saving and loading index?

**Comment by searchivarius** [comment]
@chenqi0805 not off the top of my head, sorry.
