### ISSUE TITLE
Speed up pip install 

### ISSUE THREAD

**Issue by matthen** [nmslib/nmslib#358]
Currently pip installing is slow, since there is a compile step. Is there any way to speed it up? On my macbook:

```
time pip install --no-cache nmslib
Collecting nmslib
  Downloading https://files.pythonhosted.org/packages/e1/95/1f7c90d682b79398c5ee3f9296be8d2640fa41de24226bcf5473c801ada6/nmslib-1.7.3.6.tar.gz (255kB)
    100% |████████████████████████████████| 256kB 8.8MB/s 
Requirement already satisfied: pybind11>=2.0 in .../virtualenv/python3.6/lib/python3.6/site-packages (from nmslib) (2.2.4)
Requirement already satisfied: numpy in .../virtualenv/python3.6/lib/python3.6/site-packages (from nmslib) (1.15.4)
Installing collected packages: nmslib
  Running setup.py install for nmslib ... -
done
Successfully installed nmslib-1.7.3.6

real	3m11.091s
```

would it be a good idea to provide pre-compiled wheels over pip? That would also simplify the process of finding the pybind11 headers (I had to do something special to copy them in for pip when running with a `--target` dir)

**Comment by searchivarius** [comment]
Hi @matthen I am not sure about precompiled binaries, but it doesn't make much sense, b/c it will not be compatible across all platforms. I will keep instead working on a leaner version of the library.

**Comment by matthen** [comment]
I think various other libraries provide pre-built wheels over pip, e.g. tensorflow

**Comment by searchivarius** [comment]
@matthen yes and basic tensorflow setup doesn't even support SIMD. It is possible, but it's going to be a pain to implement. Again, I would rather do it only for the lightweight version.

**Comment by scottgigante** [comment]
I second this - by providing binaries for Windows, tensorflow avoids the heavy dependency of Visual Studio for simple installations.

**Comment by scottgigante** [comment]
@searchivarius I built it by running `python setup.py bdist_wheel` on a Windows machine. If you have Python 3.5, 3.6 and 3.7 all installed, (and I'm assuming you already use `twine` to upload your source distributions) you could run the following:
```
git checkout v1.7.3.6
python35 setup.py bdist_wheel
python36 setup.py bdist_wheel
python37 setup.py bdist_wheel
twine upload -r pypi dist/*
```
Note that the same commands run on linux will provide unix binaries, which will also be good for speeding up installation on those systems.

**Comment by searchivarius** [comment]
@scottgigante thank you! Comment: one needs to limit the set of SIMD instructions for this to be truly useful. If you have AVX2, but other folks don't.... this won't work.

**Comment by scottgigante** [comment]
That's a very good point!

>

**Comment by searchivarius** [comment]
Hi @scottgigante would you care to make a similar fix for Windows:
https://github.com/nmslib/nmslib/pull/361
? It shouldn't break the Unix part though. Thanks!

**Comment by scottgigante** [comment]
@searchivarius I've had a look in `setup.py` and I don't see any code which sets `\arch`. I looked at the docs and I don't see any MS equivalent to `march=native`.

But also, when I ran `$env:CFLAGS="\arch=AVX"; python setup.py install` (powershell) this flag didn't get sent to `cl` at compile time. Not quite sure how to set this.

**Comment by scottgigante** [comment]
On a separate note, I've been working on a PR to make travis and appveyor automatically build wheels and submit them to pypi - only problem is I've hit a stumbling block where nmslib won't compile on x86. Not sure if this a configuration problem or actually a bug in the code. https://ci.appveyor.com/project/scottgigante/nmslib/build/job/8u82lkbthwp82iqm

**Comment by searchivarius** [comment]
Hi @scottgigante great, regarding settings, it seems to me that this array specifies the MSVC compilation flags:
https://github.com/nmslib/nmslib/pull/361/files#diff-535bcc8311fdc34129ee96ab7738ba25R86

**Comment by searchivarius** [comment]
@scottgigante 
```
'msvc': ['/EHsc', '/openmp', '/O2'],
```
one can modify it later too

**Comment by scottgigante** [comment]
I see this - but I'm not sure what the fix would be.

**Comment by scottgigante** [comment]
I've submitted a PR which just takes a single environment variable `ARCH` which can take the following values: `IA32|SSE|SSE2|AVX|AVX2|ARMv7VE|VFPv4`. Let me know if you would rather set it in a different way. I've also submitted the automatic deploy PR despite the appveyor x86 build not running - we've gone beyond my C++ pay grade, I'm afraid.

**Comment by searchivarius** [comment]
@scottgigante this looks right! Do I get it correctly that there exists Windows for ARM?

**Comment by scottgigante** [comment]
Yep, that's correct! Here is the [docs page](https://docs.microsoft.com/en-us/cpp/build/reference/arch-arm?view=vs-2017) and a [blog post about the VS release last May](https://blogs.windows.com/buildingapps/2018/05/08/visual-studio-support-for-windows-10-on-arm-development/)

**Comment by jhagege** [comment]
+1. anyone found a way to accelerate pip install ?
Thanks :)

**Comment by searchivarius** [comment]
@jhagege it needs to be a binary installation. If anybody wants to help, the help is welcome.

**Comment by scottgigante** [comment]
Related to #364 which appears to not quite have worked. Some points:

From appveyor (https://ci.appveyor.com/project/searchivarius/nmslib/builds/25077691/job/mb98fje0x6owt4xr):

* https://github.com/nmslib/nmslib/blob/master/.appveyor.yml#L52 change from `mv .pypirc` to `mv ../.pypirc`
* https://github.com/nmslib/nmslib/blob/master/.appveyor.yml#L59 change from `twine` to `python -m twine`

For travis (https://travis-ci.org/nmslib/nmslib/jobs/549423394):

* the secret environment variable `PYPI_PASSWORD` has not been set. The same could be true for appveyor but I can't tell as a) I don't have access to the build config page and b) it doesn't get far enough to hit the equivalent error because `twine` is not on path.

**Comment by searchivarius** [comment]
@scottgigante let's not worry about this now. I think I may fix this some day. However, I think creating a binary distribution would be more important.

**Comment by scottgigante** [comment]
@searchivarius to be clear this would create the binary distribution for each release. The alternative is to manually create them and upload manually with twine as in the deploy section of `appveyor,yml`.

**Comment by searchivarius** [comment]
@scottgigante ahh right, sorry I forgot about this. It looks like I need to make it work, indeed.

**Comment by scottgigante** [comment]
Thanks @searchivarius !!!

**Comment by searchivarius** [comment]
All credit goes to you @scottgigante sorry it took me so long. I will be more proactive in the future.

**Comment by scottgigante** [comment]
No need for apologies! Glad it's up and running.

**Comment by matthen** [comment]
the binary release hasn't been built and pushed to pypi yet, right? would appreciate a ping on this thread when it is! :)

**Comment by searchivarius** [comment]
Hi @matthen it has been, but I am also rebuilding it (so there's a mix of two-version wheels on pypi). Feel free to check it tomorrow or in a few hours. Thank you!
