### ISSUE TITLE
Stuck to install in Google Colab

### ISSUE THREAD

**Issue by happypetewht** [nmslib/nmslib#360]
I tried to install nmslib in Google Colab, it showed below and stuck there. 

_______________________________________________________________________________________________________________
Collecting nmslib
  Downloading https://files.pythonhosted.org/packages/e1/95/1f7c90d682b79398c5ee3f9296be8d2640fa41de24226bcf5473c801ada6/nmslib-1.7.3.6.tar.gz (255kB)
    100% |████████████████████████████████| 256kB 15.3MB/s 
Collecting pybind11>=2.0 (from nmslib)
  Downloading https://files.pythonhosted.org/packages/f2/7c/e71995e59e108799800cb0fce6c4b4927914d7eada0723dd20bae3b51786/pybind11-2.2.4-py2.py3-none-any.whl (145kB)
    100% |████████████████████████████████| 153kB 29.4MB/s 
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from nmslib) (1.15.4)
Building wheels for collected packages: nmslib
  Running setup.py bdist_wheel for nmslib ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1tfu_uob/nmslib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-twez7_y5 --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  creating tmp
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c /tmp/tmpkr8w7cmk.cpp -o tmp/tmpkr8w7cmk.o -std=c++14
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c /tmp/tmpgq1lzveb.cpp -o tmp/tmpgq1lzveb.o -fvisibility=hidden
  building 'nmslib' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/nmslib
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src/space
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src/method
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./nmslib/similarity_search/include -I/usr/local/include/python3.6 -I/root/.local/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c nmslib.cc -o build/temp.linux-x86_64-3.6/nmslib.o -O3 -march=native -fopenmp -DVERSION_INFO="1.7.3.6" -std=c++14 -fvisibility=hidden
  nmslib.cc:16:10: fatal error: pybind11/pybind11.h: No such file or directory
   #include <pybind11/pybind11.h>
            ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for nmslib
  Running setup.py clean for nmslib
Failed to build nmslib
Installing collected packages: pybind11, nmslib
  Running setup.py install for nmslib ... -

_____________________________________________________________________________________________________________

I tried a few solutions from https://github.com/nmslib/nmslib/issues/307. Those solutions did not work. Is it becuase I am using Google Colab?

**Comment by searchivarius** [comment]
Sorry about this, there seems to be an issue with pybind. Did you try:
```
 as a short term fix, trying going 'pip install pip==9.0.3' and then installing nmslib - longer term I think we will have to wait for a patched version of pybind11
```

**Comment by happypetewht** [comment]
> Sorry about this, there seems to be an issue with pybind. Did you try:
> 
> ```
>  as a short term fix, trying going 'pip install pip==9.0.3' and then installing nmslib - longer term I think we will have to wait for a patched version of pybind11
> ```

yes, I did. It does not work either.

**Comment by searchivarius** [comment]
@happypetewht what does the following line print:
```
python -c 'import pybind11; print(pybind11.get_include())'
```
Could you also find the exact installation location of pybind11? It is in principle possible to specify these locations in the make/setup files, I think.

**Comment by happypetewht** [comment]
> @happypetewht what does the following line print:
> 
> ```
> python -c 'import pybind11; print(pybind11.get_include())'
> ```
> Could you also find the exact installation location of pybind11? It is in principle possible to specify these locations in the make/setup files, I think.

 I did with the line "python -c 'import pybind11; print(pybind11.get_include())'"

it shows "/usr/local/include/python3.6"

I have been trying to find pybind11

**Comment by searchivarius** [comment]
Sure, you can try to
1. First check that pybind is indeed installed to that directory. 
2. If it is installed in another place, you can try to specify it in https://github.com/nmslib/nmslib/blob/master/python_bindings/setup.py#L119
