### ISSUE TITLE
Jaccard distance on bit vectors

### ISSUE THREAD

**Issue by gregfriedland** [nmslib/nmslib#369]
Hello,
In https://github.com/nmslib/nmslib/issues/354, there's a comment "Jaccard over the bit vectors is rather trivial to implement, but nobody needed it so far."

Could you describe what would be involved in making this change? I'm trying to apply Jaccard to 2048-bit vectors on millions of inputs and the current representation (which stores each bit as an int?) wants more memory than I have available...

Thanks,
Greg

**Comment by searchivarius** [comment]
Hi @gregfriedland just to make sure we are on the same page: we are talking about the bit-parallel computation of Jaccard over fixed-size vectors, right?

**Comment by gregfriedland** [comment]
Thanks @searchivarius for the quick response.

Yes, ideally it'd take advantage of bit-parallel operations on 64-bit chunks aggregated up to 2048 bits. That seems like it would be quite fast and more memory efficient.

If you have other suggestions on reducing memory consumption though I'd be very interested to hear them.

**Comment by searchivarius** [comment]
@gregfriedland it's surely possible to reduce space consumption using techniques implemented in projects such as https://roaringbitmap.org/, but it's certainly quite a bit of engineering. To implement the Jaccard on fixed-size bitmasks, one needs to create a space nearly identical to this one:
```
https://github.com/nmslib/nmslib/blob/master/similarity_search/src/space/space_bit_hamming.cc
```
Crucially, the distance function needs to be reimplemented. A bit more detailed description (may be slightly outdated is in the manual, section 7.2):
https://github.com/nmslib/nmslib/blob/master/manual/manual.pdf

Last, but not least, it would be great to have your implementation integrated into NMSLIB. 

Thank you!
