### ISSUE TITLE
the result of knnQuery is different to the result of knnQueryBatch

### ISSUE THREAD

**Issue by himansoo** [nmslib/nmslib#370]
I compared with knnQuery() and knnQueryBatch().
But, I have different results. as below

Check the below code.

========= results for knnQuery =======
[4 5 1 2 9 7 8 6 0 3]
[0.34580976 0.40854776 0.43443924 0.4470001  0.4760959  0.49099177
 0.5050826  0.52543676 0.54977345 0.55035424]
========= results for knnQueryBatch =======
[0 9 1 7 5 6 2 4 3 8]
[-1.1920929e-07  1.8902314e-01  3.3199942e-01  3.8989604e-01
  3.9615113e-01  4.0524119e-01  4.1655707e-01  4.2546618e-01
  5.4786187e-01  6.7175913e-01]

[test.txt](https://github.com/nmslib/nmslib/files/2888092/test.txt)

===== test.py==================

import nmslib
import pandas as pd
import numpy as np
import csv

df = pd.read_csv('./test.tsv', delimiter='\t', header=None, low_memory=False)
num_elements, dim = df.shape
dim = dim - 1
labels = df[dim].values

df.pop(dim)
data = df.values.astype('float32')

#data = np.random.randn(10000, 100).astype(np.float32)

index = nmslib.init(method='hnsw', space='cosinesimil')
index.addDataPointBatch(data)
index.createIndex({'post': 2}, print_progress=True)

print("")
print("========= results for knnQuery =======")
# query for the nearest neighbours of the first datapoint
ids, distances = index.knnQuery(data[0], k=10)
print(ids)
print(distances)

print("========= results for knnQueryBatch =======")
results = index.knnQueryBatch(data[0:1], k=10)
for b_ids, b_dists in results:
    print(b_ids)
    print(b_dists)

**Comment by searchivarius** [comment]
Hi, is it the same if you use ``brute_force`` method?

**Comment by himansoo** [comment]
yes. the results of brute_force method:

========= results for knnQuery =======
[4 5 1 2 9 7 8 6 0 3]
[0.3458097  0.40854776 0.43443918 0.44700003 0.4760959  0.49099183
 0.50508255 0.52543676 0.54977345 0.5503541 ]
========= results for knnQueryBatch =======
[0 9 1 7 5 6 2 4 3 8]
[0.         0.1890232  0.33199942 0.3898961  0.39615113 0.40524125
 0.41655707 0.42546612 0.5478619  0.6717592 ]

**Comment by himansoo** [comment]
Thanks for your fast feed-back. I hope that this issue will be resolved in next version. ^^

**Comment by searchivarius** [comment]
@himansoo sure, but I think you can currently use the batched version. Actually, there seems to be no real reason to have a non-batched version.

**Comment by searchivarius** [comment]
Hi @himansoo I pushed 1.8 to PyPi, could you check if this fixes the problem? I think it should. Many thanks!

**Comment by himansoo** [comment]
I checked it. The case has resolved in the current version(=1.8).

Thanks for inform to me. ^^
