### ISSUE TITLE
fatal error: 'thrift/cxxfunctional.h' file not found

### ISSUE THREAD

**Issue by madskunker** [nmslib/nmslib#372]
Trying to get this working on Mac OSX and I can't get past this.  

Any Thoughts?

Thanks

**Comment by searchivarius** [comment]
Hi @madskunker is this the main part of the library or the query server?

**Comment by madskunker** [comment]
Well I got past the by updating to thrift 12 and re-generating the cpp files and dropping them in the query-server/cpp_client_server/gen-thrift directory.

But now on the make I get

error: no viable conversion from 'stdcxx::shared_ptr<ThreadManager>' to 'boost::shared_ptr<ThreadManager>'
  boost::shared_ptr<ThreadManager> threadManager = ThreadManager::newSimpleThreadManager(threadQty)

Any ideas?

**Comment by searchivarius** [comment]
@madskunker yep, I have been upgrading to the new thrift later in a different branch, please, check it out here: https://github.com/nmslib/nmslib/commit/10ce8f7197761fec6171b3166666ad40f13db40e#diff-53ecc1e1a64b160b2f058a1def89b71a
There's also a working version of the server that works Apache Thrift 11:
https://github.com/nmslib/nmslib/tree/nmslib4a_postdoc/query_server/cpp_client_server

**Comment by madskunker** [comment]
Getting close

Just fails the Linking

/usr/local/opt/llvm/bin/clang++ -oquery_server  gen-thrift/QueryService.o gen-thrift/QueryService_server.skeleton.o gen-thrift/protocol_constants.o gen-thrift/protocol_types.o QueryService_server.o -L/usr/local/lib -L../../similarity_search//release -lthrift -lNonMetricSpaceLib -lboost_program_options -pthread -fopenmp 
duplicate symbol _main in:
    gen-thrift/QueryService_server.skeleton.o
    QueryService_server.o
ld: 1 duplicate symbol for architecture x86_64

**Comment by madskunker** [comment]
Got Thrift 11 version working FYI

**Comment by searchivarius** [comment]
@madskunker it looks like main is defined in more than one file for some reason.

**Comment by madskunker** [comment]
yep  the QueryService_server.skeleton.cpp file with thrift 12 has another main in it.  Just punted back to thrift 11  for now.

Is there a readme on  how to  use query_server and query_client?

**Comment by searchivarius** [comment]
@madskunker I should really add some, but basically the query server accepts the same set of parameters as the binary experiment, which is described in the manual see p 20-24 in the manual: https://github.com/nmslib/nmslib/blob/master/manual/manual.pdf
Plus, you need to specify the address/port of the server.
Query client is pretty much self-explanatory (run an example to see the options). Please, make sure you use the example from the branch that is Thrift-11 compatible:
https://github.com/nmslib/nmslib/tree/nmslib4a_postdoc/query_server/java_client/src/main/java/edu/cmu/lti/oaqa/apps
