### ISSUE TITLE
Unable to use ExternId

### ISSUE THREAD

**Issue by madskunker** [nmslib/nmslib#373]
How do I set the externId in my  vector file so the query_server returns it when requested?

**Comment by searchivarius** [comment]
Hi @madskunker external IDs are half-backed feature, which is supported only by few spaces. One easy workaround to change the query server so it reads a separate file with IDs. In the newer version, I would implement something like this.

**Comment by madskunker** [comment]
Yep that is basically what I have done.  I assumed that the externId is the array offset into the vector rows.  Is that a safe assumption?

**Comment by searchivarius** [comment]
@madskunker sorry, I am a bit confused about your assumption. You need to hack/replace the set of external IDs in this place:
https://github.com/nmslib/nmslib/blob/master/query_server/cpp_client_server/QueryService_server.cpp#L109
The data set is read in a single thread, so entries are read in order.

**Comment by searchivarius** [comment]
@madskunker ohhh for the query server the assumption is safe:
https://github.com/nmslib/nmslib/blob/314f48e0f86efafe9f6ad853236603400030a0ac/similarity_search/src/space.cc#L34
