### ISSUE TITLE
What is the best Space and Method for Word Vectors

### ISSUE THREAD

**Issue by madskunker** [nmslib/nmslib#374]
Been struggling at getting even remotely good recommendation from nmslib.   I have taken the GoogleNews vectors and trimmed them down to 10 dimensions to make it easier for testing.

If I use the id  as the offset into the original vectors the words associated with these are just not even remotely close.  

I have tried several combinations but would appreciate any thoughts others have on this subject.

Couple of notes.  I  am assuming the `id` returned is the row offset.   The first item returned always lines up with my original request.  I am doing K-NN and piping in the vector values tab  delimited into the query_client.

Just feel like I am missing something really stupid to be this far off with the Nearest Neighbor words.

TIA

Jeff

**Comment by madskunker** [comment]
Additional note.  No matter what method I select the results are always the same.  Perhaps it is the format of my vectors.

`0.001129150400	-0.000896453860	0.000318527220	0.001533508300	0.001106262200	-0.001403808600	-0.000030517578	-0.000419616700	-0.000576019300	0.001075744600
0.070312500000	0.086914060000	0.087890625000	0.062500000000	0.069335940000	-0.108886720000	-0.081542970000	-0.154296880000	0.020751953000	0.131835940000
-0.011779785000	-0.047363280000	0.044677734000	0.063476560000	-0.018188477000	-0.063964844000	-0.001312255900	-0.072265625000	0.064453125000	0.086425780000
-0.015747070000	-0.028320312000	0.083496094000	0.050292970000	-0.110351560000	0.031738280000	-0.014221191000	-0.089843750000	0.117675780000	0.118164060000
0.007049560500	-0.073242190000	0.171875000000	0.022583008000	-0.132812500000	0.198242190000	0.112792970000	-0.107910156000	0.071777344000	0.020874023000
0.026733398000	-0.090820310000	0.027832031000	0.204101560000	0.006225586000	-0.090332030000	0.022583008000	-0.161132810000	0.132812500000	0.061035156000
0.168945310000	-0.062988280000	-0.000265121460	0.063476560000	0.087402344000	-0.030029297000	0.001449585000	-0.077636720000	0.199218750000	-0.001770019500
-0.172851560000	0.279296880000	0.106933594000	-0.158203120000	-0.084472656000	0.059082030000	0.040771484000	0.002548217800	0.259765620000	0.180664060000
-0.024902344000	0.021972656000	-0.035400390000	0.136718750000	0.016357422000	-0.027954102000	-0.024291992000	-0.139648440000	0.057373047000	0.062255860000
-0.009094238000	-0.044189453000	0.099609375000	-0.076171875000	-0.056640625000	0.061523438000	0.255859380000	-0.158203120000	0.016601562000	-0.096679690000`

Thoughts?

**Comment by searchivarius** [comment]
@madskunker how do you use and index data? Is it query server, Python? Query server assigns offsets for IDs (https://github.com/nmslib/nmslib/blob/314f48e0f86efafe9f6ad853236603400030a0ac/similarity_search/src/space.cc#L34), but in Python you can override this.

**Comment by madskunker** [comment]
i was using the query_server -i/--dataFile to read the file that contains the vectors.

./query_server -i ../../data/pans/GNV10Dim.txt -p 10000  -m sw-graph -s word_embed:dist=cosine

Kind of thinking this is the source of the issue.

**Comment by searchivarius** [comment]
@madskunker gosh, I completely forgot about that one. This is space actually does read the external ID on its own. It assumes ID (or  a word) to be in the first column. The following columns are actual vector elements :-) The query server can retrieve this IDs. BTW, there's no need to use sw-graph any more, please, use HNSW. Don't forget to specify indexing and retrieval params. Something like:
```
-c M=30,efConstruction=100 -ef 200
```
should give you high-accuracy. You can also ask to save the index:
```
-S <index_name>
```
Next time you can load id:
```
-L <index name>
```
Unfortunately, you would still need to load data too. Most of the current indices are only meta-indices. Again, something to fix in the following versions. :-)

**Comment by madskunker** [comment]
so you thinking I can feed it a vector file like this
`in	0.070312500000	0.086914060000	0.087890625000	0.062500000000	0.069335940000	-0.108886720000	-0.081542970000	-0.154296880000	0.020751953000	0.131835940000
for	-0.011779785000	-0.047363280000	0.044677734000	0.063476560000	-0.018188477000	-0.063964844000	-0.001312255900	-0.072265625000	0.064453125000	0.086425780000
that	-0.015747070000	-0.028320312000	0.083496094000	0.050292970000	-0.110351560000	0.031738280000	-0.014221191000	-0.089843750000	0.117675780000	0.118164060000
is	0.007049560500	-0.073242190000	0.171875000000	0.022583008000	-0.132812500000	0.198242190000	0.112792970000	-0.107910156000	0.071777344000	0.020874023000
on	0.026733398000	-0.090820310000	0.027832031000	0.204101560000	0.006225586000	-0.090332030000	0.022583008000	-0.161132810000	0.132812500000	0.061035156000
##	0.168945310000	-0.062988280000	-0.000265121460	0.063476560000	0.087402344000	-0.030029297000	0.001449585000	-0.077636720000	0.199218750000	-0.001770019500
The	-0.172851560000	0.279296880000	0.106933594000	-0.158203120000	-0.084472656000	0.059082030000	0.040771484000	0.002548217800	0.259765620000	0.180664060000
with	-0.024902344000	0.021972656000	-0.035400390000	0.136718750000	0.016357422000	-0.027954102000	-0.024291992000	-0.139648440000	0.057373047000	0.062255860000
said	-0.009094238000	-0.044189453000	0.099609375000	-0.076171875000	-0.056640625000	0.061523438000	0.255859380000	-0.158203120000	0.016601562000	-0.096679690000`

and use use -m hnsw and -s word_embed:dist=cosine 

Did I comprehend this correct?

**Comment by madskunker** [comment]
Well I tried it lol

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: 2019-02-26 22:16:07 space_vector.cc:70 (CreateObjFromStr) The # of vector elements (0) line:167  doesn't match the # of elements in previous lines. (11 )

so I got something wrong lol

**Comment by madskunker** [comment]
Well almost

Get error on running Query

2019-02-26 22:25:23 QueryService_server.cpp:305 (knnQuery) [INFO] Running a 10-NN query retExternId=0 retObj=1 QueryObjStr=sommelier	-0.122070310000	-0.306640620000	0.006134033000	0.061523438000	-0.149414060000	0.441406250000	0.047851562000	-0.250000000000	0.065917970000	0.287109380000

2019-02-26 22:25:23 space_word_embed.cc:90 (HiddenDistance) [ERROR] Check failed: obj1->datalength() == obj2->datalength()

thoughts?

**Comment by searchivarius** [comment]
@madskunker I think a query should be without a word.

**Comment by madskunker** [comment]
that is what I am trying next :)

**Comment by madskunker** [comment]
Ok well it now runs but the vectors are not good.

Finished in: 0.755 ms
id=77782 dist=5.96046e-08 externId=sommelier
id=1488177 dist=0.0279171 externId=BY_RONNIE_OH
id=2262844 dist=0.0308527 externId=2GHz_CPU
id=2890890 dist=0.0365297 externId=eGrid
id=1363950 dist=0.0398774 externId=Timmins_Porcupine_gold
id=1191996 dist=0.0405659 externId=FloEFD
id=15153 dist=0.0407208 externId=analytical
id=1207727 dist=0.0428897 externId=achat
id=1793752 dist=0.0460337 externId=ARM_Cortex_M0
id=2160714 dist=0.0466766 externId=CAM_Anywhere


this is the save google vector file that returns the below with word2vec and gensim.

{ word: 'sommeliers', dist: 0.7093979786793969 },
  { word: 'Sommelier', dist: 0.7059499346916275 },
  { word: 'master_sommelier', dist: 0.6789019235751207 },
  { word: 'winemaker', dist: 0.6654944073246285 },
  { word: 'Master_Sommelier', dist: 0.6599881301296069 },
  { word: 'chef', dist: 0.6544702963326935 },
  { word: 'mixologist', dist: 0.6497131910347582 },
  { word: 'sous_chef', dist: 0.6213829104126326 },
  { word: 'wine_connoisseur', dist: 0.6175250278743422 },
  { word: 'Mixologist', dist: 0.6103265341604011 },
  { word: 'certified_sommelier', dist: 0.6047344658261055 },
  { word: 'Daniel_Johnnes', dist: 0.6027206398831519 },
  { word: 'maitre_d', dist: 0.6016680914703937 },
  { word: 'wine_pairings', dist: 0.6000349501393438 },
  { word: 'waiter', dist: 0.5941218241349029 },
  { word: 'cellarmaster', dist: 0.5933473151635382 },
  { word: 'Executive_Chef', dist: 0.5893862883467267 },
  { word: 'pastry_chef', dist: 0.585423657634384 },
  { word: 'wines', dist: 0.5847418618737826 },
  { word: 'wine', dist: 0.5829249524463957 }

Open to suggestions

**Comment by madskunker** [comment]
Oh here is the python I used to extract the .bin file

`
from gensim.models import KeyedVectors

filename = 'GoogleNews-vectors-negative300.bin'

model = KeyedVectors.load_word2vec_format(filename, binary=True)

model.wv.save_word2vec_format('GoogleNews-vectors-negative300.txt', binary=False)

`

**Comment by searchivarius** [comment]
Is there any chance that you are running 10 dimensionsal version?

**Comment by madskunker** [comment]
I am validating the vector values also.  Thinking the extract from the .bin somehow screwed up the values.  

Stay tuned

**Comment by searchivarius** [comment]
@madskunker if you could compute the cosine similarity using numpy between vectors returned by NMSLIB, you could see if NMSLIB values make sense. Note though that NMSLIB cosine is a "distance". To get a cosine *SIMILARITY* value you need to subtract NMSLIB cosine distance from one.

**Comment by madskunker** [comment]
what I am seeing is when I pull the vector out of word2vec the vector values are different that what the python script dumped to the file.  I think this is the root of the issue. aka bad vectors = bad results

I am going to write another script tomorrow  to dump all the vectors 1 by 1 into a file and then try again.

**Comment by searchivarius** [comment]
@madskunker https://github.com/nmslib/nmslib/blob/master/data/data_conv/convert_word2vec.c

**Comment by madskunker** [comment]
Yep That did the trick.   Was bad vector file

Running a 20-NN query
Finished in: 5.222 ms
id=77782 dist=0 externId=sommelier
id=145492 dist=0.290602 externId=sommeliers
id=177400 dist=0.29405 externId=Sommelier
id=346981 dist=0.321098 externId=master_sommelier
id=40654 dist=0.334505 externId=winemaker
id=391982 dist=0.340012 externId=Master_Sommelier
id=8032 dist=0.34553 externId=chef
id=169949 dist=0.350287 externId=mixologist
id=84609 dist=0.378617 externId=sous_chef
id=239899 dist=0.382475 externId=wine_connoisseur
id=521854 dist=0.389673 externId=Mixologist
id=701100 dist=0.395265 externId=certified_sommelier
id=2409800 dist=0.397279 externId=Daniel_Johnnes
id=156278 dist=0.398332 externId=maitre_d
id=126225 dist=0.399965 externId=wine_pairings
id=25776 dist=0.405878 externId=waiter
id=1116406 dist=0.406653 externId=cellarmaster
id=61165 dist=0.414576 externId=pastry_chef
id=9198 dist=0.415258 externId=wines
id=3305 dist=0.417075 externId=wine
