### ISSUE TITLE
 -march=native passed to gcc but not supported on power

### ISSUE THREAD

**Issue by paiforsyth** [nmslib/nmslib#377]
Attempting to install via pip on power architectures yields the error below.  Problem seems to be that "-march=native" is passed to gcc, but this is not supported on these architectures.

building 'nmslib' extension
    creating build
    creating build/temp.linux-ppc64le-3.6
    creating build/temp.linux-ppc64le-3.6/nmslib
    creating build/temp.linux-ppc64le-3.6/nmslib/similarity_search
    creating build/temp.linux-ppc64le-3.6/nmslib/similarity_search/src
    creating build/temp.linux-ppc64le-3.6/nmslib/similarity_search/src/method
    creating build/temp.linux-ppc64le-3.6/nmslib/similarity_search/src/space
   
 gcc 
...
...
...
 -o build/temp.linux-ppc64le-3.6/nmslib.o -O3 -march=native -fopenmp -DVERSION_INFO="1.7.3.6" -std=c++11 -fvisibility=hidden
    gcc: error: unrecognized command line option ‘-march=native’
    error: command 'gcc' failed with exit status 1

**Comment by searchivarius** [comment]
This stuff likely won't work on non-Intel CPUs, sorry about this.
