### ISSUE TITLE
Stuck to install in SageMaker

### ISSUE THREAD

**Issue by rpoli40** [nmslib/nmslib#378]
Tried to install on SageMaker in conda_python3 and conda_python2 and got the same error:
Collecting nmslib
  Using cached https://files.pythonhosted.org/packages/e1/95/1f7c90d682b79398c5ee3f9296be8d2640fa41de24226bcf5473c801ada6/nmslib-1.7.3.6.tar.gz
Requirement already satisfied: pybind11>=2.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from nmslib) (2.2.4)
Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from nmslib) (1.14.5)
Building wheels for collected packages: nmslib
  Building wheel for nmslib (setup.py) ... error
  Complete output from command /home/ec2-user/anaconda3/envs/python3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1m6_x20r/nmslib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-mxhl99fh --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  creating tmp
  gcc -pthread -B /home/ec2-user/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -c /tmp/tmp6sp3b1uu.cpp -o tmp/tmp6sp3b1uu.o -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  cc1plus: error: unrecognized command line option ‘-std=c++14’
  gcc -pthread -B /home/ec2-user/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -c /tmp/tmpu5o4lkw7.cpp -o tmp/tmpu5o4lkw7.o -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  gcc -pthread -B /home/ec2-user/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -c /tmp/tmpajwgyrb4.cpp -o tmp/tmpajwgyrb4.o -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  building 'nmslib' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/nmslib
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src/method
  creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src/space
  gcc -pthread -B /home/ec2-user/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./nmslib/similarity_search/include -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -I/home/ec2-user/.local/include/python3.6m -I/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/numpy/core/include -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -c nmslib.cc -o build/temp.linux-x86_64-3.6/nmslib.o -O3 -march=native -fopenmp -DVERSION_INFO="1.7.3.6" -std=c++11 -fvisibility=hidden
  cc1plus: error: unrecognized command line option ‘-mno-sha’
  cc1plus: error: unrecognized command line option ‘-mno-sgx’
  cc1plus: error: unrecognized command line option ‘-mno-avx512f’
  cc1plus: error: unrecognized command line option ‘-mno-avx512er’
  cc1plus: error: unrecognized command line option ‘-mno-avx512cd’
  cc1plus: error: unrecognized command line option ‘-mno-avx512pf’
  cc1plus: error: unrecognized command line option ‘-mno-prefetchwt1’
  cc1plus: error: unrecognized command line option ‘-mno-clflushopt’
  cc1plus: error: unrecognized command line option ‘-mno-xsavec’
  cc1plus: error: unrecognized command line option ‘-mno-xsaves’
  cc1plus: error: unrecognized command line option ‘-mno-avx512dq’
  cc1plus: error: unrecognized command line option ‘-mno-avx512bw’
  cc1plus: error: unrecognized command line option ‘-mno-avx512vl’
  cc1plus: error: unrecognized command line option ‘-mno-avx512ifma’
  cc1plus: error: unrecognized command line option ‘-mno-avx512vbmi’
  cc1plus: error: unrecognized command line option ‘-mno-avx5124fmaps’
  cc1plus: error: unrecognized command line option ‘-mno-avx5124vnniw’
  cc1plus: error: unrecognized command line option ‘-mno-clwb’
  cc1plus: error: unrecognized command line option ‘-mno-mwaitx’
  cc1plus: error: unrecognized command line option ‘-mno-clzero’
  cc1plus: error: unrecognized command line option ‘-mno-rdpid’
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  nmslib.cc:1:0: error: bad value (broadwell) for -march= switch
   /**
   ^
  nmslib.cc:1:0: error: bad value (broadwell) for -mtune= switch
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for nmslib
  Running setup.py clean for nmslib
Failed to build nmslib
Installing collected packages: nmslib
  Running setup.py install for nmslib ... error
    Complete output from command /home/ec2-user/anaconda3/envs/python3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1m6_x20r/nmslib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-mkwvdgp2/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    gcc -pthread -B /home/ec2-user/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -c /tmp/tmpw48c_fmt.cpp -o tmp/tmpw48c_fmt.o -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    cc1plus: error: unrecognized command line option ‘-std=c++14’
    gcc -pthread -B /home/ec2-user/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -c /tmp/tmpzylyfpl6.cpp -o tmp/tmpzylyfpl6.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -B /home/ec2-user/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -c /tmp/tmpl44v01df.cpp -o tmp/tmpl44v01df.o -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    building 'nmslib' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/nmslib
    creating build/temp.linux-x86_64-3.6/nmslib/similarity_search
    creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src
    creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src/method
    creating build/temp.linux-x86_64-3.6/nmslib/similarity_search/src/space
    gcc -pthread -B /home/ec2-user/anaconda3/envs/python3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./nmslib/similarity_search/include -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -I/home/ec2-user/.local/include/python3.6m -I/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/numpy/core/include -I/home/ec2-user/anaconda3/envs/python3/include/python3.6m -c nmslib.cc -o build/temp.linux-x86_64-3.6/nmslib.o -O3 -march=native -fopenmp -DVERSION_INFO="1.7.3.6" -std=c++11 -fvisibility=hidden
    cc1plus: error: unrecognized command line option ‘-mno-sha’
    cc1plus: error: unrecognized command line option ‘-mno-sgx’
    cc1plus: error: unrecognized command line option ‘-mno-avx512f’
    cc1plus: error: unrecognized command line option ‘-mno-avx512er’
    cc1plus: error: unrecognized command line option ‘-mno-avx512cd’
    cc1plus: error: unrecognized command line option ‘-mno-avx512pf’
    cc1plus: error: unrecognized command line option ‘-mno-prefetchwt1’
    cc1plus: error: unrecognized command line option ‘-mno-clflushopt’
    cc1plus: error: unrecognized command line option ‘-mno-xsavec’
    cc1plus: error: unrecognized command line option ‘-mno-xsaves’
    cc1plus: error: unrecognized command line option ‘-mno-avx512dq’
    cc1plus: error: unrecognized command line option ‘-mno-avx512bw’
    cc1plus: error: unrecognized command line option ‘-mno-avx512vl’
    cc1plus: error: unrecognized command line option ‘-mno-avx512ifma’
    cc1plus: error: unrecognized command line option ‘-mno-avx512vbmi’
    cc1plus: error: unrecognized command line option ‘-mno-avx5124fmaps’
    cc1plus: error: unrecognized command line option ‘-mno-avx5124vnniw’
    cc1plus: error: unrecognized command line option ‘-mno-clwb’
    cc1plus: error: unrecognized command line option ‘-mno-mwaitx’
    cc1plus: error: unrecognized command line option ‘-mno-clzero’
    cc1plus: error: unrecognized command line option ‘-mno-rdpid’
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    nmslib.cc:1:0: error: bad value (broadwell) for -march= switch
     /**
     ^
    nmslib.cc:1:0: error: bad value (broadwell) for -mtune= switch
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/ec2-user/anaconda3/envs/python3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1m6_x20r/nmslib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-mkwvdgp2/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-1m6_x20r/nmslib/

**Comment by searchivarius** [comment]
I am not sure what's exactly is in the Conda distribution, but my best guess is that you need upgrade the GCC compiler.

**Comment by rpoli40** [comment]
We have g++ 4.8 and gcc 7.2 and I’m getting the error anyway

**Comment by searchivarius** [comment]
g++4.8 is a bit old. The version of gcc is not relevant.

**Comment by rpoli40** [comment]
Your requirements say g++ 4.7.

**Comment by searchivarius** [comment]
@rpoli40 how exactly do you install nmslib? I suspect that these flags are added by the conda distribution. If this is true, please, note that I don't maintain the conda distribution.

**Comment by rpoli40** [comment]
That’s is true

**Comment by searchivarius** [comment]
@rpoli40 ok, conda distribution is different. If you want to install a pip-ed version of NMSLIB, you can use pip from the conda installation location. The pip distribution doesn't use this these flags, so I guess it is ok with the old compiler.
Thanks!

**Comment by rpoli40** [comment]
Sorry didn’t get what you mean.

**Comment by searchivarius** [comment]
@rpoli40 there are conda and pip package managers. They use *DIFFERENT* versions of the package. You are trying to install the conda version. I don't maintain this version and have no control over it. The basic installation package doesn't have these flags that cause your errors. Try to to install the pip version (you can do it from conda too), e.g., 
```
which python
/anaconda3/bin/python
/anaconda3/bin/pip install ....
```

**Comment by rpoli40** [comment]
We are installing the pip version

**Comment by rpoli40** [comment]
Leonid,
On a separate note since i currently can’t experiment with the library,
once I load my data  with nmslib can I store it somehow in an optimized way
to allow an access to various calculations (similarity) or I need to have
it loaded into memory all the time and once I exit my code I need to load
everything again from the beginning.
Thank you

**Comment by searchivarius** [comment]
@rpoli40 if you don't use getDistance or getDataPoint, it should be possible.

**Comment by rpoli40** [comment]
Leonid,
Will I be able to use index.knnQuery(query, k=10) after storing indexes?
In general what would you recommend doing if I have matrix of vectors with
following dimensions 180000X1024 which is about 700G of data (stored as
json) to create indexes for. I want to be able giving a query to retrieve
10 most similar to that query of interest. I was thinking of using
saveIndex and then load index whenever there is a need and use
index.knnQuery(query, k=10). Do you have any other
recommendations/suggestions?
Thank you for your help,
Regina

**Comment by searchivarius** [comment]
Hi Regina,
sorry for the delay. I think, if it's just retrieval with L2/cosine, it should work with HNSW and optimized index (which is built by default for L2/cosine). But one needs to double-check. There might also be some progress in adding generic data saving/retrieving functionality (whenever the index is saved), but it would take time: https://github.com/nmslib/nmslib/issues/356#issuecomment-476739319

**Comment by alohia** [comment]
For anyone still facing this problem, the following commands worked for me and allowed me to install nmslib on amazon linux on EC2

```
sudo yum install gcc64
sudo ln -s /usr/lib/gcc/x86_64-amazon-linux/6.4.1/libgomp.spec /usr/lib64/libgomp.spec
sudo ln -s /usr/lib/gcc/x86_64-amazon-linux/6.4.1/libgomp.a /usr/lib64/libgomp.a
sudo ln -s /usr/lib64/libgomp.so.1.0.0 /usr/lib64/libgomp.so
pip install nmslib --no-cache-dir
```
