### ISSUE TITLE
nmslib as a AWS Lambda Layer

### ISSUE THREAD

**Issue by Rafis1988** [nmslib/nmslib#379]
Hi. Maybe it's wrong place to ask, but how do I upload nmslib as a aws lambda layer? I've tried to zip virtualenv's site-packages with nmslib installed - no luck. I've tried to use lambci/lambda - got error: command 'gcc' failed with exit status 1. I have no problem with other python packages,for example I've uploaded numpy, pandas without any problem. What should I do?

**Comment by Rafis1988** [comment]
Finally I was able to wheel it inside lambci/lambda and upload it to aws lambda layes. It works.

**Comment by searchivarius** [comment]
Good to know thanks!
