### ISSUE TITLE
Guidance on the delaunay_type parametre

### ISSUE THREAD

**Issue by oulenz** [nmslib/nmslib#381]
I have been testing the hnsw method as part of a nearest neighbour-like machine learning model, with good results, thank you for providing this implementation.

I was hoping you could give some guidance on the `delaunay_type` parametre.

The [parametre guide](https://github.com/nmslib/nmslib/blob/master/python_bindings/parameters.md) mentions values 0 and 1, which presumably correspond to the two alternatives mentioned in the article. However, the code also accepts values 2 and 3. And while the guide says 1 is the default, the actual default seems to be 2. But the code has [a warning](https://github.com/nmslib/nmslib/blob/3068df834e16f26b72046dcbc59b4b44d8a832d3/similarity_search/include/method/hnsw.h#L116) which says 2 performs worse than 1 and does not produce correct results in combination with multithreading:

> Experimental method for selection of neighbors based on local search.
> However is peforms worse than the previous method
> Note that it works correctly only in a single thread!!!

However, multithreading is also on by default, so this seems unfortunate.

* What (if any) is the advantage of `delaunay_type` 2 and 3? Could you explain the idea behind them?
* If there are any advantages, how problematic is using `delaunay_type` 2 (and 3) in combination with multithreading?

**Comment by searchivarius** [comment]
@oulenz thank for pointing this out. Indeed, the default is two and it performs usually a bit better than 1 or 3.  I don't think type=2 is thread-unsafe. I need to dig a bit deeper to understand why it's considered "non-accurate". Treat this value as a hyper-parameter (and the default seems to be working quite well).

**Comment by oulenz** [comment]
Thanks for your reassurances on using `delaunay_type = 2` with multiple threads. It would be good to have an explanation for that code comment.

I've had another look at the code, and it seems to me now that values 1, 2 and 3 all correspond to Algorithm 4 of the article, with different parametre values:

1: `extendCandidates = False` and `keepPrunedConnections = True`
2: `extendCandidates = False` and `keepPrunedConnections = False`
3: `extendCandidates = True` and `keepPrunedConnections = True`

**Comment by yurymalkov** [comment]
Hi @oulenz,

The mentioned comment is wrong, it should be removed. At some point there was a different heuristic, which relied on traversing the graph and, thus, had this thread-safe issues. 

All heuristics are now thread-safe, the default type should be 2.

The heuristics are as follows:
1: `extendCandidates = False` and `keepPrunedConnections = True`
2: `extendCandidates = False` and `keepPrunedConnections = False`
3: `extendCandidates = True` and reweighting scheme that plays with the priority of the elements. AFAIR It didn't help much, so it never used.

Also a proper way(more fast) to set the `extendCandidates` is by a flag: https://github.com/nmslib/nmslib/blob/master/similarity_search/src/method/hnsw.cc#L52

**Comment by oulenz** [comment]
Thank you for replying so quickly and clearing up this matter!

> Also a proper way(more fast) to set the `extendCandidates` is by a flag: https://github.com/nmslib/nmslib/blob/master/similarity_search/src/method/hnsw.cc#L52

But there is no parametre that changes this flag, is there?

**Comment by yurymalkov** [comment]
@oulenz Yes, unfortunately, it is hardcoded... 
It seems that the most of the datasets are not clustered, so `extendCandidates = True` usually does not help (only slows down the construction). 
However, there is a huge difference in search perfomance for the case of clustered or extremely low dimensional datasets.

**Comment by oulenz** [comment]
Ok, I'm happy to use the default if that typically produces optimal results, it's one fewer parametre to tune. Thanks again!

**Comment by searchivarius** [comment]
Let me re-open this, I will update the code docs. Thanks everybody!

**Comment by searchivarius** [comment]
I have updated docs, thanks!
https://github.com/nmslib/nmslib/blob/master/manual/methods.md
I don't go into details of each specific pruning algorithms though.
