### ISSUE TITLE
Read an index in Java/Scala

### ISSUE THREAD

**Issue by Saftophobia** [nmslib/nmslib#382]
I would like to read an index (pre-indexed in python) via Scala, to be used for retrieval in Play app. I went through the query_server but I'm still not sure how this can be integrated in a web app like Play. 

Any input is appreciated. Thanks.

**Comment by searchivarius** [comment]
What is Play?

**Comment by Saftophobia** [comment]
It's a web application [framework](https://github.com/playframework/playframework) for java/scala, I may ask this differently please. 

When I start a cpp server via thrift, I assume it starts indexing. Is there a way I can start a server that reads an index that was created earlier? In case this doesn't exist, I would like to build an app in java/scala that reads an already created index and queries it. is it possible? any guidelines would be great.

Thank you

**Comment by searchivarius** [comment]
@Saftophobia if you do
``` 
./query_server ... -c <index parameters> -t <query parameter> -S <index name>
```
then it will create and save the index.
Next time, you can do simply:
``` 
./query_server ... -c <index parameters> -t <query parameter> -L <index name>
```
**Please, use the query server (but not the other code) from this branch:**
https://github.com/nmslib/nmslib/tree/nmslib4a_postdoc
Can't use the older code with the recent versions of Apache Thrift.
