### ISSUE TITLE
Custom metric ? 

### ISSUE THREAD

**Issue by Neoanarika** [nmslib/nmslib#383]
Hi is it possible to learn your own distance metric first and then load into nmslib as a custom metric ?

**Comment by searchivarius** [comment]
Hi @Neoanarika not easily, but possible. Also, how do you learn your metric? Often, the metric is learned as bi-linear form with symmetric PSD matrix. If this is a case, there is a transformation of the data, where similarity is just L2.

**Comment by Neoanarika** [comment]
Ahhh ok thanks. I was thinking more on the lines of using a siamese network to learn a metric and loading the learnt metric into nmslib.

**Comment by searchivarius** [comment]
@Neoanarika as far as I remember, in the end it does the cosine between two representations. You can (with a bit of effort) to implement this functionality, but 
1) It needs to be all C++
2) It is going to be much more efficient to run the encoder parts before feeding vectors into the library.
