### ISSUE TITLE
What is the plan(timeline) to implement AddBatch, DeleteBatch function?

### ISSUE THREAD

**Issue by vamshin** [nmslib/nmslib#384]
Hi  @Neoanarika,

I see the functions **AddBatch**, **DeleteBatch** are not implemented.  These functions seems to be useful in some cases.  What is the timeline or plan for the implementation of these functions? 

https://github.com/nmslib/nmslib/blob/master/similarity_search/include/index.h#L88
https://github.com/nmslib/nmslib/blob/master/similarity_search/include/index.h#L93

**Comment by searchivarius** [comment]
Hi @vamshin I am working on this, I cannot give the timeline yet. This question is more appropriate for the gitter chat.
