### ISSUE TITLE
What is the best way to merge 2 hnsw indices?

### ISSUE THREAD

**Issue by vamshin** [nmslib/nmslib#385]
Hi   @Neoanarika ,

I have 2 indices hnsw1(with 100 vectors), hnsw2(with 100 vectors). Currently i take the union of vectors from both the indices(200 vectors) and create a new index hnsw3.  

Not sure if this is better approach. I am looking some thing like, Instead of building hnsw3 from scratch, is there a way i can merge hnsw1 and hnsw2 in place?

Also what do you think will be better in terms of time complexity?
Building from scratch by taking union and creating new index **OR** merging approach.

Thanks in advance

**Comment by searchivarius** [comment]
Hi @vamshin currently there's no way to do this, but there may be a way in the future. It's on the internal feature list already.
