### ISSUE TITLE
Calculate efficiency in python

### ISSUE THREAD

**Issue by bagavi** [nmslib/nmslib#387]
I am running the following code in python
```
k = 10
index = nmslib.init(method='hnsw', space='l2')
index.addDataPointBatch(data)
index.createIndex({'post': 2}, print_progress=True)
neighbours = index.knnQueryBatch(data, k=k, num_threads=4)
```
The `data` is a 1000x12000 array (1000 1200 dimensional images). How shall I calculate the `ImprDistComp` - the improvement in distance computation (over brute method) -- inside python environment?

Also, where can I set `efConstruction` and `efSearch` parameters of `hnsw` method?

**Comment by searchivarius** [comment]
Hi @bagavi this is unfortunately not a visible metric.

**Comment by searchivarius** [comment]
Sorry, I missed your another question, for setting the parameters, please, see the notebook:
https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_optim.ipynb
I don't think I am going to support the improvement in the number of distance computation in Python, this is not trivial.
