### ISSUE TITLE
hnsw index file size

### ISSUE THREAD

**Issue by vamshi1252** [nmslib/nmslib#388]
Hi @Neoanarika ,

I am trying to estimate the size of the hnsw index saved on file system with respect to the embedding size. 
I am seeing strange behavior. 

For vector with 2 dimensions it takes 228 Bytes
For vector with 100 dimensions it takes 228 Bytes
For vector with 500 dimensions it still takes 228 Bytes

Sorry i have no idea on how the graph is serialized and stored.  Can you please help me understand why this could happen?

**Comment by yurymalkov** [comment]
Hi @vamshi1252,
Probably, you are storing the graph before adding any elements.

**Comment by searchivarius** [comment]
I am closing this, because these questions are better address through Gitter: 
https://gitter.im/nmslib/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
Who's https://github.com/Neoanarika BTW?

**Comment by vamshi1252** [comment]
@yurimalkov. No I was able to query the index and get the results. Checked the size of the index after getting results as well. So I am pretty sure graph is serialized with elements
