### ISSUE TITLE
Fork safety of Python objects for multiprocessing

### ISSUE THREAD

**Issue by keunhong** [nmslib/nmslib#389]
Hello,

I've been searching and couldn't quite find an answer for this so I'll ask here. Are the objects returned by `nmslib.init` and `ann.createIndex` fork safe i.e. if I pass them to a `multiprocessing.Process` as an argument will it work as indented?

I am using nmslib inside a dataloader for PyTorch and am encountering a deadlock in some cases. I was wonder if it is possible that this is the cause.

Thanks.

**Comment by searchivarius** [comment]
I don't think there's something that can cause a deadlock on NMSLIB side. Fork simply creates the copy of the process with the identical memory layout IMHO. However, I am not sure about Python or Python bindings. How exactly do you fork?

**Comment by keunhong** [comment]
I've found the source of my bug and nmslib had nothing to do with it :) Sorry for the noise. It seems to handle multiprocessing fine.

**Comment by searchivarius** [comment]
@keunhong no problem

**Comment by linminhtoo** [comment]
> I've found the source of my bug and nmslib had nothing to do with it :) Sorry for the noise. It seems to handle multiprocessing fine.

Hello, I am working with PyTorch currently and want to do multi-processing on my dataloader which loads a saved nmslib index and does knnQueryBatch every iteration. Unfortunately, when I set num_workers = 4, I get `TypeError: can't pickle nmslib.dist.FloatIndex objects 
` as shown below. I will try to come up with a minimum reproducible code ASAP, but in summary I am doing this: 
```
self.clusterindex = nmslib.init(method='hnsw', space='cosinesimil_sparse', 
                                data_type=nmslib.DataType.SPARSE_VECTOR)
self.clusterindex.loadIndex(self.trainargs['cluster_path'], load_data=True)
if 'query_params' in self.trainargs.keys():
        self.clusterindex.setQueryTimeParams(self.trainargs['query_params'])
```

followed by calling 
```
self.clusterindex.knnQueryBatch(rct_prod_sparse, 
                                                                                k = max(self.num_neg_prod, self.num_neg_rct) + 1, 
                                                                                num_threads = 4) # or self.trainargs['num_threads']
```
However, from your comments, multi-processing seems to work fine with nmslib. Do you mind sharing about what was the bug in your code that had nothing to do with nmslib? 

Full traceback: 
```
Traceback (most recent call last):
  File "c:/Users/Lin Min Htoo/Desktop/OFYP/work/trainEBM.py", line 71, in <module>
    trainEBM()
  File "c:/Users/Lin Min Htoo/Desktop/OFYP/work/trainEBM.py", line 64, in trainEBM
    experiment.train()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\Lin Min Htoo\Desktop\OFYP\work\experiment.py", line 178, in train
  File "C:\anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    for batch in tqdm(self.train_loader):
      File "C:\anaconda3\lib\site-packages\tqdm\std.py", line 1107, in __iter__
exitcode = _main(fd)
      File "C:\anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
for obj in iterable:
      File "C:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
self = reduction.pickle.load(from_parent)
    EOFErrorreturn _MultiProcessingDataLoaderIter(self): 
Ran out of input  File "C:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__

    w.start()
  File "C:\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
  File "C:\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle nmslib.dist.FloatIndex objects 
```

**Comment by searchivarius** [comment]
@linminhtoo NMSLIB objects **CANNOT** be copied across processes. Sorry if said something that caused confusion. There's simply no support for this. What NMSLIB does is: it uses multiple threads internally. If I know a bit more how data loader works, I may suggest some workaround.

**Comment by linminhtoo** [comment]
@searchivarius thanks for your reply! I have familiarised myself more with PyTorch's multi-processing tricks and I have found a way to overcome this issue. Since NMSLIB objects cannot be pickled and copied across processes, I simply load a separate NMSLIB search index on each worker (= subprocess) that I am using for my training. 

For the benefit of anyone else who might run into this problem, here is a sample in code:

Define a custom worker_init_fn that will be passed into PyTorch's dataloader. This function is used to initialise each new worker everytime they are spawned. Inside my custom dataset, I define a class attribute custom_dataset.clusterindex, which is initialised to be None. When my worker is spawned, it receives a copy of my custom_dataset, and this worker_init_fn loads a new copy of the search index & its data from cluster_path. 

```
def _worker_init_fn_nmslib_(worker_id):
    torch_seed = torch.initial_seed()
    np_seed = torch_seed % (2**31 - 1)
    random.seed(torch_seed)
    np.random.seed(np_seed)

    worker_info = get_worker_info() 
    dataset = worker_info.dataset 
    if dataset.clusterindex is None:
        dataset.clusterindex = nmslib.init(method='hnsw', space='cosinesimil_sparse', 
                            data_type=nmslib.DataType.SPARSE_VECTOR)
        dataset.clusterindex.loadIndex(dataset.trainargs['cluster_path'], load_data=True)
        if 'query_params' in dataset.trainargs.keys():
            dataset.clusterindex.setQueryTimeParams(dataset.trainargs['query_params'])
```

And then this is how we use it when instantiating our PyTorch DataLoader! 
```
train_dataset = ReactionDataset(self.trainargs['base_path'], 'train', 
                                        trainargs=self.trainargs, mode=mode)
self.train_loader = DataLoader(train_dataset, self.trainargs['batch_size'], 
                                       num_workers=self.trainargs['num_workers'], 
                                       worker_init_fn=_worker_init_fn_nmslib_,
                                        shuffle=True, pin_memory=self.pin_memory)
``` 

Cheers.

**Comment by searchivarius** [comment]
Hi @linminhtoo thank you! I should have mentioned this option. It was kinda self-obvious to me, but I guess I didn't recommend it in the first place, b/c loading index in each process separately is somewhat suboptimal.
