### ISSUE TITLE
all the type of space

### ISSUE THREAD

**Issue by UpCoder** [nmslib/nmslib#390]
Hi, I try to figure out the all types of space, such as cosinesimil.
is there any another space? such as l2 or ip?

Thanks

**Comment by earboxer** [comment]
It would be nice if all of the space choices were all next to eachother. [`l2` and `cosinesimil` are the only ones that can be saved and re-loaded right now](https://github.com/nmslib/nmslib/issues/356#issuecomment-439080366), but there are many other choices that should be able to be used.

The following list comes from grepping through the code (`grep -Rns "#define SPACE_"`)

*  SPACE_DUMMY              "dummy"
*  SPACE_L     "lp"
*  SPACE_LINF  "linf"
*  SPACE_L1    "l1"
*  SPACE_L2    "l2"
*  SPACE_L2SQR_SIFT    "l2sqr_sift"
*  SPACE_COSINE_SIMILARITY  "cosinesimil"
*  SPACE_ANGULAR_DISTANCE   "angulardist"
*  SPACE_NEGATIVE_SCALAR    "negdotprod"
*  SPACE_SPARSE_JACCARD              "jaccard_sparse"
*  SPACE_WORD_EMBED              "word_embed"
*  SPACE_WORD_EMBED_DIST_L2      "l2"
*  SPACE_WORD_EMBED_DIST_COSINE  "cosine"
*  SPACE_JS_DIV_SLOW         "jsdivslow"
*  SPACE_JS_DIV_FAST         "jsdivfast"
*  SPACE_JS_DIV_FAST_APPROX  "jsdivfastapprox"
*  SPACE_JS_METR_SLOW         "jsmetrslow"
*  SPACE_JS_METR_FAST         "jsmetrfast"
*  SPACE_JS_METR_FAST_APPROX  "jsmetrfastapprox"
*  SPACE_SPARSE_COSINE_SIMILARITY_FAST  "cosinesimil_sparse_fast"
*  SPACE_SPARSE_ANGULAR_DISTANCE_FAST   "angulardist_sparse_fast"
*  SPACE_SPARSE_NEGATIVE_SCALAR_FAST             "negdotprod_sparse_fast"
*  SPACE_SPARSE_QUERY_NORM_NEGATIVE_SCALAR_FAST  "querynorm_negdotprod_sparse_fast"
*  SPACE_BIT_HAMMING "bit_hamming"
*  SPACE_KLDIV_FAST                        "kldivfast"
*  SPACE_KLDIV_FAST_RIGHT_QUERY            "kldivfastrq" 
*  SPACE_KLDIVGEN_FAST                     "kldivgenfast"
*  SPACE_KLDIVGEN_FAST_RIGHT_QUERY         "kldivgenfastrq" 
*  SPACE_KLDIVGEN_SLOW                     "kldivgenslow"
*  SPACE_ITAKURASAITO_FAST                 "itakurasaitofast"
*  SPACE_ITAKURASAITO_FAST_RIGHT_QUERY     "itakurasaitofastrq" 
*  SPACE_ITAKURASAITO_SLOW                 "itakurasaitoslow"
*  SPACE_SQFD_HEURISTIC_FUNC "sqfd_heuristic_func"
*  SPACE_SQFD_MINUS_FUNC     "sqfd_minus_func"
*  SPACE_SQFD_GAUSSIAN_FUNC  "sqfd_gaussian_func"
*  SPACE_SPARSE_L     "lp_sparse"
*  SPACE_SPARSE_LINF  "linf_sparse"
*  SPACE_SPARSE_L1    "l1_sparse"
*  SPACE_SPARSE_L2    "l2_sparse"
*  SPACE_RENYI_DIVERG_SLOW "renyidiv_slow"
*  SPACE_RENYI_DIVERG_FAST "renyidiv_fast"
*  SPACE_AB_DIVERG_SLOW     "abdiv_slow"
*  SPACE_AB_DIVERG_FAST     "abdiv_fast"
*  SPACE_LEVENSHTEIN       "leven"
*  SPACE_LEVENSHTEIN_NORM  "normleven"
*  SPACE_SPARSE_COSINE_SIMILARITY          "cosinesimil_sparse"
*  SPACE_SPARSE_ANGULAR_DISTANCE           "angulardist_sparse"
*  SPACE_SPARSE_NEGATIVE_SCALAR            "negdotprod_sparse"
*  SPACE_SPARSE_QUERY_NORM_NEGATIVE_SCALAR "querynorm_negdotprod_sparse"

**Comment by searchivarius** [comment]
There's a description of spaces in the manual, which I currently update (should be done quite soon), I will also create a table of spaces online soon.

**Comment by searchivarius** [comment]
Please, see the updated docs. These are for the latest version 1.8:
https://github.com/nmslib/nmslib/tree/master/manual
Thanks!
