### ISSUE TITLE
Serving multiple indices

### ISSUE THREAD

**Issue by safwank** [nmslib/nmslib#391]
Sorry if this has been asked before, but is there documentation on how to serve multiple indices in the query server?

**Comment by searchivarius** [comment]
@safwank Sorry, it's not supported, you need to have a sepearate server on the separate port for this. I don't think I am going to support multiple indices in the near future. Clearly, this can be done, but not in the basic library version.

**Comment by safwank** [comment]
@searchivarius No worries, just wondering if it's possible. We'll just have to figure out how to work around it. Thanks!

**Comment by searchivarius** [comment]
Hi @safwank BTW, I have made a simple fix that allows to serialize/load data more efficiently. It is in the latest release.
