### ISSUE TITLE
Faster and more accurate when query data is included in the "train" and "add" stage

### ISSUE THREAD

**Issue by Zheweiqiu** [nmslib/nmslib#392]
I tried the following two settings:
1. Feed all data into the "train" and "add" stage and "query" data is randomly sampled from the whole data set, i.e. the query data is already included when building the graph.
2. Feed only partial data into the "train" and "add" stage, and during the "query" data is sample from the rest data,  i.e. the query data is excluded from the graph.
It turns out that 1 outperforms 2 in terms of query speed and accuracy, it that the normal case?
No sure if I make myself understood, let me know if anywhere confuses you and any help will be appreciate.

**Comment by searchivarius** [comment]
If you include queries into the graph this can boost performance. But in a normal setting queries are not known in advance.
