### ISSUE TITLE
Broken link to parameters tuning guide

### ISSUE THREAD

**Issue by AndreyGurevich** [nmslib/nmslib#393]
In file https://github.com/nmslib/nmslib/tree/master/python_bindings there is a link 
https://github.com/nmslib/nmslib/blob/master/python_bindings/parameters.md, but `parameters.md` is missing

**Comment by searchivarius** [comment]
Fixed, thanks a lot for noticing. Please, note that this documentation is for version 1.8. I have been just upgrading to a new version.

**Comment by AndreyGurevich** [comment]
Thank you
Yes, i've noticed that documentation is for 1.8, because parameter `save_data` at `saveIndex` promised to be very useful for me, but it's from 1.8.
Waiting for new release :)

**Comment by searchivarius** [comment]
@AndreyGurevich it's kinda released (on PiPy). It just haven't tagged it yet.
