### ISSUE TITLE
Throwing Error while installing nmslib package in windows 10 machine using anaconda jupytr notebook.

### ISSUE THREAD

**Issue by madhavi1102** [nmslib/nmslib#394]
Unable to install nmslib package in windows 10 machine. Earlier I faced issue of MS visual C++ build tools while installing,for that I had installed the Visual C++ build tools. Again after rerunning the pip install nmslib command in anaconda jupyter ,below error is thrown

  **.\nmslib\similarity_search\src\method\pivot_neighb_invindx.cc(296): note: while compiling class template member function 'void similarity::PivotNeighbInvertedIndex<float>::SetQueryTimeParams(const similarity::AnyParams &)'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2*

Can you check this issue. I am not able to proceed further.

**Comment by searchivarius** [comment]
Hi @madhavi1102 are these all the errors that you see? Could you run
```
ip install pylint --log <some log file name>
```
to record the complete file log?
Thanks!

**Comment by searchivarius** [comment]
BTW, @madhavi1102 , which Windows version do you use? 32 bit or 64 bit?

**Comment by searchivarius** [comment]
I am merging it with #399.
