### ISSUE TITLE
offline installation

### ISSUE THREAD

**Issue by Zheweiqiu** [nmslib/nmslib#397]
Hello,
Is there any way to install nmslib offline for python, i.e., pack everything in a package and we can do 'import nmslib' by adding the package to PYTHONPATH without installing it via pip?
Thanks in advance!

**Comment by searchivarius** [comment]
Hi @Zheweiqiu you can 
1. build the library locally from the `similarity_search` folder
2. create a Python egg in the `python_bindings` directory by then running `python setup.py` build.
You can then add the **full* path of the egg to PYTHONPATH.

**Comment by Zheweiqiu** [comment]
> Hi @Zheweiqiu you can
> 
> 1. build the library locally from the `similarity_search` folder
> 2. create a Python egg in the `python_bindings` directory by then running `python setup.py` build.
>    You can then add the **full** path of the egg to PYTHONPATH, e.g.
>    `PYTHONPATH=/Users/leo/tmp/nmslib-1.8-py3.6-macosx-10.7-x86_64.egg`

Are these two steps two ways of building nmslib library locally or twos steps of one approach? And for the second part, how to 'create a Python egg in the python_bindings directory'? These question may seem stupid since I am a beginner.
Thank for any help!

**Comment by searchivarius** [comment]
Hi, these are basically the setups. It's actually easier to go directly to the python_bindings folder and type:
```
python setup.py build
```
If I understand correctly, the egg in the the ``build/lib...`` subdirectory. You can google for additional info. NMSLIB is not different in this respect compared to other python libraries. Once you build the egg, you can use it without installing. I did try this yesterday and it worked.
