### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by 1653091** [nmslib/nmslib#399]
I am using pip 3.7.3 x64 on WIndows.
![image](https://user-images.githubusercontent.com/46515998/59814384-559bb000-933f-11e9-97ad-9ad74d5c743c.png)
I already have pyblind11 and numpy.
Thanks a lot.

**Comment by searchivarius** [comment]
Seems like a similar issue with #394: what is your MS Visual Studio version?
Thank you!

**Comment by 1653091** [comment]
I'm using MS Visual Studio 19

**Comment by 1653091** [comment]
The error occures in file pivot_neighb_invindx.cc and it about _mm_prefetch function not found. So I try changing the header of  pivot_neighb_invindx.cc like this. It works
![image](https://user-images.githubusercontent.com/46515998/59910653-87467100-943c-11e9-95c5-3ce12e2c3311.png)
Anyone who have the same error like me can try it.

**Comment by searchivarius** [comment]
Many thanks, I would have to patch & test!

**Comment by LouisdeBruijn** [comment]
any update on this? I am getting an error aswell, but no simple fix for it.

**Comment by barney54321** [comment]
I've also come across this issue on multiple computers, all running Windows 10 and Python 3.7.4
Here's the error from my pip log:
[err.txt](https://github.com/nmslib/nmslib/files/3480622/err.txt)

**Comment by searchivarius** [comment]
@barney54321 I hope to look into this quite soon (likely after this Wed).

**Comment by chandansharma02** [comment]
Hi Leonid Boytsov..........Any luck with above?

**Comment by searchivarius** [comment]
We should be soon done with this. We will also be able to provide binaries, albeit they might be a bit slower.

**Comment by chandansharma02** [comment]
Thank you looking forward for either. I am using windows 10. In case of binaries, speed is less of an issues as of now.

**Comment by searchivarius** [comment]
@chandansharma02 ok, sure, should be done with this today.

**Comment by searchivarius** [comment]
Hi @chandansharma02 could you check if the current binary version works for you? Thank you!

**Comment by chandansharma02** [comment]
Thank you again. Now I am able to pip install it and able to import the library. Will run the complete code and hope all works.

**Comment by searchivarius** [comment]
Nice, thank you for confirming @chandansharma02

**Comment by snosrap** [comment]
I'm also getting this error installing on a windows 10 machine, python 3.8, pip version 20.0.2

```
    .\similarity_search\src\method\pivot_neighb_invindx.cc(651): error C3861: '_mm_prefetch': identifier not found
    .\similarity_search\src\method\pivot_neighb_invindx.cc(652): error C2065: '_MM_HINT_T0': undeclared identifier
    .\similarity_search\src\method\pivot_neighb_invindx.cc(652): error C3861: '_mm_prefetch': identifier not found
    .\similarity_search\src\method\pivot_neighb_invindx.cc(653): error C2065: '_MM_HINT_T0': undeclared identifier
    .\similarity_search\src\method\pivot_neighb_invindx.cc(653): error C3861: '_mm_prefetch': identifier not found
    .\similarity_search\src\method\pivot_neighb_invindx.cc(666): warning C4146: unary minus operator applied to unsigned type, result still unsigned
    .\similarity_search\src\method\pivot_neighb_invindx.cc(697): warning C4018: '<=': signed/unsigned mismatch
    .\similarity_search\src\method\pivot_neighb_invindx.cc(700): warning C4146: unary minus operator applied to unsigned type, result still unsigned
    .\similarity_search\src\method\pivot_neighb_invindx.cc(709): error C2065: '_MM_HINT_T0': undeclared identifier
    .\similarity_search\src\method\pivot_neighb_invindx.cc(709): error C3861: '_mm_prefetch': identifier not found
    .\similarity_search\src\method\pivot_neighb_invindx.cc(710): error C2065: '_MM_HINT_T0': undeclared identifier
    .\similarity_search\src\method\pivot_neighb_invindx.cc(710): error C3861: '_mm_prefetch': identifier not found
    .\similarity_search\src\method\pivot_neighb_invindx.cc(711): error C2065: '_MM_HINT_T0': undeclared identifier
    .\similarity_search\src\method\pivot_neighb_invindx.cc(711): error C3861: '_mm_prefetch': identifier not found
    .\similarity_search\src\method\pivot_neighb_invindx.cc(726): warning C4146: unary minus operator applied to unsigned type, result still unsigned
    .\similarity_search\src\method\pivot_neighb_invindx.cc(741): warning C4146: unary minus operator applied to unsigned type, result still unsigned
    .\similarity_search\src\method\pivot_neighb_invindx.cc(756): error C2065: '_MM_HINT_T0': undeclared identifier
    .\similarity_search\src\method\pivot_neighb_invindx.cc(756): error C3861: '_mm_prefetch': identifier not found
    .\similarity_search\src\method\pivot_neighb_invindx.cc(757): error C2065: '_MM_HINT_T0': undeclared identifier
    .\similarity_search\src\method\pivot_neighb_invindx.cc(757): error C3861: '_mm_prefetch': identifier not found
    .\similarity_search\src\method\pivot_neighb_invindx.cc(758): error C2065: '_MM_HINT_T0': undeclared identifier
    .\similarity_search\src\method\pivot_neighb_invindx.cc(758): error C3861: '_mm_prefetch': identifier not found
    C:\Users\me\AppData\Local\Temp\pip-install-w69gas4j\nmslib\similarity_search\include\params.h(188): warning C4244: '=': conversion from 'const DefaultType' to 'ParamType', possible loss of data
```

@searchivarius, where's the binary version you mentioned [above](https://github.com/nmslib/nmslib/issues/399#issuecomment-549759140)?

**Comment by snosrap** [comment]
@1653091's fix worked for me, which was to `#include <xmmintrin.h>` instead of `#include <mmintrin.h>` in `pivot_neighb_invindx.cc`

**Comment by searchivarius** [comment]
@snosrap thank you for letting me know. I guess the headers are messed up if you want to compile on your own (needs to be sort out). But now you can also install a binary version (by default).

**Comment by snosrap** [comment]
Hi @searchivarius, thanks for your response.

How do you install a binary version?

I'm installing using pip:
```
pip install nmslib
```
I get the `error C3861: '_mm_prefetch': identifier not found` error during the `pip install` process on my win10 laptop (works fine on my mac).

**Comment by searchivarius** [comment]
@snosrap ohh interesting could you try:
```
pip install nmslib --only-binary:all
```
Binary should be installed by default, but if it is not ... something is wrong.

**Comment by snosrap** [comment]
I had to use `pip install nmslib --only-binary all` (no colon)

But I still got the same compilation problem...

`pip install nmslib --only-binary all` starts running "setup.py install for nmslib", then errors with `error C3861: '_mm_prefetch': identifier not found` -- same as before

**Comment by searchivarius** [comment]
@snosrap which Python version do you have?

**Comment by snosrap** [comment]
```
Microsoft Windows [Version 10.0.16299.1625]

> python -V
Python 3.8.1

> pip -V
pip 20.0.2 from c:\users\me\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)
```

**Comment by searchivarius** [comment]
@snosrap unfortunately, we don't have 3.8 yet, 3.7 is the latest.

**Comment by snosrap** [comment]
Ah, that explains it.

Well, I'll be compiling my own using [this fix](https://github.com/snosrap/nmslib/commit/f3fe4f27c49a31f1afacd52b0133088bcd512bf4) in the meantime. Your windows compilation environment must have access to more header files than mine!

Thanks for looking into this.

**Comment by searchivarius** [comment]
@snosrap yes, the header needs to be fixed too for sure. It's surprising the header set isn't standard accross Windows machines though.

**Comment by jzthree** [comment]
I am encountering the same error for the conda-forge recipe that I maintain ( thanks for the awesome library! I am using it in another conda package that I made and nmslib was not available in the anaconda ecosystem yet so I made the recipe). All of the windows builds error out (for all python 3 versions) but Linux and OSX builds were fine (https://github.com/conda-forge/nmslib-feedstock/pull/6#partial-pull-merging).

I am not familiar with these headers but it does seem like the fix proposed in this thread (changing mmintrin.h to xmmintrin.h) agrees with Intel's docs that _mm_prefetch is part of xmmintrin.h (https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=4391&text=_mm_prefetch). 

I also found this useful https://stackoverflow.com/questions/11228855/header-files-for-x86-simd-intrinsics.

**Comment by searchivarius** [comment]
@jzthree yeah, these includes are wrong, I will try to fix them in the upcoming release.

**Comment by searchivarius** [comment]
Hi @jzthree we have updated headers in the develop branch. Could you check if this still causes a trouble? Many thanks!

**Comment by jzthree** [comment]
Great thanks! I can confirm the build problem is gone with the develop branch. The environment I tested was Windows 10 + python 3.8 + vs2017.

**Comment by searchivarius** [comment]
@jzthree awesome, many thanks! we will be rolling out this version quite soon.

**Comment by searchivarius** [comment]
Hi @NancyLi1013 I believe you won't need this patch for NMSLIB any more (once develop merges into master):
https://github.com/microsoft/vcpkg/blob/256d8a497a77f000168fe5a5b7c90a1962fa76ff/ports/nmslib/fix-headers.patch

**Comment by NancyLi1013** [comment]
Hi @searchivarius 
Thanks for your kindly reminder. Of course, we can remove this patch in next release if these changes merged to.
