### ISSUE TITLE
Bitpacked data instead of strings for bit_hamming?

### ISSUE THREAD

**Issue by Markusjsommer** [nmslib/nmslib#401]
Creating space-separated strings to add to a bit_hamming HNSW index adds quite a bit of overhead for large data sets that may already be in a compressed format (e.g. one-hot genomic data in a uint8 numpy array created with np.packbits). 

Is there a way to avoid creating strings representing binary data solely for the HNSW bit distance indexes, either in python or C++?

**Comment by searchivarius** [comment]
@Markusjsommer there's an overhead in passing the string to NMSLIB, but not in storing, b/c internally these strings are bit-packed into integers. So, if, e.g., you read a binary from disk, convert it to a string and pass a string to NMSLIB, there's virtually no space overhead.

Well, it's somewhat a hassle, but it's no clear how much interest would be in supporting passing bit-packed data from Python to nmslib directly to support this kind of optimization. But, of course, pull requests are welcome.

**Comment by searchivarius** [comment]
I am closing this for now, but, of course, if anybody wants to contribute a code that directly passes bit-vectors to NMSLIB, this is welcome.
