### ISSUE TITLE
_sparse suffixes for L_p spaces in documentation

### ISSUE THREAD

**Issue by CrafterKolyan** [nmslib/nmslib#403]
There is no `_sparse` suffixes in almost all `L_p` spaces in documentation ( https://github.com/nmslib/nmslib/blob/master/manual/spaces.md#lp-spaces )
Seems it should be `l1_sparse`, `l2_sparse` and `linf_sparse`

**Comment by searchivarius** [comment]
Indeed, thank you for noticing (added).
