### ISSUE TITLE
Issue with building in parallel

### ISSUE THREAD

**Issue by VasantVK** [nmslib/nmslib#404]
Hi, I was wondering if nmslib supported adding in data points in parallel? I see in the API reference, I can utilize num_threads for the query but my main issue is building the index. Below is a simple example I made where both functions work but return an empty array i.e. qq gives this: "(array([], dtype=int32), array([], dtype=float32))"

Any help would be appreciated. Thanks.

```
import nmslib
import multiprocessing
import numpy

def ex1(iArr):
    b = [iArr]
    index.addDataPointBatch(ids=range(multiprocessing.cpu_count()), data=b)

def ex2(iArr):
    b = [iArr]
    index.addDataPoint(id=0, data=b)

iArr = numpy.random.randint(1,10,(20,2))

index = nmslib.init(method='hnsw', space='l2')

p = multiprocessing.Pool(processes=multiprocessing.cpu_count())
p.map(ex1,iArr)
p.map(ex2,iArr)

index.createIndex()

qq = index.knnQuery(numpy.array([[5, 12]]), k=5)
print(qq)
```

I should also mention that it threw an error if I didn't do ```b = [iArr]```. This code snippet works though and returns an array of the ids and distances.
```
x = 0
for i in iArr:
    index.addDataPoint(id=x, data=i)
    x += 1
```

**Comment by searchivarius** [comment]
Hi @VasantVK no, unfortunately, there's no multi-threaded addition of data. Querying, however, is multi-threaded, but one needs to use ``knnQueryBatch``.

Regarding the error message, which function did it throw? You don't need an additional list for ``addDataPointBatch``. However, addDataPoint, if I remember correctly requires a vector, not a matrix. I suspect this was the function that raised the error. Please, refer to the notebook for a step-by-step example: https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_optim.ipynb

**Comment by VasantVK** [comment]
If I try to add the array (in the example below),
```
def ex1(iArr):
    index.addDataPointBatch(ids=range(multiprocessing.cpu_count()), data=iArr)
```

then I get an error message like this

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "m.py", line 6, in ex1
    index.addDataPointBatch(ids=range(multiprocessing.cpu_count()), data=iArr)
RuntimeError: data must be a 2d array
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "m.py", line 16, in <module>
    p.map(ex1,iArr)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: data must be a 2d array
```

I tried the same way with the ```addDataPoint``` but it didn't work either.

**Comment by searchivarius** [comment]
@VasantVK it looks like it chokes on int matrices. Please, try float32 matrices instead.

**Comment by VasantVK** [comment]
It does not work for that either. I changed the array to this ```iArr = numpy.full((10,2), numpy.float32(numpy.random.random()))```. It also does not seem to work for float64 as well.

**Comment by searchivarius** [comment]
Hi @VasantVK 
I cannot reproduce your issue.
Could you provide 
1. the minimal end-to-end example
2. Python version
3. Numpy version?
4. nmslib version

**Comment by VasantVK** [comment]
This is all the code I have. I am trying to implement it in another program so tested it here.

Python: ```Python 3.7.3```, Numpy: ```'1.16.4'```, nmslib: ```nmslib in /usr/local/lib/python3.7/site-packages (1.8)```

```
import nmslib
import multiprocessing
import numpy

def ex1(iArr):
    index.addDataPointBatch(ids=range(multiprocessing.cpu_count()), data=iArr)

def ex2(iArr):
    index.addDataPoint(id=0, data=iArr)

iArr = numpy.full((10,2), numpy.float32(numpy.random.random()))

index = nmslib.init(method='hnsw', space='l2')

p = multiprocessing.Pool(processes=multiprocessing.cpu_count())
p.map(ex1,iArr)
p.map(ex2,iArr)

index.createIndex()

qq = index.knnQuery(numpy.array([5,12]), k=5)
print(qq)
```

Can I ask what results you were getting? Thanks.

**Comment by searchivarius** [comment]
Hi @VasantVK sorry if I wasn't clear: there should be a single process that creates an index. I am not sure what are the side effects of multiprocessing.

**Comment by VasantVK** [comment]
In the example above, I think I am creating with a single process but am adding data points in parallel. But if it doesn't work that's fine. HNSW should work in the manner I want right?

**Comment by searchivarius** [comment]
Dear @VasantVK since I do not understand the code and why it uses multiprocessing, I cannot tell anything, sorry. You need to follow the code in the notebooks. If you have a single-process example, where it doesn't work as intended during indexing, feel, free to re-open this issue. But don't forget to produce an end-to-end piece of code.
