### ISSUE TITLE
loadIndex fails with MemoryError: std::bad_alloc & how to handle .dat suffix ?

### ISSUE THREAD

**Issue by mohamed-ali** [nmslib/nmslib#406]
Thanks for the effort you put in this library. 
I am facing two issues with loadIndex:

- A suffix .dat is added to the specified index name with no way to disable or change it.
- MemoryError for a relatively small index (2.0G) on a 32G server. 

First, I create and save the index as follows: 
```python
index = nmslib.init(method='hnsw', space='cosinesimil')
index.addDataPointBatch(data, _ids)
index.createIndex(['M=32', 'post=0', 'efConstruction=800'], print_progress=True)
index.saveIndex('saved_index.ndx')
```
the data contains roughly 6 million entries. 

### .dat suffix is added automatically to the filename

A `.dat` suffix is added to the file name `saved_index.ndx` with no way to disable or alter this behavior. This is not a blocker, I can rename the file. But I want to know if it's recommended to suffix the saved index filename with .dat?

### MemoryError

 As I mentioned, despite that the index index is relatively small (around 2.0G), when I try to load it, I get the error

```python
MemoryError: std::bad_alloc
```
The code I use to load the index is the following:

```python
index = nmslib.init(method='hnsw', space='cosinesimil')
index.loadIndex('saved_index.dat', print_progress=True)
```

I also tried loading the index with the following code: 

```python
In [3]: index = nmslib.loadIndex('saved_index.dat')
```
This fails with the error: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-6cc81673b456> in <module>()
----> 1 index = nmslib.loadIndex('saved_index.dat')

TypeError: loadIndex(): incompatible function arguments. The following argument types are supported:
    1. (arg0: object, arg1: object) -> object

Invoked with: 'saved_index.dat'
```

The error message and the function signature aren't very helpful to understand the input parameters or to debug.

I am using nmslib==1.8.1. 

Thanks.

**Comment by searchivarius** [comment]
Hi @mohamed-ali thank you for kind words. 
1. For L2 if you don't need distances calculations, you can disable saving data by setting ``save_data`` to false: https://nmslib.github.io/nmslib/api.html#nmslib.dist.FloatIndex.saveIndex
2. When loading index, don't add the prefix dat. ``saveIndex('someName')`` then ``loadIndex(someName)``.
Sorry about confusion with saving and not saving data. I plan to iron this out in future versions.
