### ISSUE TITLE
CPU utilization

### ISSUE THREAD

**Issue by Zheweiqiu** [nmslib/nmslib#407]
Hi,
I am using hnsw. When my program is running, I notice that my CPUs are fully occupied. I tried both knnQueryBatch(with num_threads set to 1) and knnQuery but there is no difference on cpu utilization. Each thread takes up to 400% CPU. I am not sure what causes this problem.  So I am wondering if hnsw causes this problem.
Any help will be appreciate!

**Comment by searchivarius** [comment]
Hi do you have a reproducible example? I think the code itself shouldn't be using all the threads unless you may run several threads or processes yourself.
