### ISSUE TITLE
pip install bug on arch linux

### ISSUE THREAD

**Issue by brendanchambers** [nmslib/nmslib#408]
In the file nmslib/python_bindings/setup.py,
Line 109 should read:
c_opts['msvc'].append("/arch:{}".format(os.environ['ARCH']))

Instead, it currently reads:
c_opts['msvc'].append("/arch:{}".format(os.envrion['ARCH']))

os.envrion -> os.environ 

This prevents installation on impacted arch linux distributions.

**Comment by brendanchambers** [comment]
Updating, fixed and submitted pull request. Thank you!

**Comment by brendanchambers** [comment]
Update:  After typofix, the AppVeyer build test failed for python 2 only. Python 3 checks passed. Other tests passed. Looks like a deeper issue, at least for python 2.

**Comment by searchivarius** [comment]
@brendanchambers Python2 is a known issue, I need to fix it. There's one function that is only available in Python3 and it does unit testing.

**Comment by brendanchambers** [comment]
Ah, makes sense. I'm using Python3 for what it's worth. Thanks!
