### ISSUE TITLE
import nmslib throws error

### ISSUE THREAD

**Issue by geetickachauhan** [nmslib/nmslib#410]
I am using scispacy UmlsLinker which relies on nmslib. Upon trying to import nmslib, I get the following
'ImportError: /envs/<conda_directory>/lib/python3.6/site-packages/nmslib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt6thread6_StateE'
Trace is the following:
`from scispacy.umls_linking import UmlsEntityLinker -> from scispacy.candidate_generation import CandidateGenerator -> import nmslib`

I used pip to install scispacy into my conda environment and exported that to a yml file. Subsequently, I created this conda environment in another machine using this yml file. There is no import issue in the original conda environment, but there is in this one.

**Comment by searchivarius** [comment]
Hi @geetickachauhan I am a bit confused. There seems to be an issue related to install nmslib with scispacy, indeed, but does it help if you install nmslib directly (i.e., on your own)?

**Comment by geetickachauhan** [comment]
Hi @searchivarius I have experienced this issue before when installing the same library with pip as well as conda. It is most likely related to that issue rather than nmslib not being present. I will investigate this further and post if I was able to solve this issue.

**Comment by searchivarius** [comment]
Hi @geetickachauhan I hope this issue doesn't happen anymore. If it is still an issue feel free to reopen, but I would need extra details to fix it.
