### ISSUE TITLE
Please could we have a point release?

### ISSUE THREAD

**Issue by DeNeutoy** [nmslib/nmslib#413]
It would be helpful if we could have a release which includes this commit:

https://github.com/nmslib/nmslib/commit/761b2f5ea46a765edaa655929cf8cbffa9d8855c

I think it may help ease install issues for scispacy.

Thanks!

**Comment by DeNeutoy** [comment]
oooh binary builds would be great. Honestly I don't know too much about packaging C++ libraries so they work cross platform, but happy to install things and see if they work etc. I'll drop you an email.

**Comment by searchivarius** [comment]
Hi @DeNeutoy we've incorporated the requirement for a more recent pybind11 and have provided the binaries. This should hopefully resolve most issues with installation. It is still always possible to install from sources for maximum performance.
