### ISSUE TITLE
get reverse cosine similarity results?

### ISSUE THREAD

**Issue by AdityaSoni19031997** [nmslib/nmslib#422]
How can we get the reverse results from the ```knnQuery```?
By reverse i mean, it computes the ```cosine dist``` let's say as ```-1*cosine_dist```?
i.e. the one which has the highest ```cosine dist``` should come first after i run the `knnQuery`..

**Comment by searchivarius** [comment]
@AdityaSoni19031997 it's very easy to do in Python, e.g., using numpy.
