### ISSUE TITLE
Sparse Jaccard Space fails for ultra-high dimensional input

### ISSUE THREAD

**Issue by fkaiserbio** [nmslib/nmslib#423]
Hi, 

I followed the [tutorial](https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_generic_sparse_jaccard.ipynb) for sparse jaccard spaces. It worked great and I tried to adapt it to my problem.

However, I have to deal with highly sparse data with dimensions in the range of >1B. I tried to add data points to the index with e.g. 

`index.addDataPoint(i, '2289927267 3696402029 4018138687')`

This fails with the error:

`space_sparse_jaccard.cc:61 (ReadIdList) Failed to parse the line: '2289927267 3696402029 4018138687'`

I guess it's because of the huge dimensionality and it works well for lower dimensions. Is there any way to make it work for these huge dimensions?

Thank you in advance
Florian

**Comment by searchivarius** [comment]
Hi @fkaiserbio sorry we don't support ids larger than the four byte **signed** int, sorry. However, does it really matter for approximate search? You can probably easily replace all your IDs with `id % 2147483648` or `id % 2147483647`. This should have a minuscule effect on the overall accuracy: and the search is approximate anyways.

**Comment by fkaiserbio** [comment]
Hi @searchivarius! Thanks for clarification and the suggestion. You are probably right, I will do the conversion of the IDs and test for the accuracy on our data.Thanks for your help and the great library!

**Comment by searchivarius** [comment]
You are most welcome, please, let me us know about results.

**Comment by fkaiserbio** [comment]
Just to let you know: I found my data to be bounded to four byte **unsigned** int. So I had easy times to  fit the full data by shifting it by `-2147483648`. Never thought about this before :man_facepalming:
The library works really great now. I don't have recall numbers yet, but first results looks really promising.
