### ISSUE TITLE
[Question] Loading index on disk instead of loading on RAM

### ISSUE THREAD

**Issue by alvations** [nmslib/nmslib#425]
Sorry if I haven't read the documentation fully but I have a few questions regarding the index loading. We have a pretty large index, created from:

```python
from tqdm import tqdm
import numpy as np
import nmslib

# Read the sentences from file.
with open("somefile.txt") as fin:
    sentences = map(str.strip, fin.readlines())

# `sentences` are just `list(sentences)`
sentences = list(set(sentences)) # Unique list.

# Converts sentences to arrays of floats.
vectorized_sents = [vectorize(s) for s in tqdm(sentences)]

# Concatenate the arrays.
data = np.vstack(vectorized_sents)

# Create the index
index = nmslib.init(method='hnsw', space='cosinesimil')
# Add data to index.
index.addDataPointBatch(data)
# The actual indexing.
index.createIndex({'post': 2}, print_progress=True)
```

We require a large around of RAM to load the whole index. 

 - Is there a way to incrementally index without locking down so much RAM?
 - Also, is there a way to load on disk and when querying prob the disk?
 - Currently our index is stored as one large binary, are there sharding mechanisms for `nmslib`?

Thank you in advance for the answers!!

**Comment by alvations** [comment]
Just realized I should be using gitter for this, closing issue =)
Sorry about that!

**Comment by searchivarius** [comment]
@alvations no worries, but thank you for moving this to gitter.
