### ISSUE TITLE
how to start with dataset of MNIST ?

### ISSUE THREAD

**Issue by ucasiggcas** [nmslib/nmslib#426]
hi,dear,
I just wanna to apply the method in MNIST,
could you help me ?

any advice or suggestion will be appreciated.
thx

**Comment by searchivarius** [comment]
Hi @ucasiggcas sorry it's outside of the scope of this project. However, if you want to apply k-NN search to images you need to get good representations first. Some activation layer of a convnet etc. In the case of MNIST doing PCA right on the vectors and taking 10 or components does the trick.
