### ISSUE TITLE
fail to use negdotprod with hnsw.

### ISSUE THREAD

**Issue by kelvi** [nmslib/nmslib#428]
fail to use negdotprod with hnsw.
When I use negdotprod with hnsw
I got error message below.

> hnsw.cc:350 (CreateIndex) [INFO] No appropriate custom distance function for negdotprod
> hnsw.cc:353 (CreateIndex) [INFO] searchMethod			  = 0

How could I use hnsw with negdotprod or some distance like inner product?

**Comment by searchivarius** [comment]
Sorry, I missed this one. You need to set the skip_optimized_parameter to 0 as in this notebook
https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_nonoptim.ipynb
This is inconvenient, sorry, I am planning to fix this in future versions.
