### ISSUE TITLE
How to implement multi-probe LSH in nmslib?

### ISSUE THREAD

**Issue by dongzhen123** [nmslib/nmslib#431]

**Comment by searchivarius** [comment]
@dongzhen123 what do you mean by implementing? Adding a new method?

**Comment by dongzhen123** [comment]
> @dongzhen123 what do you mean by implementing? Adding a new method?

How to use multi-probe LSH in nmslib

**Comment by searchivarius** [comment]
@dongzhen123 you need to use a somewhat older version. There's more than one multiprobe LSH BTW. One version is FALCONN and another one is LSHKIT. However, none of these was competitive on any data sets with graph-based retrieval.
