### ISSUE TITLE
Possible incorrect results when there is a large cluster of very similar vectors

### ISSUE THREAD

**Issue by adeelhasan** [nmslib/nmslib#432]
I have around 2 million dense image vectors, 512 dimensions each. For the most part, everything works great and the results come out and accurate and very swift. Thanks for manking this!

But every now and then, there are some images which are incorrectly returned in the results. These are from some groups of images which are very similar to each other. So you could say there are clusters of images which are very similar to each other (example of 400+ images here: [https://www.coroflot.com/fazilawani/Industrial-Design-Rest-Chair](url) )

It looks like these clusters can skew results. I am wondering if there are index creation options I can try to address this? Or is this a known limitation? One way could be to figure out these clusters and then perhaps only index one or two images from them.

Currently I initialize the index as:

```
index = nmslib.init(method='hnsw', space='cosinesimil')
index.createIndex(print_progress=True)
```

Any help is greatly appreciated, thanks.

**Comment by searchivarius** [comment]
Hi @adeelhasan it would be totally black magic to try solve this issue in this case. What about using HNSW to do efficient k-means clustering? If certain items are very-very close, maybe you don't have to index all of them in HNSW. If you know that item x is very close to item y_1, y_2, ..., y_k, you can try only indexing x. Whenever x is retrieved, you can also verify if y_i are sufficiently close.

**Comment by adeelhasan** [comment]
thanks for your reply, I had wanted to make sure I am not missing anything obvious. I will follow your advice and avoid indexing items that are very close.

**Comment by searchivarius** [comment]
Hi @adeelhasan there's also a heuristic that might work for highly clustered data, but enabling it requires recompilation.

**Comment by adeelhasan** [comment]
thanks for giving that as an option. I think in terms of my use case -- its an image search engine -- it would be better to not return results which are very close to each other (they would all reference the same content.)

so at the point of indexing, I am currently using a cosine matrix for seeing if a vector is too close to others. what package would you suggest to do the hsnw clustering?

also, I was trying to use:
index.getDistance(x,y)

I tried with valid int index values (array indices) as well as the data int keys when building the index. But in both cases I got:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-165-4539990689d2> in <module>
----> 1 nmslib_index.getDistance(100,111)

IndexError: invalid vector<T> subscript

Thanks

**Comment by searchivarius** [comment]
Do you use an optimized index? To get rid of very similar items, you can use k-NN search. Each time  before add a batch you run a query and check if there are very similar data points. It somewhat increases indexing time... In your case it is going to be even less than double, b/c your overall index is going to be much more compact and it will take little time to index. When you query, you can also get a list of distances, you **don't need a separate getDistance call.**

**Comment by adeelhasan** [comment]
Not using an optimized index -- would you have a suggestion as to which one?

In my use case, data is organized by user folders. So I go through folder by folder and do more of a brute force calculation of distances, marking out those which are too close (cosine distance is > 0.999). Each folder is at most a few thousand items, and my hypothesis is that items that are very close to each other could cause a problem for other optimized indexes as well. At best I only have to do this once in my use case, and at worst periodically. Once weeded out (I estimate 10-20 user folders in about a million), I can continue to use nmslib.

**Comment by searchivarius** [comment]
When I say non-optimized I am refering to setting a special flag: https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_nonoptim.ipynb

**Comment by adeelhasan** [comment]
ok, so you are saying to make an non-optimized index and then use that to find the very similar items. let me try that out.

**Comment by searchivarius** [comment]
@adeelhasan actually not quite so, never mind. I don't have time to explain it, but basically currently (and this is an issue) getIndex doesn't work properly if you don't reload the data. The easiest way to check for duplicates is to carry k-NN search and check what distances it returns. If your dataset is small you can do bruteforce (NMSLIB supports it too) or HNSW. If you search within a small sub-folder a chance to miss anything is small. Plus, I guess it's ok to index a similar item once or twice, it shouldn't affect performance too much. The issue I guess is when you have a lot of similar items indexed, if you can remove even 50% of these, you will get a boost. Plus, it is always faster to search a smaller data set.
