### ISSUE TITLE
is it possible to specify different query params for each query?

### ISSUE THREAD

**Issue by ophiry** [nmslib/nmslib#437]
currently setQueryTimeParams set the query params for the index. is is possible to override these for specific queries?

**Comment by searchivarius** [comment]
Unfortunately, it is not possible now.

**Comment by ophiry** [comment]
are there any downsides for calling setQueryTimeParams for each call?

**Comment by searchivarius** [comment]
@ophiry it has a small cost. I didn't measure it, but I suspect it's way faster than doing k-NN search. If you use knnQueryBatch, it's likely negligible.

**Comment by searchivarius** [comment]
@ophiry PS: in C++ API it's a bit of an issue, b/c the call isn't thread safe.

**Comment by searchivarius** [comment]
Let me close this, as, probably, one can use a different setting for each query batch without much overhead.
