### ISSUE TITLE
ID_SIZE is written to LABEL_SIZE by mistake

### ISSUE THREAD

**Issue by Dreamerzp** [nmslib/nmslib#438]
in the file object.h , inline LabelType label()    const { return *(reinterpret_cast<LabelType*>(buffer_ + LABEL_SIZE)); }   , although ID_SIZE and LABEL_SIZE are both int32_t , I think ID_SIZE  is better。

**Comment by searchivarius** [comment]
Thank you @Dreamerzp could look at the commit? I shouldn't affect anything, but it's good to fix for clarity.
