### ISSUE TITLE
is there simple java code to read graph and get knn

### ISSUE THREAD

**Issue by liyuanzhe** [nmslib/nmslib#439]
your java client code is so complicated 
i donnot konw how to calculate knn by java 
it seems that java client is just a thrift client? 

how to read graph and calculate knn by java?
not providing service

**Comment by searchivarius** [comment]
There's no simple way, sorry. But you can just query for nearest neighbors using Python/C++/or Java API after the graph is constructed. If you use Python make sure you use knnQueryBatch with a large batch as it's much faster.
