### ISSUE TITLE
ef_search and ef_construction paramters

### ISSUE THREAD

**Issue by naveenkumarmarri** [nmslib/nmslib#441]
I'm trying to tweak `ef_search` and `ef_construction` parameters.
Is there a one to one mapping between these parameters? For instance, if I have `ef_construction` as `512` and `ef_search` as `1024` does it actually help in improving the recall of the search?

**Comment by searchivarius** [comment]
They are symmetric in the sense that both define the quality of the retrieval. However, ef_construction affects the quality of index-time retrieval. Thus, the higher is the value of ef_construction, the better is the graph. ef_search applies only to retrieval time "thoroughness" of search. In practice, it rarely makes sense to increase ef_construction beyond 200-400. A likely reason is that the graph quality affects retrieval quality somewhat indirectly.

Instead, try to increase M. ef_search has a more profound effect on retrieval quality than ef_construction, which should be jast large enough.
