### ISSUE TITLE
requires_dist specifies numpy version <1.17 for Python 3

### ISSUE THREAD

**Issue by jjjamie** [nmslib/nmslib#445]
https://pypi.org/pypi/nmslib/json returns `requires_dist` field that specifies numpy <1.17 (introduced in https://github.com/nmslib/nmslib/commit/be36b2be130789c04eddce3382cff72efdc4b676#diff-535bcc8311fdc34129ee96ab7738ba25, I think to reflect numpy >=1.17 not being supported under Python 2)

```
"requires_dist": [
      "pybind11 (>=2.2.3)",
      "psutil",
      "numpy (<1.17,>=1.10.0)"
    ],
```

This means that resolving versions forces numpy version <=1.16 , even for Python 3 where the restriction isn't needed - which causes incompatibility with another package I'm using (this is a problem because I'm using `poetry` where the dependency resolution is stricter than pip - if I install with pip it'll tell me about the incompatibility but work anyway).

I believe https://github.com/nmslib/nmslib/pull/443, raised ~2 weeks ago, should fix it - AppVeyor and Travis CI pipelines pass - thought I'd create an issue in case that hadn't been spotted.

**Comment by akdor1154** [comment]
Hi @searchivarius - this is still stopping nmslib from being installable with new numpy in projects that enforce dependency constraints properly. If there's likely to be much more work before develop is pulled into master, is there any chance of backporting the fix for this into master?
As said, this prevents me from installing nmslib at all.

**Comment by searchivarius** [comment]
@akdor1154 it's fixed in develop right?

**Comment by akdor1154** [comment]
I think so, because #446 got merged. However I can't really ensure this because the problem's only visible when trying to install a prebuilt wheel from pypi (and the latest wheel is 2.0.6 from April '20).

**Comment by searchivarius** [comment]
@akdor1154 ok, I am working on some test script (should be ready soon), then I will build binaries. sorry about the delay, I am trying to be more thorough with this (and future) release.

**Comment by akdor1154** [comment]
No worries, thanks - can work around by e.g. depending on github url directly for now. :)

**Comment by frankier** [comment]
Like many larger C/C++ projects containing optional Python bindings, the setup.py is in a subdirectory, so at least this poetry issue: https://github.com/python-poetry/poetry/issues/755 would need to be addressed before we can install from GitHub.

**Comment by searchivarius** [comment]
@akdor1154 and @jjjamie the fix should be in the latest release. Thank you! Do let me know if there's still a problem.

**Comment by akdor1154** [comment]
thanks for all your hard work!

**Comment by searchivarius** [comment]
sorry about delays, it should get faster this year :-)

**Comment by charliermarsh** [comment]
I think _some_ of the wheels in the latest release still have the incorrect metadata.

For example, [this wheel](https://files.pythonhosted.org/packages/8e/95/d8c595464322fafe539cba88457159c70d9d66c6877602343e0c7651fcdb/nmslib-2.1.1-cp39-cp39-manylinux2014_aarch64.whl.metadata) contain:

```
Requires-Dist: numpy (<1.17,>=1.10.0) ; python_version == "2.7"
Requires-Dist: numpy (>=1.10.0) ; python_version >= "3.5"
```

While [this other wheel](https://files.pythonhosted.org/packages/15/97/6f7f05cf605601426664ccf665d235a0d20875e606e32ca87496f66b71ce/nmslib-2.1.1-cp35-cp35m-macosx_10_14_x86_64.whl.metadata) contains:

```
Requires-Dist: numpy (<1.17,>=1.10.0)
Requires-Dist: numpy (>=1.10.0)
```
