### ISSUE TITLE
Issue when creating generic Lp spaces

### ISSUE THREAD

**Issue by davisidarta** [nmslib/nmslib#448]
Hi all!

I'm improving my dimensionality reduction method to address reviewers' comments on it. The key to improving speed and scalability was to implement a nmslib wrapper within it to carry out a fast k-ANN search. I have implemented it [here](https://github.com/davisidarta/dbMAP/blob/master/src/dbmap/ann.py). 

So far, nmslib has worked amazingly well in these settings. However, based on [this work](https://link.springer.com/chapter/10.1007/3-540-44503-X_27), for queries with k higher than 10, the euclidean distance becomes non-informative and unable to discriminate properly between nearest and farthest neighbors, resulting in the development of fractional p-norm spaces as a sucessfull workaround.  Thus, I would like to implement fractional p metrics with my method using nmslib. Yet, when trying to run any Lp space, I get (here p =2):

```
 File "/usr/local/lib/python3.8/dist-packages/dbmap/ann.py", line 198, in fit
    self.nmslib_ = nmslib.init(method=self.method,
RuntimeError: 2020-07-26 00:44:54 spacefactory.h:50 (CreateSpace) It looks like the space lp:p=2 is not defined for the distance type : FLOAT
```
Similarly, running [nmslib sample notebook](https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_optim.ipynb) while setting `space_name='lp:p=2'` returns:

```
space_name='lp:p=2'
# Intitialize the library, specify the space, the type of the vector and add data points
index = nmslib.init(method='hnsw', space=space_name, data_type=nmslib.DataType.DENSE_VECTOR)
index.addDataPointBatch(dat)
>>3.8.2 (default, Apr 27 2020, 15:53:34) 
>>[GCC 9.3.0]
>>NMSLIB version: 2.0.6
>>Index-time parameters {'M': 30, 'indexThreadQty': 10, 'efConstruction': 100, 'post': 0}
>>Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 26, in <module>
>>RuntimeError: 2020-07-26 01:30:11 spacefactory.h:50 (CreateSpace) It looks like the space lp:p=2 is not defined for the distance type : FLOAT
```
Any hints on what might be causing this unexpected error? 

Cheers

**Comment by searchivarius** [comment]
ohh shoot, turns out that when we create a space with parameters, it's done differently from the command line tool. And because nobody used it before... anyways, I need to update the docs, but the right way to pass space parameters is via an extra argument:
```
index = nmslib.init(method='hnsw', space=space_name, space_params={'p':0.3},  ...
```

**Comment by searchivarius** [comment]
PS: ** and space name should be** lp

**Comment by davisidarta** [comment]
Thank you @searchivarius ! Easily solved, indeed :)

**Comment by searchivarius** [comment]
I am happy to see people exploring additional spaces. I have modified the docs to include this information: https://github.com/nmslib/nmslib/blob/develop/manual/spaces.md#specifying-parameters-of-the-space
