### ISSUE TITLE
Can nmslib-hnsw indexes be loaded via mmap?

### ISSUE THREAD

**Issue by RamanRajarathinam** [nmslib/nmslib#449]
Hi,

I have been exploring "hnsw" indexes and need some clarification on the same

1. Say If I want to load a large index (size=3G), does nmslib load "hnsw" indexes via mmap by default?  or Are there any methods that could help me load the indexes efficiently? any best practices?

2. Also I would like to know if there is any way to speed up index creation, other than setting high "indexThreadQty"?

My usual params would be,
```
index_time_params = {
    "M": 15,
    "indexThreadQty": 8,
    "efConstruction": 100,
    "post": 0,
}
```

**Comment by searchivarius** [comment]
No mmap sorry.

**Comment by RamanRajarathinam** [comment]
May I know that is there any other possibilities to efficiently load index?

**Comment by searchivarius** [comment]
Hi @RamanRajarathinam the only way to speed up indexing (without increasing the number of cores) is to decrease M and efConstruction. However, this does affect the quality of the index. So your parameters are actually low enough. Well, maybe efConstruction=50 can still work reasonably well. 

There's no other way to load the index. If you use an optimized version of the index, it doesn't need to load data separately, unless you want to compute distances. So, if you use data_data or load_data flag and your distance is L2 or cosine you can set these flags to False.
