### ISSUE TITLE
NMSlib fails with > 10e6 samples

### ISSUE THREAD

**Issue by davisidarta** [nmslib/nmslib#450]
Hi all!

I'm trying to apply NMSlib to a very large dataset (1.3M samples) with the 'cosinesimil_sparse_fast' space metric. I've implemented a [custom script to call NMSlib,](https://github.com/davisidarta/dbMAP/blob/master/src/dbmap/ann.py) and everything works neatly up to some hundred thousands of samples. Yet, when I try to analyze bigger datasets, I get the following error:

```
Check failed: resQty == pVal2 - val2
Check failed: resQty == pVal2 - val2
Check failed: resQty == pVal2 - val2
Check failed: resQty == pVal2 - val2
Check failed: resQty == pVal2 - val2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davisidarta/anaconda3/lib/python3.7/site-packages/dbmap/diffusion.py", line 133, in fit  #This is my library
    verbose=self.verbose).fit(data)
  File "/home/davisidarta/anaconda3/lib/python3.7/site-packages/dbmap/ann.py", line 216, in fit      # This is my custom NMSlib script
    self.nmslib_.createIndex(index_time_params)
RuntimeError: Check failed: it's either a bug or inconsistent data!
```

Any insights on what might be happening here? I've checked and re-checked the input data, and subsampling it to 50% of its original size doesn't return the same error, neither does running the command with similar datasets. All inputs are csr sparse matrices. I'm running python 3.8 on a arch-based HPCC.

**Comment by searchivarius** [comment]
Is it sparse data? There's a bug that is fixed, but not pushed to master/pypi where an empty vector causes an exception.

**Comment by davisidarta** [comment]
Thank you for answering @searchivarius. Yes, I'm using sparse data. Yet, I don't think I have any empty vectors within this data. All my nmslib installations are through pypi.

**Comment by searchivarius** [comment]
@davisidarta which space do you use?

**Comment by davisidarta** [comment]
I used the 'cosinesimil_sparse_fast' space for this specific example. The same space runs flawlessly on subset data.

**Comment by davisidarta** [comment]
I was able to solve the problem after checking more carefully for empty AND near-empty vectors. Everything runs smoothly now. BTW: NMSlib takes about 15min to run on this data using 10 cores (biggest biological dataset available). What a fantastic library! Thank you for the help and attention, @searchivarius !

**Comment by searchivarius** [comment]
@davisidarta thanks a lot for checking, could you explain what near-empty vectors are?
PS: I wish we had a more production-ready library.

**Comment by davisidarta** [comment]
@searchivarius  By 'near-empty' vectors I meant vectors with <100 non-null observations. Removing those solved the problem. Apparently that can become an issue as the data grow larger, as I've never faced it before even when dealing with similarly sparse but smaller data with as few as 50 non-null observations per sample.

**Comment by searchivarius** [comment]
ohh no this isn't right. and it should be relatively easy to reproduce. could you share these vectors?
