### ISSUE TITLE
This should not happen. For some reason the elements is already added

### ISSUE THREAD

**Issue by sh1ng** [nmslib/nmslib#451]
Hi,

Only see it when running nmslib in k8s pod. The same data set(can be shuffled) runs ok locally. 
Could you elaborate about the error?

**Comment by searchivarius** [comment]
Hi @sh1ng what's exactly the problem? Could you elaborate?

**Comment by sh1ng** [comment]
Sorry, looks like multiple threads were adding duplicated.
May be it's worth to make the message more explicit about it.
