### ISSUE TITLE
Your CPU supports instructions that this binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2

### ISSUE THREAD

**Issue by TamHHM** [nmslib/nmslib#458]
My processor is AMD Ryzen 9 3900X, running on Ubuntu 18.04. I used the cosinesimil_sparse_fast distance. Some folks said that AVX instructions can dramatically increase the computational speed. Is there a way to enable them? I found a similar instruction to do this with tensorflow and MAC [here](https://technofob.com/2019/06/14/how-to-compile-tensorflow-2-0-with-avx2-fma-instructions-on-mac/).

**Comment by searchivarius** [comment]
On Ubuntu it should pretty straightforward to install from source code:
```
pip install --no-binary :all: nmslib
```

**Comment by searchivarius** [comment]
PS: Yes there would be some gains from using SSE (actually you don't even need AVX), but it may not be as dramatic if vectors have only few non-zero elements. That is it makes sense primarily when your vectors are quite large (in terms of non-zero elements). The brute-force search with sparse metrics should be sped up considerably.

**Comment by TamHHM** [comment]
Thanks you your reply. The warning went away.
