### ISSUE TITLE
Out-of-memory while indexing

### ISSUE THREAD

**Issue by TamHHM** [nmslib/nmslib#459]
I am  indexing a sparse data of 43798758x16384 sparse matrix of type '<class 'numpy.bool_'>' 	with 1228841224 stored elements in Compressed Sparse Row format. My machine ran out of memory while indexing:
```
space_name='cosinesimil_sparse_fast'
efC = 200
M = 50
index_time_params = {'M': M,
                     'efConstruction': efC,
                     'post' : 2}
graph = nmslib.init(method='hnsw', space=space_name,
                    data_type=nmslib.DataType.SPARSE_VECTOR,
                    dtype=nmslib.DistType.FLOAT
                   ) 
graph.addDataPointBatch(data, idx)
graph.createIndex(index_time_params, print_progress=True)
graph.saveIndex("gragh.bin", save_data=False)
```
The machine is a 64Gb Ram laptop running Ubuntu. Is there a way of mitigate this?

**Comment by searchivarius** [comment]
A couple of questions:
1. What the memory usage after addDataPointBatch?
2. Are there large gaps between adajcent non-zero IDs, say 1M?
PS: M=50 is probably an overkill, please, try M=30.

**Comment by TamHHM** [comment]
Thanks for your reply. Using htop command:
  - Before addDataPointBatch, RAM usage: 15.7 G
  - After addDataPointBatch, RAM usage: 26.7 G
RAM usage gradually increases while indexing. It gets worse if save_data=True (do not know why)

I don't know about the gap. The vector is generated by counting the number of two-grams in strings. Each grams is hashed in to a random bucket which is about 100 times more than the number of possible grams (for collision avoidance purpose). Thus, I don't know how to measure the gap, but the bucket dimension is just 16384 in my case so the gap should be definitely less than 1M if I understand you correctly.

**Comment by searchivarius** [comment]
@TamHHM ohh if the max dimension is 16K it is fine. Yeah, just try to decrease M.

**Comment by TamHHM** [comment]
Hi, I still crashed with  M=10, efConstruction=200. I noticed that it crashed after the second process bar reached 100%. Does it mean it crashed while saving the indexes?

![Selection_008](https://user-images.githubusercontent.com/40778683/97427583-e093ae00-1968-11eb-9942-5c6cd73a7417.png)

**Comment by searchivarius** [comment]
@TamHHM ohh please set the value of the parameter `post` to 0. You can then probably increase M to 15.

**Comment by TamHHM** [comment]
Thanks, I was able to run with M=30, efConstruction=200. This mean the post processing step consumes quite some memory, doesn't it? Does skipping it mean I will have a worse recall?

**Comment by searchivarius** [comment]
@TamHHM this specific post-processing step constructs another index. Regarding recall, you might lose a bit, but not much. Maybe even nothing at all. According to my own experiments, post > 0 is less helpful for sparse data.

**Comment by TamHHM** [comment]
Thank you. I were not awared that 64G of RAM would not be enough to index 40mil records. Assuming my database keeps increasing to 100mil+ or even 1bil+, I think that I need to split the database in smaller chunks then indexing them separately. At query time, I can query each chunks separately then combine the results and get the top k. Since querying is quite fast, it seems feasible to do this. What do you think about this? Are there other tricks?

**Comment by searchivarius** [comment]
@TamHHM there are some relatively little inefficiency related to the library itself. However, a big thing is that storing all the data in uncompressed format and not being able to compress the index itself is a big disadvantage in terms of space efficiency. You may try to use traditional IR, e.g., Lucene. Inverted files are easy to compress and they are a good fit for the maximum inner product in the very sparse setting. However, they can become slow when you have large queries, documents and especially if you do document-to-document search. In summary, Lucene is an option.
