### ISSUE TITLE
proprietary, problematic and unused images in git repository

### ISSUE THREAD

**Issue by pabs3** [nmslib/nmslib#460]
I'm working on getting [gensim](https://radimrehurek.com/gensim/) into [Debian](https://www.debian.org/) and the next step in that process is to get nmslib into Debian.

While reviewing the nmslib git repository I noticed that the `data/data_conv/sqfd/sample/` directory contains a [copy](https://github.com/nmslib/nmslib/blob/master/data/data_conv/sqfd/sample/lena.png) of the [Lenna](https://en.wikipedia.org/wiki/Lenna) image. This image is [copyright by Playboy Enterprises, Inc](http://www.lenna.org/optical.html) and has not been released under an open source license. This image is also [considered problematic](https://en.wikipedia.org/wiki/Lenna#Criticism) by some folks, who say it is degrading to women and an example of sexism in science.

In addition, [the street scene](https://github.com/nmslib/nmslib/blob/master/data/data_conv/sqfd/sample/street.jpg) in the same directory has "Camera: Google" in the metadata. I am guessing that this is a screenshot from Google Street View. If it is then it is copyright by Google or one of its partners and is very unlikely to have been released under a free license.

The [remaining image](https://github.com/nmslib/nmslib/blob/master/data/data_conv/sqfd/sample/from_thesis.jpg) appears (according to Google reverse image search and the source code in the parent directory) to have been taken from one of a few ([1](http://doi.acm.org/10.1145/1816041.1816105) [2](https://dl.acm.org/doi/abs/10.1145/2806416.2806459) [3](http://btw2017.informatik.uni-stuttgart.de/slidesandpapers/Tutorial/MSS_slides.pdf) [4](https://web.archive.org/web/20190114220407/http://publications.rwth-aachen.de/record/229392) [5](https://web.archive.org/web/20170809110457/http://dme.rwth-aachen.de/en/system/files/file_upload/publications/p438_Beecks.pdf)) different publications/presentations by Beecks et al. Presumably the copyright for the image lies with one of the authors, or with one of the universities they worked at and presumably it has not been released under a free license.

These images and the directory they are located in do not appear to be used by the code as far as I can tell.

In order to get nmslib into Debian, everything in the source package needs to be under a free software license, so it would be helpful if they could be removed from the git repository.

It seems that @bileg [added](https://github.com/nmslib/nmslib/commit/41305c7bf1d6a82c75b0befacd45e0f85a775ad7) these images in 2014, hopefully they have some insight into this situation.

**Comment by searchivarius** [comment]
It is not used anywhere and was committed clearly by mistake. Thanks for notifying us!
I deleted it from the main and develop branch. Is it problematic if we have them in some other unused branches?

**Comment by pabs3** [comment]
Excellent, thanks for removing them!

Personally I would remove them from all branches, but it doesn't affect
me if you want to leave them on the unused branches, as long as there
won't be any releases made from those branches.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by searchivarius** [comment]
Removed everywhere, to the best of my knowledge, thanks!
