### ISSUE TITLE
Clear nms index memory

### ISSUE THREAD

**Issue by bipinkc19** [nmslib/nmslib#465]
I am running a job where after some fixed time the code reruns in the background re-running the part where nms index is initialized and data points are added.

But I am getting errors due to huge memory consumption after sometimes.

My guess is either, vectors are being repeatedly added to a same index or different indexes are being initialized.

So my question is,

How can we empty a nmlib index or completely delete it from memory so we can initialize a new one.

**Comment by searchivarius** [comment]
Hi @bipinkc19 memory should be freed once your index variable is out of scope. Although bugs are always possible, there's a test for memory leaks and I also wrote a little program to demonstrate that memory should be normally cleared, please, see the attached file, you need to run it like this:
```
./test_clear_mem.py '/Users/leo/TextCollect/VectorSpaces/unif100K_100d.txt'
```
[test_prog.zip](https://github.com/nmslib/nmslib/files/5730085/test_prog.zip)

**Comment by bipinkc19** [comment]
So, I guess when I assign the index variable to a class's self variable, it would never release it!?

I usually have to hold on to the index and get the nearest vectors once request is issued.  And I have to refresh it every "x" minutes. When refreshing I guess the index is always in scope, so when i do, self.index.operations the vectors are just  piling up instead of clearing memory.

What would you suggest in this case?

**Comment by searchivarius** [comment]
Hi @bipinkc19 out of scope was defined a bit vagule. It should have been more like: "there's no live variable that keeps a reference to the index". Before anything else, could you run the attached program with the attached data like this one and paste the output?
```
./test_clear_mem_class.py unif100K_100d.txt 
```

**Comment by bipinkc19** [comment]
Yes, I ran the attached program. It is clearing the memory or the memory size is constant.

**Comment by bipinkc19** [comment]
So, using
`del self.index _var`

should do the trick?

**Comment by bipinkc19** [comment]
Closing the issue, I guess the problem is somewhere else in my code.

**Comment by searchivarius** [comment]
Hi @bipinkc19 it might be, hard to tell, it might be some pybind11/Python quirk. I am really curious if del worked for you? I believe it should not be the space here though:

> del self.index _var
