### ISSUE TITLE
error import nmslib after building from source

### ISSUE THREAD

**Issue by zioufang** [nmslib/nmslib#471]
after building from source with the `setup.py`, when I tried to import nmslib got this error
```
Python 3.9.1 (default, Jan  8 2021, 17:17:17)
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nmslib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Object of type 'Logger' is not an instance of 'module_'
```
Tried with python v3.9.1 and v3.7.9 on MacOS and Ubuntu 18.04. All got exactly the same error.

Not sure if it is the cause but there is a warning against a missing file `similarity_search/src/main.cc`, which i checked it is indeed not in this repo:
`warning: no previously-included files matching 'similarity_search/src/main.cc' found anywhere in distribution`

Also using pip no-binary install on all the older versions > 2.0.5 gave the same error as well, e.g.
`pip install --no-dependencies --no-binary :all: nmslib==2.0.5`

**Comment by searchivarius** [comment]
Does it work with older Python versions?

**Comment by cristianmtr** [comment]
I'm experiencing the same. Python 3.7.9 on Ubuntu 20.04

**Comment by searchivarius** [comment]
There seem to be some issues with incomplete release.

**Comment by DicksonK** [comment]
I am experiencing the same (Python 3.7.9 MacOS) but `2.0.11` didn't do the trick for me

Also I noticed that pypi failed to get the latest version when `--no-binary :all:`

Installed with pip
`pip install --no-dependencies --no-binary :all: nmslib==2.0.11`

Return the following error
`ERROR: Could not find a version that satisfies the requirement nmslib==2.0.11 (from versions: 1.6.3, 1.7, 1.7.1, 1.7.2, 1.7.3.1, 1.7.3.2, 1.7.3.3, 1.7.3.4, 1.7.3.6, 1.8, 1.8.1, 2.0.4, 2.0.5, 2.0.6, 2.0.9)
ERROR: No matching distribution found for nmslib==2.0.11`

**Comment by searchivarius** [comment]
We are having multiple deployment issues. I apologize for this and I will work on resolving this next week. Unfortunately, for some reason the latest version on pypi lacks the tar ball. To install from sources, it is easiest to download the latest version ([tagged 2.0.11](https://github.com/nmslib/nmslib/releases/tag/v2.0.11)) and just just do
```
pip install -r requirments.txt
python setup.py 
```
from the ``python_bindings`` folder.

**Comment by maumueller** [comment]
I've experienced the same issue. The problem was fixed by using the previous release of pybind11 (`pip install pybind11==2.6.1`).

**Comment by searchivarius** [comment]
thanks a lot @maumueller something got broken recently and I was struggling with building a proper release. That might have been it. Hold on, let's see if this was *THE* issue.

**Comment by searchivarius** [comment]
@zioufang @cristianmtr @DicksonK sorry about the issue, I believe it should be fixed now. Make sure you delete all the remainings of the older version when you install a new one. It should 2.1.1. Have to jump versions due to PyPi quirks. Feel free to reopen the issue or comment if it's still not working.

**Comment by jknix** [comment]
@searchivarius may be worth adding something to the readme temporarily noting that those versions were removed. I was able to find this issue and figure things out, but it's not going to be intuitive to someone in 2-3 months why nmslib 2.0.9 is gone and their build is failing. Thanks for your work sorting out the release issues! Greatly appreciated.

**Comment by searchivarius** [comment]
@jknix yes, it's a good thought. I am going to chart the release and I can add these notes there, but I haven't done it yet. Unfortunately, PyPi has this policy of not letting re-upload a deleted build. Overall, sorry, this release was plagued by a lot of issues. I will have to set up a test pypi account to prevent such issues in the future.

**Comment by searchivarius** [comment]
PS: @jknix what else could be a good place to mention that these releases were gone due to deployment shenanigans?

**Comment by jknix** [comment]
@searchivarius maybe in [the quickstart docs](https://github.com/nmslib/nmslib/blob/master/docs/_sources/quickstart.rst.txt)? I feel like if it's posted there, on the readme, and PyPi, that should be plenty sufficient. At that point, if anyone can't find it then they cannot possibly be looking. I think a quick note in each place along the lines of "Note: Users who have previously installed versions 2.0.7-2.0.13 will need to uninstall and reinstall nmslib >= 2.1.1 for compatibility." Thanks!

**Comment by searchivarius** [comment]
@jknix thank you! I added a [note here](https://github.com/nmslib/nmslib/blob/master/docs/_sources/quickstart.rst.txt#notes-about-issues-with-deploying-version-20x).

Fortunately, not so many people install `nmslib` from sources. Interestingly enough, it was possible to build binaries and they passed the test so apparently
