### ISSUE TITLE
No appropriate custom distance function for AngularDistance

### ISSUE THREAD

**Issue by zyh3826** [nmslib/nmslib#474]
what this information means, why this information occurs, Thx
my code is:

> nms_index = nmslib.init(method="hnsw", space="angulardist")
nms_index.addDataPointBatch(self.embeddings.numpy(), ids=list(self.vocab.values()))
nms_index.createIndex({'post': 2}, print_progress=True)
nms_index.saveIndex(model_save_path, save_data=True)

BTW, what's the meaning of the parameter "index_params " in createIndex method, thank you very much

**Comment by searchivarius** [comment]
@zyh3826 sorry, this was introduced recently, apparently. I didn't really test the angular distance, only the cosine, ohh. You can probably force create it as a non-optimized index. For some reason it doesn't happen automatically. Indexing parameters are parameters used to select parameters of the indexing algorithm.

**Comment by searchivarius** [comment]
@zyh3826 which NMSLIB version do you use?

**Comment by zyh3826** [comment]
@searchivarius Hi, thanks for your reply, my version is 2.1.1

**Comment by searchivarius** [comment]
@zyh3826 could you provide a complete standalone piece of code, which also prints the version? I tried to reproduce your code, but it worked for me. Thank you!

**Comment by searchivarius** [comment]
Hi @zyh3826 I am closing this. There's no proper explanation as to how this occurs. I suspect it's a message from the log, but this doesn't cause the code crash or anything. Performance for angular distance is somewhat subpar compared to using the cosine similarity, although both are equivalent in terms of results.
