### ISSUE TITLE
Use random seed for NMS index building

### ISSUE THREAD

**Issue by oujiafan** [nmslib/nmslib#477]
In HNSWLib we support passing random_seed, but seems not in NMSLib. We will get different results when we build index at different times.
There's a seed in InitLibrary, but seems not for this purpose.

**Comment by oujiafan** [comment]
Thank you @searchivarius .
I got ~0.5% absolute value variance for recall, when I run NMSLib multiple times. 
I changed NMSLib index build to single thread and still got difference. Is there any workaround to get it stable for single thread? Though it could be arguable that if it makes sense to do that.

**Comment by searchivarius** [comment]
Hi @oujiafan I have to take it back that HNSW construction isn't affected by random numbers in a single thread mode. Sorry for misleading you. The random number generator is initialized only when you load the library, sorry. So when you run a new experiment it naturally uses a different sequence of random numbers.

**Comment by oujiafan** [comment]
OK. So we don't use random seed.

**Comment by searchivarius** [comment]
We do. Do you load nmslib only once per experiment?
