### ISSUE TITLE
Custom Metrics

### ISSUE THREAD

**Issue by Chokerino** [nmslib/nmslib#478]
Hello,

I wanted to perform NN search on a dataset of genomes. For this task, the distance between 2 datapoints is calculated by a custom script? Is there I can incorporate this without having to create the entire NN search algorithm myself and only modify some parts of your code?

**Comment by searchivarius** [comment]
Hi @Chokerino custom metrics require writing C++ code.

**Comment by Chokerino** [comment]
@searchivarius that should not be an issue. The distance calculation is a part of another C++ script and it takes 2 filenames as parameters. Is there somehow I can incorporate this with my datapoints being strings or maybe I could use something like a hashmap and input the hash into the library?

**Comment by searchivarius** [comment]
Hi @Chokerino you can use an existing Levenstein space as an example more information can be found here:

https://github.com/nmslib/nmslib/blob/master/manual/extend.md

It needs to be a space that accepts data in string format, an example of passing strings:
https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_generic_sparse_jaccard.ipynb

**Comment by Chokerino** [comment]
@searchivarius I created the space but when I make changes to space and recompile the library, the changes don't get reflected. I am assuming the space register isn't getting called again. How do I reinitialise the space every time I recompile the library?

**Comment by searchivarius** [comment]
Hi @Chokerino did you re-run cmake after the space is added and when did you place the respective .cc files?
```
Note that no explicit/manual modification of makefiles (or other configuration files) is required. However, you have to re-run cmake each time a new source file is created (addition of header files does not require a cmake run). This is necessary to automatically update makefiles so that they include new source files.
```
***BTW, you may need to remove the cmake cache.***

Once you ran the cmake once and with all the files, make should automatically identify changed files.

**Comment by Chokerino** [comment]
@searchivarius I have not created any .cc files and have only created 2 .h files similar to that of the Levenstein distance. Running cmake again even after deleting the cache has had no changes.

**Comment by searchivarius** [comment]
@Chokerino dependencies need to be updated even these are just h files? How would make know what needs to be recompiled? 

Also, make sure you add registration code to the space factory. As a sanity check, remove cmake cache and all object files, then cmake . and compile again.

**Comment by Chokerino** [comment]
@searchivarius I think there is some confusion or I am just not able to understand. So I created 2 `.h` files, one in `similarity_search/include/space/` which has the main implementation of the Hidden Distance and one in `similarity_search/include/factory/space/` which has the create space function. Also, added the registration in `init_spaces.h`. I had compiled this version but wanted to make changes. To recomple, I have tried deleting the cache(deleting the CMakeCache.txt file) and running cmake again followed by make followed by re-compiling the python bindings. This does not reflect changes I made in the HiddenDistance.

**Comment by searchivarius** [comment]
Ohh if you are testing directly through Python bindings you need to reinstall them.

**Comment by searchivarius** [comment]
Rebuild and reinstall.

**Comment by Chokerino** [comment]
@searchivarius thanks got it to work!
Also another small issue the `object->data()` is stored as a `const char *` but the function I need to use needs `char *`. I have tried straight casting, const_cast and various other methods but there is always some garbage value gets added to some of the strings. Any idea how to do this?

**Comment by searchivarius** [comment]
@Chokerino was it a reinstallation issue? There's a version of data that returns just plain char, but make sure you call the data function and not the buffer function:

```
  inline const char* data() const { return buffer_ + ID_SIZE + LABEL_SIZE+ DATALENGTH_SIZE; }
  inline char* data()             { return buffer_ + ID_SIZE + LABEL_SIZE+ DATALENGTH_SIZE; }
```
because buffer will return aux. info in the beginning:
```
  inline const char* buffer()  const { return buffer_; }
```

**Comment by Chokerino** [comment]
@searchivarius I had not properly rebuilt the library as the cache wasn't being deleted.
So, if I use `char* x = obj1->data();` there are some garbage values in the strings like `/global/homes/c/cjain7/shared/projects/ANI/data/Bacillus_anthracis/Bacillus_anthracis_GCA_002980615_2.LargeContigs.fna�t!`. I do not understand how to explicitly call the `char *` function because by default that should be called right? 
Using `char* x = obj1->data();` fails on compilation because cannot convert `const char *` to `char *` and `char* x = (char *)obj1->data();`  throws error `*** Error in `python': munmap_chunk(): invalid pointer: 0x0000555555ddb250 ***`. 

Adding my function definition just in case.
```
virtual float HiddenDistance(const Object* obj1, const Object* obj2) const {
    CHECK(obj1->datalength() > 0);
    CHECK(obj2->datalength() > 0);
    char* x = (char *) obj1->data();
    char* y = (char *) obj2->data();
    char* command[] = {"./fastANI", "-q", x, "-r" , y};
    float result = dist::getDistance(command);
    return 100 - result;
  }
```

**Comment by searchivarius** [comment]
@Chokerino ohh actually I just realized that the auto-conversion to char won't work, because Object pointer are const. Now, the solution to this is not to cast to `char *`, but to make the command to be of the type `const char`.

Regarding garbage: How do you implement `CreateObjFromStr`? Whatever you use inside NMSLIB should eventually be disconnected from Python-allocated objects, which may disappear any time.

**Comment by Chokerino** [comment]
@searchivarius I haven't implemented `CreateObjFromStr` yet. Should I make it similar to the ones used in other spaces?

**Comment by searchivarius** [comment]
@Chokerino may be or may be not, I had another look at your above comment and I think I understand now why you get garbage.  The default `CreateObjFromStr` in the string space **does not store the trailing zero character**. For the easiest way out, I recommend using our function `CreateStrFromObj`, which returns a C++ string object, so `c_str()` will create a proper c-style string for you.

**Comment by Chokerino** [comment]
@searchivarius `CreateStrFromObj` worked. Thanks alot!

**Comment by searchivarius** [comment]
Awesome I hope the custom metric will be quite useful.

**Comment by Chokerino** [comment]
@searchivarius are the parameters in hnsw for this library the same as the hnswlib ones? Because for the same parameters, I am getting very different results in the two. I mean for hnswlib,

**Comment by searchivarius** [comment]
The implementations aren't the same but they are similar.

**Comment by Chokerino** [comment]
@searchivarius I am unable to use `vp-tree` and get the error `RuntimeError: 2021-07-13 21:18:04 methodfactory.h:60 (CreateMethod) It looks like the method vp-tree is not defined for the distance type : FLOAT`.

**Comment by searchivarius** [comment]
It's `vptree'.

**Comment by Chokerino** [comment]
@searchivarius i created a pull request to make it consistent with the docs

**Comment by searchivarius** [comment]
updated thank you!

**Comment by Chokerino** [comment]
@searchivarius Could you please tell me how the pivots are being selected for NAPP. Is it completely random?

**Comment by searchivarius** [comment]
@Chokerino they can be either random or provided from an external source. If they are random they are saved with the index.

**Comment by Chokerino** [comment]
hey @searchivarius, I am suddenly getting blank predictions for some points in one of my custom metrics. Do you know what could possibly cause this?

**Comment by searchivarius** [comment]
It's not even clear what blank prediction means.

**Comment by Chokerino** [comment]
@searchivarius multiple indices of the output of `index.knnQueryBatch()` are `array([], dtype=int32), array([], dtype=float32`

**Comment by searchivarius** [comment]
Could you be more specific? An example of the output with a small batch size and an explanation what is wrong. Also did try tobrun the bruteforce search?
