### ISSUE TITLE
CPU instructions AVX and AVX2 not supported on a windows machine

### ISSUE THREAD

**Issue by ivan-marroquin** [nmslib/nmslib#483]
Hi,

Thanks for such great package!

I have a windows 64 machine with Python 3.6.5 and nmslib 2.1.1

The nmslib package was installed using "pip install nmslib" without issues. When, I use another package that makes use of nmslib, I get the message below:

Your CPU supports instructions that this binary was not compiled to use: AVX AVX2
For maximum performance, you can install NMSLIB from sources
pip install --no-binary :all: nmslib

So, I decided to uninstall nmslib and re-install it using the command mentioned above. Then, I ran the other package that makes use of nmslib, and I still get the same message below.

What is the meaning of this message? 

Ivan

**Comment by searchivarius** [comment]
Hi @ivan-marroquin it just doesn't use these instructions, sorry. We have binaries for Windows, which are somewhat less efficient. Hopefully, we will be able to select an instruction subset dynamically one day (though it's tricky).
