### ISSUE TITLE
Incorrect result when using 3D data

### ISSUE THREAD

**Issue by ivan-marroquin** [nmslib/nmslib#487]
Hi,

I have windows 10 64 bits with Python 3.6.5 and nmslib 2.1.1. I get incorrect querying results when using 3D data sets. To duplicate the incident:

import nmslib
data= np.random.randn(1000,3)
index= nmslib.init(method= 'hnsw', space= 'lp', space_params= {'p': 0.1}, data_type= 
                              nmslib.DataType.DENSE_VECTOR, dtype= nmslib.DistType.FLOAT)
index.addDataPointBatch(data)
index_params= {'M': 15, 'indexThreadQty': 4, 'efConstruction': 100, 'post': 1, 'skip_optimized_index': 0}
index.createIndex(index_params= index_params)
nbrs= index.knnQueryBatch(data, k= 241, num_threads= 4)
np.shape(nbrs)

The last Python command gives the following error message and incorrect output dimension
C:\Temp\Python\Python3.6.5\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
(1000, 2)

Since the output of the query command is a list, when I try to convert it into an array I get this error message:
np.asarray(nbrs, dtype= np.float32)
TypeError: only size-1 arrays can be converted to Python scalars
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\numpy\core\_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

To illustrate what it is the desired output, I use the following Python commands:
import pynndescent
index_p= pynndescent.NNDescent(data, metric= 'minkowski', metric_kwds= {'p': 0.1}, n_neighbors= 241, 
                                                         random_state= 1969, n_jobs= 4)
index_p.prepare()
idx_p, d_p= index_p.query(data, k= 241)
idx_p.shape, d_p.shape
(1000, 241), (1000, 241)

Ivan

**Comment by searchivarius** [comment]
Hi @ivan-marroquin I am not sure it should conform with NNDescent, please, see the sample notebook. If it doesn't work as prescribed, feel free to re-open the issue:
https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_lp.ipynb

**Comment by ivan-marroquin** [comment]
Hi @searchivarius ,

I used pynndescent to illustrate that the output of nbrs= index.knnQueryBath() should provide two lists: distances and indices. 

I ran more tests, I found that the issue is not related to the shape of the input data set but rather to the number of neighbors used in the query. 

So, if I replace the old command:
nbrs= index.knnQueryBatch(data, k= 241, num_threads= 4)

By this new one:
nbrs= index.knnQueryBatch(data, k= 10, num_threads= 4)

Then, I get the expected result - as it is confirmed by the command:
np.shape(nbrs)
(1000, 2, 10)

I believe this incident should be re-opened. perhaps, the title does not make more sense as the issue is more related to the number of neighbors

Hope this helps,

Ivan

**Comment by searchivarius** [comment]
Hi @ivan-marroquin there's a known issue that k-NN search can return fewer than k results: #172
Is this the ultimate issue that you have? Do you know how many fewer than k?
Unfortunately, this issue is somewhat tricky to fix and the fix may affect efficiency.

**Comment by ivan-marroquin** [comment]
Hi @searchivarius ,

Thanks for your prompt reply. My challenge is the following, I am dealing with datasets that show high distance concentration. So, I need to test several k-neighbors to see what is the most suitable value. Once I found one, then I can generate index and distance matrices that are used for further analyses. With respect your questions, I don't have a fixed k-neighbors but rather I look for the "optimal" one.

Ivan

**Comment by ivan-marroquin** [comment]
Reading the description of #172, one of my datasets has a size of 296180 x 3 and when using k= 240, the computation fails as shown above. The returned output is of 296180 x 2, and if you try to convert it to array or print its shape. The same error messages - as shown above - are displayed

**Comment by searchivarius** [comment]
@ivan-marroquin could you share a data subset? Or maybe even a complete data set. It shouldn't be big.

**Comment by ivan-marroquin** [comment]
[input_data.zip](https://github.com/nmslib/nmslib/files/6658603/input_data.zip)

**Comment by searchivarius** [comment]
It worked just fine, see the attached. Please note that we don't return results the way NNDescent does it, so simply casting to an np-array won't work. Sometimes there will be fewer than K entries and that would screw up np.asarray.

I understand that you may get fewer than K results is annoying, hopefully I can fix it soon, but not immediately, sorry.

[test_cube.zip](https://github.com/nmslib/nmslib/files/6659007/test_cube.zip)

**Comment by searchivarius** [comment]
PS: @ivan-marroquin it's often interesting to play with people's data. Turns out that on your dataset, you can use even a VP-tree. It's exact version is a bit slower than HNSW, but it's approximate variant seems to be actually a bit faster. The indexing time is a bit long, because the model auto-tunes to achieve a desired recall, but, in principle, you can manually select the best query-time parameters and avoid auto-tuning in the future. See, the attached notebook. Also the VP-tree is likely to always return K neighbors.
[test_cube_vptree.ipynb.zip](https://github.com/nmslib/nmslib/files/6659553/test_cube_vptree.ipynb.zip)

**Comment by ivan-marroquin** [comment]
Thanks so much!
