### ISSUE TITLE
any example for l2_sparse distance?

### ISSUE THREAD

**Issue by abmitra84** [nmslib/nmslib#495]
Hi @searchivarius ,

Is there an example of how to use `l2_sparse` ? I have already used 'sparse_jaccard' with great success (both speed and recall) for sparse binary vectors. 

If I have data like below and given that more than 95% of cells would be 0 so using 'l2' seems to be computationally expensive. It is is taking about 2 hours to index 1 mn rows. And then `knnQuery` a single id takes ~ 100 ms for large K. I think 'l2_sparse' will reduce the computational expense but not entirely sure if it works with this kind of data. Your input is highly appreciated

`arr = [[0.5, 0,0.25,0,...., 1,,0,0,0,1,0], [0.35, 0, 0.05, 0,1,0....,0,0,0,0]]`

**Comment by searchivarius** [comment]
Hi @abmitra84 for generic questions, we recommend using [gitter](https://gitter.im/nmslib/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

That said, you can use the following notebook, just replace the distance name with `l2_sparse` (I just checked that it works file):

https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_sparse_cosine.ipynb

**Comment by abmitra84** [comment]
Cool. Thank you again !

**Comment by abmitra84** [comment]
Just came to provide a feedback. 'l2_sparse' did fantastic and cut down the indexing time by 95% and search time by 66% for 1mn * 2000 dimension search space with M values >40 and a very large K.

**Comment by searchivarius** [comment]
Awesome news, thank you for feedback!
