### ISSUE TITLE
Dealing with NAN or no-data values

### ISSUE THREAD

**Issue by MarcYin** [nmslib/nmslib#510]
Is there a way to deal with NAN or no-data value in the library? 

The current implementation seems treats them as 0 and producing results that are far away from inputs. Ultimately, those no-data values should be excluded in the distance computation and return the k nearest neighbours that closest to the remaining valid values.

Marc.

**Comment by searchivarius** [comment]
Hi @MarcYin no we don't support NaNs and I am not sure we should. This seems to be a rather arbitrary requirement. Why is it useful in the first place? More generally, it may make sense to provide some sort of masked distance implementation, but I think it's not good to use NaNs for masking. With respect to a masked distance implementation, what is the right level of generality for such a distance?

In sum,
1. Treating NaNs as masks should not be supported
2. A specialized masked distance might be implemented, but it is not clear how useful it will be to users (and that is a separate issue).
3. For generic discussions about potential functionality it is best to use a chat here https://gitter.im/nmslib/Lobby

**Comment by MarcYin** [comment]
Thanks a lot for the prompt reply. 

Yes, masked distance would be a more general case. It is useful if the input is time series, and normally missing values exists in time series signals and they can appear randomly in the time series. If no such a mechanism to deal with the missing values, you will need to do some sort of imputation, but the imputation could be arbitrary and bring overheads for the computation.

Marc.

**Comment by searchivarius** [comment]
Agree on imputations, but I would think time series will have variable number of entries? This may require a more customized distance than L2 on "dense" vectors.

**Comment by MarcYin** [comment]
Yes, that could be the case. But cases like earth observation data, time series of satellite images have the same length (along time) while having missing values, like clouds for optical images, randomly distributed in the images. There should be other cases where continuous measurements are taken, but the measurements are not always being useful. It would be really useful for time series of earth observation data analysis if there is a native way to deal with missing values rather then doing imputation first….

**Comment by searchivarius** [comment]
I see, yet, it's a good question if we should support the use of NaNs as missing values or have a custom distance. Detecting NaNs makes computation slower. Furthermore, if you detect them using a non-SIMD isnan function, this function is a dummy with the current compilation flags (thanks C++ for this wonderful feature). So, at the very least, this needs to be a separate custom L2 space, b/c not everybody wants a slow-down due to dealing with NaNs.

**Comment by MarcYin** [comment]
I think it’s better to just allow for masked or even better weighted distance if uncertainty or qa information available and missing values will have zero weightings.
