### ISSUE TITLE
saveIndex() with remote file path raises "RuntimeError: Check failed: Cannot open file <path> for writing"

### ISSUE THREAD

**Issue by owenvallis** [nmslib/nmslib#512]
saveIndex() accepts a string path to save the file, but this fails when saving to a remote file. Passing other file objects like tf.io.gfile.GFile() are not currently supported. We would like to be able to do something like the following:

```
path = "/REMOTE/FILE"
with tf.io.gfile.GFile(path, "wb+") as f:
  _search_index.loadIndex(f, load_data=True)
```

**Comment by searchivarius** [comment]
Hi @owenvallis 
unfortunately
1. the library cannot use Python descriptors to load indices
2. it doesn't support remote files for this reason

sorry, this is something difficult to implement, especially, if we do something for other languages then Python.

**Comment by owenvallis** [comment]
Thanks for the quick reply. I'll try and save locally using nmslib and then use the Python descriptors to save to the user provided path.
