### ISSUE TITLE
Combine `LICENSE` and `LICENSE-Apache-2.0` into one file?

### ISSUE THREAD

**Issue by mbrukman** [nmslib/nmslib#515]
As of commit https://github.com/nmslib/nmslib/commit/ae1a18230bebe9b159f1a5a610ef1060373807d9 (PR https://github.com/nmslib/nmslib/pull/455), there are now two license files:

* [`LICENSE`](https://github.com/nmslib/nmslib/blob/ae1a18230bebe9b159f1a5a610ef1060373807d9/LICENSE) with just a single line: 

  > The code is released under the Apache License Version 2.0 http://www.apache.org/licenses/. 

* [`LICENSE-Apache-2.0`](https://github.com/nmslib/nmslib/blob/ae1a18230bebe9b159f1a5a610ef1060373807d9/LICENSE-Apache-2.0) with the contents of the Apache 2.0 license

This causes GitHub to report that there are two licenses on the repo overview page:

![NMSLIB GitHub repo overview](https://user-images.githubusercontent.com/4074659/171070910-a2919987-d21e-4eb3-bfc4-c98732e97c21.png)

For clarity, would you mind combining both of these files into a single file `LICENSE` with just the contents of the Apache 2.0 license?

**Comment by searchivarius** [comment]
Thanks for pointing out. Does it look better now?

**Comment by searchivarius** [comment]
seems fine now. :-)
