### ISSUE TITLE
Build failure on OSX

### ISSUE THREAD

**Issue by cwelton** [nmslib/nmslib#520]
System information:
> OSX: 12.5
> Chip: Apple M1 Max
> Apple clang version 13.1.6 (clang-1316.0.21.2.5)
> Target: arm64-apple-darwin21.6.0
> Thread model: posix
> Python 3.10.2

$ pip3 install nmslib

Results in `clang: error: the clang compiler does not support '-march=native'`

> ...
> Installing collected packages: nmslib
>  Running setup.py install for nmslib ... error
>  error: subprocess-exited-with-error
>  
>  × Running setup.py install for nmslib did not run successfully.
>  │ exit code: 1
>  ╰─> [20 lines of output]
>      Dependence list: ['pybind11<2.6.2', 'psutil', "numpy>=1.10.0,<1.17 ; python_version=='2.7'", "numpy>=1.10.0 ; python_version>='3.5'"]
>      /Users/cwelton/.pyenv/versions/3.10.2/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
>        warnings.warn(
>      running install
>      running build
>      running build_ext
>      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Users/cwelton/.pyenv/versions/3.10.2/include/python3.10 -c /var/folders/zm/wl2cwllx1y3gv5m_5bw6ngy80000gn/T/tmpeqcxm6js.cpp -o var/folders/zm/wl2cwllx1y3gv5m_5bw6ngy80000gn/T/tmpeqcxm6js.o -std=c++14
>      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Users/cwelton/.pyenv/versions/3.10.2/include/python3.10 -c /var/folders/zm/wl2cwllx1y3gv5m_5bw6ngy80000gn/T/tmpzf2wt8g1.cpp -o var/folders/zm/wl2cwllx1y3gv5m_5bw6ngy80000gn/T/tmpzf2wt8g1.o -fvisibility=hidden
>      Extra compilation arguments: ['-O3', '-march=native', '-stdlib=libc++', '-mmacosx-version-min=10.7', '-DVERSION_INFO="2.1.1"', '-std=c++14', '-fvisibility=hidden']
>      building 'nmslib' extension
>      creating build
>      creating build/temp.macosx-12.1-arm64-3.10
>      creating build/temp.macosx-12.1-arm64-3.10/similarity_search
>      creating build/temp.macosx-12.1-arm64-3.10/similarity_search/src
>      creating build/temp.macosx-12.1-arm64-3.10/similarity_search/src/method
>      creating build/temp.macosx-12.1-arm64-3.10/similarity_search/src/space
>      creating build/temp.macosx-12.1-arm64-3.10/tensorflow
>      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I./similarity_search/include -Itensorflow -I/Users/cwelton/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pybind11/include -I/Users/cwelton/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pybind11/include -I/Users/cwelton/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pybind11/include -I/Users/cwelton/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pybind11/include -I/Users/cwelton/.pyenv/versions/3.10.2/lib/python3.10/site-packages/numpy/core/include -I/Users/cwelton/.pyenv/versions/3.10.2/include/python3.10 -c ./similarity_search/src/distcomp_bregman.cc -o build/temp.macosx-12.1-arm64-3.10/./similarity_search/src/distcomp_bregman.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO="2.1.1" -std=c++14 -fvisibility=hidden
>      clang: error: the clang compiler does not support '-march=native'
>      error: command '/usr/bin/clang' failed with exit code 1
>      [end of output]
>  
>  note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
>
> × Encountered error while trying to install package.
>╰─> nmslib

**Comment by cwelton** [comment]
This looks like a dup of #476, I'll add some comments there.

**Comment by searchivarius** [comment]
Hi @cwelton it should be fixed in the master, but it's taking me a while to produce a release due to issues with CI.

Could you try installing directly from github, this would be a nice test to see if the fix is actually working. Many thanks and you could use something like:
```
pip install git+https://github.com/nmslib/nmslib.git
```

**Comment by atwoodjw** [comment]
@searchivarius Tried to install directly from GH, but got this error.

```
$ pip install git+https://github.com/nmslib/nmslib.git
Collecting git+https://github.com/nmslib/nmslib.git
  Cloning https://github.com/nmslib/nmslib.git to /private/var/folders/ff/xz3x_2sd5rlcr9fy627mqn6w0000gn/T/pip-req-build-5tl92hfx
  Running command git clone --filter=blob:none --quiet https://github.com/nmslib/nmslib.git /private/var/folders/ff/xz3x_2sd5rlcr9fy627mqn6w0000gn/T/pip-req-build-5tl92hfx
  Resolved https://github.com/nmslib/nmslib.git to commit ade4bcdc9dd3719990de2503871450b8a62df4a5
ERROR: git+https://github.com/nmslib/nmslib.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by searchivarius** [comment]
@atwoodjw aaargh, sorry, setup.py is currently not in the root folder, but in the python_bindings directory. Something to fix in the future. You can clone, cd to python_bindings and do python setup.py
