### ISSUE TITLE
Can you provide some C++ examples  ？

### ISSUE THREAD

**Issue by xddun** [nmslib/nmslib#523]
Thank you for your work and dedication.

I can't convert the following python code to C++ . Can you give me some examples or suggestions ？

python:
```
def knn_nmslib(feats, k, space='cosinesimil'):
    index = nmslib.init(method='hnsw', space=space)
    index.addDataPointBatch(feats)
    index.createIndex({'post': 2}, print_progress=True)
    neighbours = index.knnQueryBatch(feats, k=k, num_threads=multiprocessing.cpu_count())
    return neighbours
```

c++:

'''
void knn_nmslib(std::vector<std::vector<float>> feats, std::vector<std::pair<std::vector<int>, std::vector<float>>>& neighbours, int k)
{

}
'''

**Comment by searchivarius** [comment]
Hi @xddun  we have examples here:
https://github.com/nmslib/nmslib/tree/master/sample_standalone_app
