### ISSUE TITLE
Feature request/question: bipartite knn?

### ISSUE THREAD

**Issue by iosonofabio** [nmslib/nmslib#524]
Hi there and thank you for the extremely useful libraries, both this one and https://github.com/nmslib/hnswlib.

Does either library support bipartite knn?

In other words, if I have two lists of vectors A and B, I want to give it a certain element in A (call it A_i) and ask what are the k nearest elements in B. Ideally, I'd like to have it for all elements in A (there might be some speed-up by batch-querying, I guess).

If not, are you aware of any library/paper where they do it? Or alternatively, do you think one could hack either of your libraries to work in that situation?

Thank you for your time,
Fabio

**Comment by searchivarius** [comment]
Hi @iosonofabio although it may be possible to do via some clever merging, it is not clear if you can do better than:
1. indexing set A
2. batch query A using B
3. do the procedure in the other direction
I do not think, it's going to be crucial to have this as a feature.

**Comment by iosonofabio** [comment]
Thank you - will try that way. Closing.
