### ISSUE TITLE
Failed to load index that is built on sparse space

### ISSUE THREAD

**Issue by netang** [nmslib/nmslib#525]
I can't load index saved to file.

My steps:
Creating index and saving to a file:
```python
M = 100
efC = 2000
post = 0

index = nmslib.init(method='hnsw', space='negdotprod_sparse', data_type=nmslib.DataType.SPARSE_VECTOR) #negdotprod_sparse cosinesimil_sparse angulardist_sparse
index.addDataPointBatch(data=sim_matrix)
index_time_params = {'M': M, 'efConstruction': efC, 'post' : post} 

index.createIndex(index_time_params)

index.saveIndex('/tmp/nmslib_hnsw_index_slim', save_data=True)
```
Loading index from a file:
```python
index = nmslib.init(method='hnsw', space='negdotprod_sparse', data_type=nmslib.DataType.SPARSE_VECTOR) # negdotprod_sparse cosinesimil_sparse
index = index.loadIndex('/tmp/nmslib_hnsw_index_slim') # , load_data=True
```

And I am getting the following error
```
ERROR:nmslib:Check failed: totalElementsStored_ == this->data_.size() The number of stored elements 10678 doesn't match the number of data points 0! Did you forget to re-load data?

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [108], line 2
      1 index = nmslib.init(method='hnsw', space='negdotprod_sparse', data_type=nmslib.DataType.SPARSE_VECTOR) # negdotprod_sparse cosinesimil_sparse
----> 2 index = index.loadIndex('/tmp/nmslib_hnsw_index_slim')

RuntimeError: Check failed: The number of stored elements 10678 doesn't match the number of data points 0! Did you forget to re-load data?
```
I looked at the issue https://github.com/nmslib/nmslib/issues/356 and tried using the `save_data=True` and `load_data=True` params, but that didn't help.
Can you please tell me if `nmslib` supports such a scenario?

**Comment by searchivarius** [comment]
Hi @netang annoyingly for sparse data one needs to re-read data on their own. Sorry about that:
https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_sparse_cosine.ipynb

**Comment by netang** [comment]
> Hi @netang annoyingly for sparse data one needs to re-read data on their own. Sorry about that: https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_sparse_cosine.ipynb

I'm sorry, I had a mistake in the line

```python
index = index.loadIndex('/tmp/nmslib_hnsw_index_slim', load_data=True)
```
i fixed it to

```python
index.loadIndex('/tmp/nmslib_hnsw_index_slim', load_data=True)
```
and now it's working.

Thx!

**Comment by searchivarius** [comment]
@netang ohh, that's right, I incorrectly assumed that data won't be loaded, but, indeed, it will. It's a bit annoying the API allows you to do the incorrect thing, sorry.
