### ISSUE TITLE
Sparse dataDataPointBatch could support sparse matrices directly

### ISSUE THREAD

**Issue by celsofranssa** [nmslib/nmslib#527]
The notebook kernel crash when running this sparse index:

```python
import numpy as np
from scipy import sparse
import nmslib

row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1., 1., 1., 1., 1., 1.])
m = sparse.csr_matrix((data, (row, col)), shape=(3, 3))

# initialize a new index, using a HNSW index on Cosine Similarity
index = nmslib.init(method='hnsw', space='jaccard_sparse', data_type=nmslib.DataType.SPARSE_VECTOR)
index.addDataPointBatch(m)
index.createIndex()
```

**Comment by searchivarius** [comment]
Hi @celsofranssa unfortunately currently you cannot pass sparse matrices directly, there's a crutch to pass data via string format (see in the example the conversion function). Something to fix in the future:
https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_generic_sparse_jaccard.ipynb

**Comment by celsofranssa** [comment]
Thank you!
